In [ ]:
#put this script in the same folder with all the below files (ppid refers to participant id):
# 1. Minute physiological data
# 2. Minute posture data (Majoriites per 60sec_ppid_day1 or Majoriites per 60sec_ppid_day2)
# 3. EMA data (though this is optional as it is not provided on GitHub due to being sensitive data)
# 4. Lab calibration data (contains the calibration factors for the spirometer, as well as paced breathing baseline regression coefficients)

# MERGING DATA
## HORIZONTALLY MERGING EACH PARTICIPANT'S PHYSIOLOGICAL MINUTE EPOCH DATA WITH DETECTED MINUTE POSTURE DATA, VERTICALLY MERGING EACH PARTICIPANT'S DAY1 AND DAY 2 DATA, AND FINALLY VERTICALLY MERGING ALL PARTICIPANT DATA TO GET AN OVERALL DATAFRAME WITH ALL PHYSIOLOGICAL MINUTE EPOCHS AND POSTURES

In [1]:
#import the necessary libraries
import os  #for handling the file directory/path
import pandas as pd
from glob import glob

# specifying the directory/repository that the files are located in 
base_path = r"C:\Users\msa583\OneDrive - Vrije Universiteit Amsterdam\Desktop\RSA Analyses Post-Processing\RQ2"

# identifying the physiological minute epoch xls files that end with _1 or _2 (for the different days)
physio_files = glob(os.path.join(base_path, "*_[12].xls"))

# extract the participant id using the file names (the first part until the first underscore _)
participant_ids = set()
for file in physio_files:
    basename = os.path.basename(file)
    participant_id = basename.split('_')[0]
    participant_ids.add(participant_id)

# define an empty list to collect everything
all_data = []

# looping through each participant (sorted by id)
for pid in sorted(participant_ids, key=int):
    for day in [1, 2]:
        # defining the paths and naming conventions for the physio and posture files
        physio_file = os.path.join(base_path, f"{pid}_{pid}_{day}.xls")
        posture_file = os.path.join(base_path, f"Majoriites per 60sec_{pid}_day{day}.csv")

        # checking if both the physio and the posture files exist
        if os.path.exists(physio_file) and os.path.exists(posture_file):
            try:
                # load the excel physiological data
                physio_df = pd.read_excel(physio_file)

                # loading the csv posture data and choosing only the "Majority_postures" column
                posture_df = pd.read_csv(posture_file, usecols=["Majority_postures"])

                # horizontally -side by side- merging the physio and posture dataframes
                merged_df = pd.concat([physio_df, posture_df], axis=1)

                # adding the participant id and day number as new columns, so the merged_df represents the data for one participant, one day
                merged_df["participant_id"] = pid
                merged_df["day"] = day

                # append the merged dataframe to the all_data list
                all_data.append(merged_df)

            except Exception as e:
                print(f"Error processing participant {pid}, day {day}: {e}")
                
#all day contains the list of all the merged_dfs 
# make all data into one dataframe by vertically stacking the individual dataframes
final_df = pd.concat(all_data, ignore_index=True)

# view the first lines of the overall dataframe
print(final_df.shape)
final_df.head()
print(len(final_df))

(84356, 45)
84356

In [2]:
# save as excel
final_df.to_excel(os.path.join(base_path, "all_participants_merged.xlsx"), index=False)

In [3]:
#calculating the mean absolute percentage error for the spirometer (against the gold standard fixed volume calibration syringe)
#this is a standalone operation that does not affect our main dataframe
import os
import pandas as pd
import numpy as np

# setting the directory including the lab calibration files
calibration_dir = r"C:\Users\msa583\OneDrive - Vrije Universiteit Amsterdam\Desktop\RSA Analyses Post-Processing\RQ2"
calibration_files = [f for f in os.listdir(calibration_dir) if f.startswith("lab_calibration_") and f.endswith(".xlsx")]

# dictionary to store participant percentages
spirometer_percentages = {}

# loop through each file
for file in calibration_files:
    participant_id = os.path.splitext(file)[0].split("_")[-1]
    file_path = os.path.join(calibration_dir, file)
    df = pd.read_excel(file_path)
    
    if "spirometer_estimation_3l" in df.columns:
        percentage = df["spirometer_estimation_3l"].iloc[0]
        spirometer_percentages[participant_id] = percentage
        print(f"Participant {participant_id}: {percentage:.2f}%")
    else:
        print(f"Participant {participant_id}: 'spirometer_estimation_3l' column not found")

# calculate MAPE across the 42 procedures
if spirometer_percentages:
    percentages = np.array(list(spirometer_percentages.values()))
    absolute_errors = np.abs(100 - percentages)
    mape = np.mean(absolute_errors)
    print(f"\nMean Absolute Percentage Error (MAPE): {mape:.2f}%")

Participant 12008: 101.06%
Participant 13304: 99.91%
Participant 15337: 100.89%
Participant 24340: 102.95%
Participant 25201: 98.96%
Participant 25879: 100.09%
Participant 28327: 100.73%
Participant 28404: 101.45%
Participant 30739: 99.96%
Participant 33280: 99.13%
Participant 34714: 98.21%
Participant 34763: 94.68%
Participant 37092: 93.69%
Participant 37818: 100.71%
Participant 38029: 98.72%
Participant 38645: 102.55%
Participant 44066: 96.30%
Participant 46773: 102.41%
Participant 50129: 97.71%
Participant 54783: 100.83%
Participant 55110: 98.03%
Participant 56143: 97.38%
Participant 57458: 99.39%
Participant 58996: 98.29%
Participant 61972: 98.71%
Participant 65919: 101.63%
Participant 66303: 103.39%
Participant 68416: 94.93%
Participant 72950: 96.04%
Participant 74998: 101.06%
Participant 75967: 97.04%
Participant 78692: 97.65%
Participant 81981: 102.83%
Participant 82556: 98.20%
Participant 84645: 95.29%
Participant 88137: 99.49%
Participant 91169: 102.68%
Participant 91850: 102.11%
Participant 92674: 93.96%
Participant 92957: 95.89%
Participant 93676: 97.07%
Participant 99857: 96.68%

Mean Absolute Percentage Error (MAPE): 2.29%

# MAKING A CALIBRATED TIDAL VOLUME COLUMN USING THE POSTURE-SPECIFIC CALIBRATION COEFFICIENTS PER PARTICIPANT AND THE PRESENT MINUTE'S POSTURE

In [4]:
import pandas as pd

# file path
file_path = r"C:\Users\msa583\OneDrive - Vrije Universiteit Amsterdam\Desktop\RSA Analyses Post-Processing\RQ2\all_participants_merged.xlsx"

# reading in the excel with the merged participant data
df = pd.read_excel(file_path)

print(len(df))

84356

In [5]:
df.head()

,Location,Physical_Exertion,Posture,Social_Situation,Type_Of_Activity,Location_Code,Physical_Exertion_Code,Posture_Code,Social_Situation_Code,Type_Of_Activity_Code,...,Max_IBI_msec,RSA_msec,Artefact_Free_ECG_percent,Artefact_Free_Respiration_percent,Majority_postures,participant_id,day,Experimental_Conditions,Experimental_Conditions_Code,Artefact_Free_ECG_s
0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,...,677.0,19.000000,100.0,100.000000,Standing,12008,1,NaN,NaN,NaN
1,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,...,655.0,8.888889,100.0,100.000000,Standing,12008,1,NaN,NaN,NaN
2,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,...,692.0,15.000000,100.0,92.487479,Standing,12008,1,NaN,NaN,NaN
3,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,...,692.0,10.666667,100.0,97.063622,Standing,12008,1,NaN,NaN,NaN
4,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,...,655.0,15.750000,100.0,92.346090,Standing,12008,1,NaN,NaN,NaN

In [6]:
#calibrating the tidal volumes specific for each posture
import os
import pandas as pd
import numpy as np

# loading all calibration files
calibration_dir = r"C:\Users\msa583\OneDrive - Vrije Universiteit Amsterdam\Desktop\RSA Analyses Post-Processing\RQ2"
calibration_files = [f for f in os.listdir(calibration_dir) if f.startswith("lab_calibration_") and f.endswith(".xlsx")]

# defining an empty dictionary to store the calibration coefficients for each participant
calibration_dict = {}

for file in calibration_files:
    participant_id = os.path.splitext(file)[0].split("_")[-1]
    calib_path = os.path.join(calibration_dir, file)
    calib_df = pd.read_excel(calib_path)
    calibration_dict[participant_id] = calib_df.iloc[0].to_dict()

# function to calculate calibrated tidal volume
def calibrate_tidal_volume(row):
    pid = str(row["participant_id"])
    posture = row["Majority_postures"]
    uncalibrated = row["Tidal_Volume_mOhm"]

    # if there is -9999 in the uncalibrated tidal volume column, put by vu-dams, do not calculate a tidal volume for it
    if uncalibrated == -9999 or pid not in calibration_dict:
        return np.nan

    calib = calibration_dict[pid]

    if posture.lower() == "sitting":
        return uncalibrated * calib["slope_sitting"] + calib["intercept_sitting"]
    elif posture.lower() == "standing":
        return uncalibrated * calib["slope_standing"] + calib["intercept_standing"]
    elif posture.lower() == "lying":
        return uncalibrated * calib["slope_supine"] + calib["intercept_supine"]
    else:
        return np.nan 

# applying the calibration function to the dataframe df
df["Calibrated_Tidal_Volume"] = df.apply(calibrate_tidal_volume, axis=1)

# saving the dataframe
#df.to_excel(os.path.join(calibration_dir, "all_participants_calibrated.xlsx"), index=False)

In [7]:
#datetime indexing the dataframe df, making sure to note the original format is DD-MM-YYYY, with HH:MM:SS:.FFFF
df["datetime"] = pd.to_datetime(
    df["Start_Date"].astype(str) + " " + df["Start_Time"].astype(str),
    format="%d-%m-%Y %H:%M:%S.%f"
)

df.head()

,Location,Physical_Exertion,Posture,Social_Situation,Type_Of_Activity,Location_Code,Physical_Exertion_Code,Posture_Code,Social_Situation_Code,Type_Of_Activity_Code,...,Artefact_Free_ECG_percent,Artefact_Free_Respiration_percent,Majority_postures,participant_id,day,Experimental_Conditions,Experimental_Conditions_Code,Artefact_Free_ECG_s,Calibrated_Tidal_Volume,datetime
0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,...,100.0,100.000000,Standing,12008,1,NaN,NaN,NaN,2.910774,2024-09-02 09:29:53.500
1,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,...,100.0,100.000000,Standing,12008,1,NaN,NaN,NaN,3.063689,2024-09-02 09:30:53.500
2,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,...,100.0,92.487479,Standing,12008,1,NaN,NaN,NaN,2.862958,2024-09-02 09:31:53.500
3,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,...,100.0,97.063622,Standing,12008,1,NaN,NaN,NaN,3.074853,2024-09-02 09:32:53.500
4,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,...,100.0,92.346090,Standing,12008,1,NaN,NaN,NaN,2.223003,2024-09-02 09:33:53.500

In [ ]:
#df.to_excel(os.path.join(calibration_dir, "all_participants_calibrated.xlsx"), index=False)
#saved just to manually double check for some participants that the calibration values are as expected
#verified that this calculation works for all postures, for different participants

# CALCULATING THE MEAN OF MAPE FOR CALIBRATION

In [ ]:
#DO NOT RUN THIS AGAIN (JUST RUNNING ONCE WAS ENOUGH FOR THE STATS)
#finding the mean for the mean absolute percentage error for the calibrations across participants
import os
import pandas as pd

# Set directory path
calibration_dir = r"C:\Users\msa583\OneDrive - Vrije Universiteit Amsterdam\Desktop\RSA Analyses Post-Processing\RQ2"

# List of calibration files
calibration_files = [
    f for f in os.listdir(calibration_dir)
    if f.startswith("lab_calibration_") and f.endswith(".xlsx")
]

# Columns to summarize
columns_to_extract = [
    "mape_supine",
    "mape_sitting",
    "mape_standing",
    "spirometer_estimation_3l"
]

# Collect all calibration rows
calib_rows = []

for file in calibration_files:
    file_path = os.path.join(calibration_dir, file)
    try:
        df = pd.read_excel(file_path)
        calib_rows.append(df[columns_to_extract])
    except Exception as e:
        print(f"Could not read {file}: {e}")

# Concatenate all rows into one DataFrame
all_calib_data = pd.concat(calib_rows, ignore_index=True)

# Calculate summary statistics including count
summary_stats = all_calib_data.agg(["count", "mean", "std", "min", "max"])

# Display results
print(summary_stats)

# REMOVING EPISODES OF LAB RECORDING AND SLEEP SO WE ARE LEFT WITH AWAKE AMBULATORY DATA

In [8]:
# excluding periods of lab time and sleep time
#double-checked all dates and times
exclude_periods = {
    "25879": { #done
        "sleep": [
            ("12-04-2024 22:45:00.000", "13-04-2024 07:40:00.000")
        ],
        "lab_end": "12-04-2024 12:15:00.000"
    },
    "91169": { #done
        "sleep": [
            ("01-05-2024 01:20:00.000", "01-05-2024 09:15:00.000") #the day1 start time in VU-DAMS is an hour later than it is (need to correct for EMA)
        ],
        "lab_end": "30-04-2024 12:55:00.000" #as the VU-AMS recording for day1 for the participant started an hour later than it is, adjusted this
    }, 
    "72950": { #done
        "sleep": [
            ("02-05-2024 01:58:00.000", "02-05-2024 08:43:00.000") 
        ],
        "lab_end": "01-05-2024 12:00:00.000" 
    },
    "65919": {   #done
        "sleep": [
            ("15-05-2024 00:43:00.000", "15-05-2024 08:27:00.000") 
        ],
        "lab_end": "14-05-2024 11:55:00.000" 
    },   
    "33280": {   #done
        "sleep": [
            ("16-05-2024 00:42:00.000", "16-05-2024 08:51:00.000") 
        ],
        "lab_end": "15-05-2024 12:10:00.000" 
    }, 
    "75967": {   #done
        "sleep": [
            ("17-05-2024 00:14:00.000", "17-05-2024 07:49:00.000") 
        ],
        "lab_end": "16-05-2024 11:55:00.000" 
    },
    "38645": {   #done
        "sleep": [
            ("24-05-2024 04:50:00.000", "24-05-2024 12:47:00.000") 
        ],
        "lab_end": "23-05-2024 12:16:00.000" 
    },
    "92674": {   #done
        "sleep": [
            ("30-05-2024 00:55:55.000", "30-05-2024 08:54:00.000") 
        ],
        "lab_end": "29-05-2024 12:04:00.000" 
    },
    "37092": {   #done
        "sleep": [
            ("31-05-2024 00:04:00.000", "01-06-2024 07:52:00.000")  #the day2 should actually be 31-5-2024 and not the first of june, correct it for EMA
        ],  #the dates here are correct, the VU-DAMS jumped from 31st of May around 2:40 am to 1st of June 2:40 am
        "lab_end": "30-05-2024 12:22:00.000" 
    },    
    "57458": {   #done
        "sleep": [
            ("11-06-2024 22:35:00.000", "12-06-2024 08:22:00.000")  
        ],
        "lab_end": "11-06-2024 11:54:00.000" 
    },  
    "91850": {   #done
        "sleep": [
            ("14-06-2024 01:07:00.000", "14-06-2024 09:54:00.000")  
        ],
        "lab_end": "13-06-2024 11:47:00.000" 
    },
    "81981": {   #done
        "sleep": [
            ("20-06-2024 01:14:00.000", "20-06-2024 08:52:00.000")  
        ],
        "lab_end": "19-06-2024 12:03:00.000" 
    },    
    "61972": {   #done
        "sleep": [
            ("25-06-2024 01:47:00.000", "25-06-2024 08:33:00.000")  
        ],
        "lab_end": "24-06-2024 11:56:00.000" 
    },    
    "15337": {   #this participant does not have the sleep time data, so that part is not applicable - done
        
        "lab_end": "25-06-2024 12:13:00.000" 
    },
    "50129": {    #done
        "sleep": [
            ("26-06-2024 23:57:00.000", "27-06-2024 06:48:00.000")  
        ],
        "lab_end": "26-06-2024 12:31:00.000" 
    },
    "92957": {    #done
        "sleep": [
            ("04-07-2024 00:38:00.000", "04-07-2024 08:28:00.000")  
        ],
        "lab_end": "03-07-2024 12:17:00.000" 
    },   
    "28327": {    #done
        "sleep": [
            ("05-07-2024 02:01:00.000", "05-07-2024 09:29:00.000")  
        ],
        "lab_end": "04-07-2024 12:15:00.000" 
    },
    "46773": {    #done
        "sleep": [
            ("09-07-2024 22:55:00.000", "10-07-2024 06:28:00.000")  
        ],
        "lab_end": "09-07-2024 11:00:00.000" #the day1 recording start time is written as an hour earlier than it actually is, so also adjusted this
    },
    "30739": {  #done  
        "sleep": [
            ("11-07-2024 23:36:00.000", "12-07-2024 08:15:00.000")  
        ],
        "lab_end": "11-07-2024 10:57:00.000" #the day1 recording start time is written as an hour earlier than it actually is, so also adjusted this
    },    
    "93676": {    #done
        "sleep": [
            ("06-08-2024 21:15:00.000", "07-08-2024 13:17:00.000")  
        ],
        "lab_end": "06-08-2024 11:29:00.000" #the day1 recording start time is written as an hour earlier than it actually is, so also adjusted this
    },
    "13304": {   #this participant does not have the sleep time data, so that part is not applicable - done
        
        "lab_end": "09-08-2024 11:59:00.000" 
    },    
    "37818": {    #done
        "sleep": [
            ("20-08-2024 21:22:00.000", "21-08-2024 05:18:00.000")  
        ],
        "lab_end": "20-08-2024 10:50:00.000"  #the day1 recording start time is written as an hour earlier than it actually is, so also adjusted this
    },    
    "12008": {    #done
        "sleep": [
            ("02-09-2024 22:02:00.000", "03-09-2024 07:41:00.000")  
        ],
        "lab_end": "02-09-2024 11:09:00.000"   #the day1 recording start time is written as an hour earlier than it actually is, so also adjusted this
    },
    "25201": {    #done
        "sleep": [
            ("10-09-2024 23:14:00.000", "11-09-2024 08:23:00.000")  
        ],
        "lab_end": "10-09-2024 11:17:00.000"  #the day1 recording start time is written as an hour earlier than it actually is, so also adjusted this
    },   
    "38029": {    #done
        "sleep": [
            ("11-09-2024 23:32:00.000", "12-09-2024 07:34:00.000")  
        ],
        "lab_end": "11-09-2024 12:05:00.000" 
    },
    "24340": {    #done
        "sleep": [
            ("18-09-2024 01:23:00.000", "18-09-2024 07:48:00.000")  
        ],
        "lab_end": "17-09-2024 12:28:00.000" 
    },
    "58996": {    #done
        "sleep": [
            ("20-09-2024 01:13:00.000", "20-09-2024 08:14:00.000")  
        ],
        "lab_end": "19-09-2024 12:11:00.000" 
    },
    "88137": {    #done
        "sleep": [
            ("21-09-2024 00:00:49.000", "21-09-2024 09:58:00.000")  
        ],
        "lab_end": "20-09-2024 10:50:00.000"  #the day1 recording start time is written as an hour earlier than it actually is, so also adjusted this
    },
    "56143": {   #done
        "sleep": [
            ("27-09-2024 01:04:00.000", "27-09-2024 07:45:00.000")  
        ],
        "lab_end": "26-09-2024 11:50:00.000" 
    },
    "28404": {  #done
        "sleep": [
            ("03-10-2024 23:59:00.000", "04-10-2024 07:26:00.000")  
        ],
        "lab_end": "03-10-2024 12:30:00.000" 
    },    
    "68416": {  #done
        "sleep": [
            ("01-11-2024 02:13:00.000", "01-11-2024 10:38:00.000")  
        ],
        "lab_end": "31-10-2024 11:56:00.000" 
    }, 
    "44066": {   #done
        "sleep": [
            ("02-11-2024 00:10:20.000", "02-11-2024 09:02:00.000")  
        ],
        "lab_end": "01-11-2024 12:10:00.000" 
    },   
    "34714": {   #done
        "sleep": [
            ("08-11-2024 01:16:00.000", "08-11-2024 09:30:00.000")  
        ],
        "lab_end": "07-11-2024 12:23:00.000" 
    },   
    "54783": {   #done
        "sleep": [
            ("13-11-2024 23:05:00.000", "14-11-2024 00:42:00.000")  #as the end of sleep put in some time after the end (00:41:54.658) of this file
        ],
        "lab_end": "13-11-2024 12:10:00.000" 
    },     
    "74998": {   #done
        "sleep": [
            ("15-11-2024 03:27:00.000", "15-11-2024 08:24:00.000")  
        ],
        "lab_end": "14-11-2024 12:17:00.000" 
    },
     "82556": {   #done
        "sleep": [
            ("15-11-2024 22:52:00.000", "16-11-2024 07:28:53.000")  
        ],
        "lab_end": "15-11-2024 12:24:00.000" 
    },   
     "78692": {   #done
        "sleep": [
            ("06-12-2024 00:16:00.000", "06-12-2024 10:32:00.000")  
        ],
        "lab_end": "05-12-2024 12:07:00.000" 
    },  
     "55110": {   #done
        "sleep": [
            ("16-01-2025 23:11:00.000", "17-01-2025 06:29:00.000")  
        ],
        "lab_end": "16-01-2025 12:14:00.000" 
    }, 
     "84645": {  #done
        "sleep": [
            ("25-01-2025 00:09:00.000", "25-01-2025 09:31:00.000")  
        ],
        "lab_end": "24-01-2025 11:50:00.000" 
    },
     "34763": {  #done
        "sleep": [
            ("29-01-2025 03:27:00.000", "29-01-2025 09:10:00.000")  
        ],
        "lab_end": "28-01-2025 12:16:00.000" 
    },
     "66303": {  #done
        "sleep": [
            ("04-02-2025 01:04:00.000", "04-02-2025 08:16:00.000")  
        ],
        "lab_end": "03-02-2025 12:14:00.000" 
    },
     "99857": {  #done
        "sleep": [
            ("12-02-2025 00:24:00.000", "12-02-2025 08:42:00.000")  
        ],
        "lab_end": "11-02-2025 11:50:00.000" 
    }
}

In [9]:
filtered_dfs = []  # list to collect the awake ambulatory data for all participants

# obtain the list of unique participant ids
all_participants = df["participant_id"].astype(str).unique()

for pid in all_participants:
    # selecting and copying the given participant's data
    participant_data = df[df["participant_id"].astype(str) == pid].copy()

    # if the participant is in the exclude list, apply the filters
    if pid in exclude_periods:
        periods = exclude_periods[pid]

        # if lab_end is provided, remove the lab data
        if "lab_end" in periods:
            lab_end = pd.to_datetime(periods["lab_end"], format="%d-%m-%Y %H:%M:%S.%f")
            participant_data = participant_data[participant_data["datetime"] > lab_end]  #keeps data with datetime later than end of lab procedure

        # if sleep period is provided, remove the sleep data
        if "sleep" in periods:
            for start_str, end_str in periods["sleep"]:
                sleep_start = pd.to_datetime(start_str, format="%d-%m-%Y %H:%M:%S.%f")
                sleep_end = pd.to_datetime(end_str, format="%d-%m-%Y %H:%M:%S.%f")
                participant_data = participant_data[
                    ~((participant_data["datetime"] >= sleep_start) & (participant_data["datetime"] <= sleep_end))   #removing interval of sleep
                ]

    # add the filtered data to the full list
    filtered_dfs.append(participant_data)

# combine the contents of the filtered_dfs list into one general dataframe
df_awake_ambulatory = pd.concat(filtered_dfs, ignore_index=True)

In [10]:
df_awake_ambulatory  #this is the dataset that does not have the lab recording and the sleep episodes anymore

,Location,Physical_Exertion,Posture,Social_Situation,Type_Of_Activity,Location_Code,Physical_Exertion_Code,Posture_Code,Social_Situation_Code,Type_Of_Activity_Code,...,Artefact_Free_ECG_percent,Artefact_Free_Respiration_percent,Majority_postures,participant_id,day,Experimental_Conditions,Experimental_Conditions_Code,Artefact_Free_ECG_s,Calibrated_Tidal_Volume,datetime
0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,...,100.0,100.000000,Standing,12008,1,NaN,NaN,NaN,2.933965,2024-09-02 11:09:53.500
1,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,...,100.0,100.000000,Standing,12008,1,NaN,NaN,NaN,3.128341,2024-09-02 11:10:53.500
2,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,...,100.0,93.531469,Standing,12008,1,NaN,NaN,NaN,3.182655,2024-09-02 11:11:53.500
3,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,...,100.0,92.500000,Standing,12008,1,NaN,NaN,NaN,3.171272,2024-09-02 11:12:53.500
4,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,...,100.0,100.000000,Sitting,12008,1,NaN,NaN,NaN,1.706549,2024-09-02 11:13:53.500
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
61485,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,100.0,100.000000,Sitting,99857,2,-9999.0,-9999.0,NaN,1.830138,2025-02-12 21:55:39.500
61486,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,100.0,100.000000,Sitting,99857,2,-9999.0,-9999.0,NaN,1.581758,2025-02-12 21:56:39.500
61487,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,100.0,100.000000,Sitting,99857,2,-9999.0,-9999.0,NaN,1.416549,2025-02-12 21:57:39.500
61488,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,100.0,81.878089,Sitting,99857,2,-9999.0,-9999.0,NaN,2.225654,2025-02-12 21:58:39.500
61489,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,100.0,100.000000,Sitting,99857,2,-9999.0,-9999.0,NaN,2.829555,2025-02-12 21:59:39.500

In [11]:
import numpy as np

# filtering out rows where Total_Motility_mg >= 160 - there is at least a physical intensity akin to that of walking
initial_row_count = len(df_awake_ambulatory)

df_awake_ambulatory = df_awake_ambulatory[df_awake_ambulatory['Total_Motility_mg'] < 160] #creating the no physical activity version of the df

removed_rows = initial_row_count - len(df_awake_ambulatory)
percentage_removed = (removed_rows / initial_row_count) * 100
print(f"Percentage of rows removed (Total_Motility_mg >= 160): {percentage_removed:.2f}%")
df_awake_ambulatory #this is the dataframe with no ambulatory, no lab, no medium-intense physical activity data

Percentage of rows removed (Total_Motility_mg >= 160): 9.37%

,Location,Physical_Exertion,Posture,Social_Situation,Type_Of_Activity,Location_Code,Physical_Exertion_Code,Posture_Code,Social_Situation_Code,Type_Of_Activity_Code,...,Artefact_Free_ECG_percent,Artefact_Free_Respiration_percent,Majority_postures,participant_id,day,Experimental_Conditions,Experimental_Conditions_Code,Artefact_Free_ECG_s,Calibrated_Tidal_Volume,datetime
0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,...,100.0,100.000000,Standing,12008,1,NaN,NaN,NaN,2.933965,2024-09-02 11:09:53.500
4,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,...,100.0,100.000000,Sitting,12008,1,NaN,NaN,NaN,1.706549,2024-09-02 11:13:53.500
5,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,...,100.0,94.863563,Standing,12008,1,NaN,NaN,NaN,2.811731,2024-09-02 11:14:53.500
12,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,...,100.0,100.000000,Standing,12008,1,NaN,NaN,NaN,2.683670,2024-09-02 11:21:53.500
13,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,...,100.0,96.875000,Standing,12008,1,NaN,NaN,NaN,2.478718,2024-09-02 11:22:53.500
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
61485,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,100.0,100.000000,Sitting,99857,2,-9999.0,-9999.0,NaN,1.830138,2025-02-12 21:55:39.500
61486,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,100.0,100.000000,Sitting,99857,2,-9999.0,-9999.0,NaN,1.581758,2025-02-12 21:56:39.500
61487,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,100.0,100.000000,Sitting,99857,2,-9999.0,-9999.0,NaN,1.416549,2025-02-12 21:57:39.500
61488,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,100.0,81.878089,Sitting,99857,2,-9999.0,-9999.0,NaN,2.225654,2025-02-12 21:58:39.500
61489,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,100.0,100.000000,Sitting,99857,2,-9999.0,-9999.0,NaN,2.829555,2025-02-12 21:59:39.500

In [ ]:
#df_awake_ambulatory.to_excel('df_awake_ambulatory_checkexclusions.xlsx')
#saved only to make sure the sleep and lab period and physically active periods are eliminated (manually checked some rows in the excel) - correct

In [ ]:
#let's calculate for this duration of recording the percentage of artifacts for the ECG and respiration

In [12]:
# check if there are any 0s at all in Artefact_Free_ECG_percent
zero_values = df_awake_ambulatory[
   
    (df_awake_ambulatory['Artefact_Free_ECG_percent'] == 0)
]

print(zero_values)

Empty DataFrame
Columns: [Location, Physical_Exertion, Posture, Social_Situation, Type_Of_Activity, Location_Code, Physical_Exertion_Code, Posture_Code, Social_Situation_Code, Type_Of_Activity_Code, Subject_ID, Label_ID, Start_Date, Start_Time, End_Date, End_Time, Label_Duration_s, Total_Motility_mg, Average_IBI_msec, Average_HR_bpm, SDNN_msec, Respiration_Rate_bpm, Tidal_Volume_mOhm, RMSSD_msec, LF_ms, RSA0_msec, HF_ms, PEP_msec, LVET_msec, TWave_amplitude_mV, Stroke_Volume_(Nederend_2017)_cc, Minute_Volume_(Nederend_2017)_lmin, Average_SCL_uS, nsSCRs_per_minute_ppm, Min_IBI_msec, Max_IBI_msec, RSA_msec, Artefact_Free_ECG_percent, Artefact_Free_Respiration_percent, Majority_postures, participant_id, day, Experimental_Conditions, Experimental_Conditions_Code, Artefact_Free_ECG_s, Calibrated_Tidal_Volume, datetime]
Index: []

[0 rows x 47 columns]

In [13]:
#In the artifact free ECG column, there are not any 0s. When there is no data for ECG, it is specified with a value of -9999. We will thus replace the
#-9999 values in this column with 0 (meaning there is a lack of artifact free ECG)
df_awake_ambulatory['Artefact_Free_ECG_percent'] = df_awake_ambulatory['Artefact_Free_ECG_percent'].replace(-9999, 0)

# mean of Artefact_Free_ECG_percent
mean_ecg = df_awake_ambulatory['Artefact_Free_ECG_percent'].mean()

print("Mean Artefact Free ECG Percent:", mean_ecg)

Mean Artefact Free ECG Percent: 87.4919473432547

C:\Users\msa583\AppData\Local\Temp\ipykernel_31700\2289913148.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_awake_ambulatory['Artefact_Free_ECG_percent'] = df_awake_ambulatory['Artefact_Free_ECG_percent'].replace(-9999, 0)

In [14]:
#do the same for respiration
df_awake_ambulatory['Artefact_Free_Respiration_percent'] = df_awake_ambulatory['Artefact_Free_Respiration_percent'].replace(-9999, 0)

# mean of Artefact_Free_ECG_percent
mean_resp = df_awake_ambulatory['Artefact_Free_Respiration_percent'].mean()

print("Mean Artefact Free Respiration Percent:", mean_resp)

Mean Artefact Free Respiration Percent: 85.78365557741692

C:\Users\msa583\AppData\Local\Temp\ipykernel_31700\1931996242.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_awake_ambulatory['Artefact_Free_Respiration_percent'] = df_awake_ambulatory['Artefact_Free_Respiration_percent'].replace(-9999, 0)

In [15]:
# calculate the mean, min, and max for the columns of RSA0, RR, IBI, and Calibrated_Tidal_Volume
rsa0_mean = df_awake_ambulatory['RSA0_msec'].mean()
rsa0_min = df_awake_ambulatory['RSA0_msec'].min()
rsa0_max = df_awake_ambulatory['RSA0_msec'].max()

respiration_rate_mean = df_awake_ambulatory['Respiration_Rate_bpm'].mean()
respiration_rate_min = df_awake_ambulatory['Respiration_Rate_bpm'].min()
respiration_rate_max = df_awake_ambulatory['Respiration_Rate_bpm'].max()

ibi_mean = df_awake_ambulatory['Average_IBI_msec'].mean()
ibi_min = df_awake_ambulatory['Average_IBI_msec'].min()
ibi_max = df_awake_ambulatory['Average_IBI_msec'].max()

vt_mean = df_awake_ambulatory['Calibrated_Tidal_Volume'].mean()
vt_min = df_awake_ambulatory['Calibrated_Tidal_Volume'].min()
vt_max = df_awake_ambulatory['Calibrated_Tidal_Volume'].max()

# display the results
print("RSA0_msec - Mean:", rsa0_mean, "Min:", rsa0_min, "Max:", rsa0_max)
print("Respiration_Rate_bpm - Mean:", respiration_rate_mean, "Min:", respiration_rate_min, "Max:", respiration_rate_max)
print("Average_IBI_msec - Mean:", ibi_mean, "Min:", ibi_min, "Max:", ibi_max)
print("Calibrated_Tidal_Volume - Mean:", vt_mean, "Min:", vt_min, "Max:", vt_max)

RSA0_msec - Mean: -1140.4659980705615 Min: -9999.0 Max: 415.8571428571428
Respiration_Rate_bpm - Mean: -1170.7933238997928 Min: -9999.0 Max: 33.02552952430968
Average_IBI_msec - Mean: -465.176894823439 Min: -9999.0 Max: 1334.875
Calibrated_Tidal_Volume - Mean: 0.7337880595216868 Min: -22.774494504921062 Max: 84.60541128778387

In [16]:
# we only select rows in which there is more than 45% artifact-free data for both Artefact_Free_ECG_percent and Artefact_Free_Respiration_percent
#otherwise we would still have -9999 (NA) values for RSA0, IBI, and RR (parameters of interest)
df_awake_ambulatory = df_awake_ambulatory[
    (df_awake_ambulatory['Artefact_Free_ECG_percent'] >= 45) &
    (df_awake_ambulatory['Artefact_Free_Respiration_percent'] >= 45)
]
df_awake_ambulatory

,Location,Physical_Exertion,Posture,Social_Situation,Type_Of_Activity,Location_Code,Physical_Exertion_Code,Posture_Code,Social_Situation_Code,Type_Of_Activity_Code,...,Artefact_Free_ECG_percent,Artefact_Free_Respiration_percent,Majority_postures,participant_id,day,Experimental_Conditions,Experimental_Conditions_Code,Artefact_Free_ECG_s,Calibrated_Tidal_Volume,datetime
0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,...,100.0,100.000000,Standing,12008,1,NaN,NaN,NaN,2.933965,2024-09-02 11:09:53.500
4,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,...,100.0,100.000000,Sitting,12008,1,NaN,NaN,NaN,1.706549,2024-09-02 11:13:53.500
5,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,...,100.0,94.863563,Standing,12008,1,NaN,NaN,NaN,2.811731,2024-09-02 11:14:53.500
12,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,...,100.0,100.000000,Standing,12008,1,NaN,NaN,NaN,2.683670,2024-09-02 11:21:53.500
13,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,...,100.0,96.875000,Standing,12008,1,NaN,NaN,NaN,2.478718,2024-09-02 11:22:53.500
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
61485,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,100.0,100.000000,Sitting,99857,2,-9999.0,-9999.0,NaN,1.830138,2025-02-12 21:55:39.500
61486,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,100.0,100.000000,Sitting,99857,2,-9999.0,-9999.0,NaN,1.581758,2025-02-12 21:56:39.500
61487,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,100.0,100.000000,Sitting,99857,2,-9999.0,-9999.0,NaN,1.416549,2025-02-12 21:57:39.500
61488,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,100.0,81.878089,Sitting,99857,2,-9999.0,-9999.0,NaN,2.225654,2025-02-12 21:58:39.500
61489,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,100.0,100.000000,Sitting,99857,2,-9999.0,-9999.0,NaN,2.829555,2025-02-12 21:59:39.500

In [17]:
# calculate the mean, min, and max for the columns of RSA0, RR, IBI to make sure that following our selection of columns, the -9999s are not there
rsa0_mean = df_awake_ambulatory['RSA0_msec'].mean()
rsa0_min = df_awake_ambulatory['RSA0_msec'].min()
rsa0_max = df_awake_ambulatory['RSA0_msec'].max()

respiration_rate_mean = df_awake_ambulatory['Respiration_Rate_bpm'].mean()
respiration_rate_min = df_awake_ambulatory['Respiration_Rate_bpm'].min()
respiration_rate_max = df_awake_ambulatory['Respiration_Rate_bpm'].max()

ibi_mean = df_awake_ambulatory['Average_IBI_msec'].mean()
ibi_min = df_awake_ambulatory['Average_IBI_msec'].min()
ibi_max = df_awake_ambulatory['Average_IBI_msec'].max()

# display the results
print("RSA0_msec - Mean:", rsa0_mean, "Min:", rsa0_min, "Max:", rsa0_max)
print("Respiration_Rate_bpm - Mean:", respiration_rate_mean, "Min:", respiration_rate_min, "Max:", respiration_rate_max)
print("Average_IBI_msec - Mean:", ibi_mean, "Min:", ibi_min, "Max:", ibi_max)

RSA0_msec - Mean: 57.21108640251692 Min: 0.0 Max: 415.8571428571428
Respiration_Rate_bpm - Mean: 17.520442732572874 Min: 7.279411764705882 Max: 33.02552952430968
Average_IBI_msec - Mean: 735.5681619471582 Min: 340.2732558139535 Max: 1334.875

In [18]:
# calculate the mean, min, and max for the columns of RSA0, RR, IBI, and Calibrated_Tidal_Volume
rsa0_mean = df_awake_ambulatory['RSA0_msec'].mean()
rsa0_min = df_awake_ambulatory['RSA0_msec'].min()
rsa0_max = df_awake_ambulatory['RSA0_msec'].max()

respiration_rate_mean = df_awake_ambulatory['Respiration_Rate_bpm'].mean()
respiration_rate_min = df_awake_ambulatory['Respiration_Rate_bpm'].min()
respiration_rate_max = df_awake_ambulatory['Respiration_Rate_bpm'].max()

ibi_mean = df_awake_ambulatory['Average_IBI_msec'].mean()
ibi_min = df_awake_ambulatory['Average_IBI_msec'].min()
ibi_max = df_awake_ambulatory['Average_IBI_msec'].max()

vt_mean = df_awake_ambulatory['Calibrated_Tidal_Volume'].mean()
vt_min = df_awake_ambulatory['Calibrated_Tidal_Volume'].min()
vt_max = df_awake_ambulatory['Calibrated_Tidal_Volume'].max()

# display the results
print("RSA0_msec - Mean:", rsa0_mean, "Min:", rsa0_min, "Max:", rsa0_max)
print("Respiration_Rate_bpm - Mean:", respiration_rate_mean, "Min:", respiration_rate_min, "Max:", respiration_rate_max)
print("Average_IBI_msec - Mean:", ibi_mean, "Min:", ibi_min, "Max:", ibi_max)
print("Calibrated_Tidal_Volume - Mean:", vt_mean, "Min:", vt_min, "Max:", vt_max)

RSA0_msec - Mean: 57.21108640251692 Min: 0.0 Max: 415.8571428571428
Respiration_Rate_bpm - Mean: 17.520442732572874 Min: 7.279411764705882 Max: 33.02552952430968
Average_IBI_msec - Mean: 735.5681619471582 Min: 340.2732558139535 Max: 1334.875
Calibrated_Tidal_Volume - Mean: 0.716032707767372 Min: -22.774494504921062 Max: 71.08422386075979

In [19]:
# calculate mean, min, and max for Calibrated_Tidal_Volume, after the removal of outliers for each participant specifically
participant_stats = df_awake_ambulatory.groupby('participant_id')['Calibrated_Tidal_Volume'].agg(['mean', 'min', 'max'])
print(participant_stats)

                    mean        min        max
participant_id
12008           1.700330 -12.218596   3.295508
13304           0.617628   0.096279   9.002533
15337           0.681023   0.371967   3.637552
24340           0.423655  -1.092138  14.241041
25201           0.481401   0.118884   1.426210
25879           0.520385   0.207447   3.794518
28327           0.745354  -0.416675   5.765957
28404           0.631897  -0.002496  10.017951
30739           0.565304   0.048086   5.143306
33280           0.365867  -0.025222   3.298081
34714           0.780869   0.466584   3.625991
34763           0.676459   0.230354  16.754334
37092           0.878177   0.499509  13.488824
37818           0.842010   0.485022   4.998923
38029           0.571333   0.336559   1.290300
38645           0.539844   0.378149   2.616565
44066           0.413442   0.109487  13.181655
46773           0.348449  -3.044703   0.612588
50129           0.409418   0.299495   0.781693
54783           0.876150   0.780386   1.444408
55110           0.752380   0.289539  28.064343
56143           0.511421   0.220531   1.506754
57458           0.782165   0.444997   7.189487
58996           1.525538 -22.774495  14.452461
61972           1.656570  -1.380144  21.916218
65919           0.934783   0.259042  10.949528
66303           0.575526   0.102820   1.268506
68416           0.605586   0.152963   7.725224
72950           0.549371   0.274401   7.961210
74998           0.489466   0.300820   2.882856
75967           0.585081   0.408917   1.786452
78692           0.444831   0.123221   2.203261
81981           0.448309   0.157257   0.915757
82556           1.454087   0.927118  71.084224
84645           0.235543   0.006225   1.412632
88137           0.655895   0.095174   6.803678
91169           0.645887   0.066467   5.085937
91850           0.652486   0.207984   1.648909
92674           0.440305   0.187835   8.554718
92957           0.363041   0.144056   0.851881
93676           1.152577   0.220474  22.132275
99857           1.608327   0.692212   6.117562

In [20]:
#filtering out of epochs with implausible and deviant tidal volume values

# filtering out rows with implausible calibrated volume values - specifically, a Calibrated_Tidal_Volume of less than 0.1 or greater than 6.5 L
initial_row_count = len(df_awake_ambulatory)

df_awake_ambulatory = df_awake_ambulatory[
    (df_awake_ambulatory['Calibrated_Tidal_Volume'] >= 0.1) & 
    (df_awake_ambulatory['Calibrated_Tidal_Volume'] <= 6.5)
]

removed_rows = initial_row_count - len(df_awake_ambulatory)

percentage_removed = (removed_rows / initial_row_count) * 100

print(f"Percentage of rows removed (Calibrated_Tidal_Volume < 0 or > 6.5): {percentage_removed:.2f}%")

# grouping per participant_id and per Majority_postures, then calculate mean and sd for Calibrated_Tidal_Volume
stats = df_awake_ambulatory.groupby(['participant_id', 'Majority_postures'])['Calibrated_Tidal_Volume'].agg(['mean', 'std'])

# function to remove outliers for each row based on its participant_id AND posture
def remove_outliers(row, stats):
    # calculate the mean and sd for the given participant_id and Majority_postures
    mean = stats.loc[(row['participant_id'], row['Majority_postures']), 'mean']
    std = stats.loc[(row['participant_id'], row['Majority_postures']), 'std']
    
    # calculate distance from mean per each tidal volume value
    distance_from_mean = abs(row['Calibrated_Tidal_Volume'] - mean) / std
    # if the distance is more than 3 standard deviations, enter NaN
    if distance_from_mean >= 3:
        return np.nan  
    return row['Calibrated_Tidal_Volume']

# run the remove_outliers function row by row
initial_row_count = len(df_awake_ambulatory)

df_awake_ambulatory['Cleaned_Tidal_Volume'] = df_awake_ambulatory.apply(lambda row: remove_outliers(row, stats), axis=1)

# actually drop rows where Cleaned_Tidal_Volume is NaN 
removed_rows = df_awake_ambulatory['Cleaned_Tidal_Volume'].isna().sum()
percentage_removed = (removed_rows / initial_row_count) * 100
df_awake_ambulatory = df_awake_ambulatory.dropna(subset=['Cleaned_Tidal_Volume'])

print(f"Percentage of rows removed (outliers more than 3 SDs away): {percentage_removed:.2f}%")

print(f"Remaining rows: {len(df_awake_ambulatory)}")
print(df_awake_ambulatory)

Percentage of rows removed (Calibrated_Tidal_Volume < 0 or > 6.5): 1.26%
Percentage of rows removed (outliers more than 3 SDs away): 1.34%
Remaining rows: 47338
       Location  Physical_Exertion  Posture  Social_Situation  \
0       -9999.0            -9999.0  -9999.0           -9999.0
4       -9999.0            -9999.0  -9999.0           -9999.0
5       -9999.0            -9999.0  -9999.0           -9999.0
12      -9999.0            -9999.0  -9999.0           -9999.0
13      -9999.0            -9999.0  -9999.0           -9999.0
...         ...                ...      ...               ...
61485       NaN                NaN      NaN               NaN
61486       NaN                NaN      NaN               NaN
61487       NaN                NaN      NaN               NaN
61488       NaN                NaN      NaN               NaN
61489       NaN                NaN      NaN               NaN

       Type_Of_Activity  Location_Code  Physical_Exertion_Code  Posture_Code  \
0               -9999.0        -9999.0                 -9999.0       -9999.0
4               -9999.0        -9999.0                 -9999.0       -9999.0
5               -9999.0        -9999.0                 -9999.0       -9999.0
12              -9999.0        -9999.0                 -9999.0       -9999.0
13              -9999.0        -9999.0                 -9999.0       -9999.0
...                 ...            ...                     ...           ...
61485               NaN            NaN                     NaN           NaN
61486               NaN            NaN                     NaN           NaN
61487               NaN            NaN                     NaN           NaN
61488               NaN            NaN                     NaN           NaN
61489               NaN            NaN                     NaN           NaN

       Social_Situation_Code  Type_Of_Activity_Code  ...  \
0                    -9999.0                -9999.0  ...
4                    -9999.0                -9999.0  ...
5                    -9999.0                -9999.0  ...
12                   -9999.0                -9999.0  ...
13                   -9999.0                -9999.0  ...
...                      ...                    ...  ...
61485                    NaN                    NaN  ...
61486                    NaN                    NaN  ...
61487                    NaN                    NaN  ...
61488                    NaN                    NaN  ...
61489                    NaN                    NaN  ...

       Artefact_Free_Respiration_percent  Majority_postures participant_id  \
0                             100.000000           Standing          12008
4                             100.000000            Sitting          12008
5                              94.863563           Standing          12008
12                            100.000000           Standing          12008
13                             96.875000           Standing          12008
...                                  ...                ...            ...
61485                         100.000000            Sitting          99857
61486                         100.000000            Sitting          99857
61487                         100.000000            Sitting          99857
61488                          81.878089            Sitting          99857
61489                         100.000000            Sitting          99857

      day Experimental_Conditions Experimental_Conditions_Code  \
0       1                     NaN                          NaN
4       1                     NaN                          NaN
5       1                     NaN                          NaN
12      1                     NaN                          NaN
13      1                     NaN                          NaN
...    ..                     ...                          ...
61485   2                 -9999.0                      -9999.0
61486   2                 -9999.0                      -9999.0
61487   2                 -9999.0                      -9999.0
61488   2                 -9999.0                      -9999.0
61489   2                 -9999.0                      -9999.0

       Artefact_Free_ECG_s  Calibrated_Tidal_Volume                datetime  \
0                      NaN                 2.933965 2024-09-02 11:09:53.500
4                      NaN                 1.706549 2024-09-02 11:13:53.500
5                      NaN                 2.811731 2024-09-02 11:14:53.500
12                     NaN                 2.683670 2024-09-02 11:21:53.500
13                     NaN                 2.478718 2024-09-02 11:22:53.500
...                    ...                      ...                     ...
61485                  NaN                 1.830138 2025-02-12 21:55:39.500
61486                  NaN                 1.581758 2025-02-12 21:56:39.500
61487                  NaN                 1.416549 2025-02-12 21:57:39.500
61488                  NaN                 2.225654 2025-02-12 21:58:39.500
61489                  NaN                 2.829555 2025-02-12 21:59:39.500

       Cleaned_Tidal_Volume
0                  2.933965
4                  1.706549
5                  2.811731
12                 2.683670
13                 2.478718
...                     ...
61485              1.830138
61486              1.581758
61487              1.416549
61488              2.225654
61489              2.829555

[47338 rows x 48 columns]

C:\Users\msa583\AppData\Local\Temp\ipykernel_31700\1678507945.py:36: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_awake_ambulatory['Cleaned_Tidal_Volume'] = df_awake_ambulatory.apply(lambda row: remove_outliers(row, stats), axis=1)

In [21]:
# calculate mean, min, and max for Calibrated_Tidal_Volume, after the removal of outliers for each participant specifically
participant_stats = df_awake_ambulatory.groupby('participant_id')['Calibrated_Tidal_Volume'].agg(['mean', 'min', 'max'])
print(participant_stats)

                    mean       min       max
participant_id
12008           1.712384  0.457229  3.295508
13304           0.568085  0.118275  1.303695
15337           0.665486  0.371967  1.221897
24340           0.460630  0.143540  1.056040
25201           0.472315  0.118884  0.917020
25879           0.514647  0.207447  1.167206
28327           0.820621  0.101613  3.396424
28404           0.614978  0.102459  1.338234
30739           0.561642  0.100385  1.787948
33280           0.365262  0.101986  1.207562
34714           0.775036  0.466584  1.396584
34763           0.508627  0.230354  2.466209
37092           0.771588  0.499509  1.715267
37818           0.829614  0.485022  1.195109
38029           0.567331  0.336559  1.020966
38645           0.534450  0.378149  0.913602
44066           0.390183  0.109487  0.922843
46773           0.354813  0.193881  0.541578
50129           0.407822  0.299495  0.717867
54783           0.869729  0.780386  1.144406
55110           0.721558  0.289539  1.614960
56143           0.506376  0.220531  1.211131
57458           0.707922  0.444997  2.463011
58996           1.695276  0.123175  4.137684
61972           1.589295  1.196595  3.643909
65919           0.905155  0.259042  2.322135
66303           0.571973  0.102820  1.070646
68416           0.582418  0.152963  1.302941
72950           0.538348  0.274401  0.904218
74998           0.485243  0.300820  1.315450
75967           0.579838  0.408917  0.837989
78692           0.431104  0.123221  1.673917
81981           0.444480  0.157257  0.780625
82556           1.264054  0.927118  5.787612
84645           0.245894  0.100018  0.715668
88137           0.628095  0.100637  1.932597
91169           0.600650  0.104934  2.425937
91850           0.640702  0.207984  1.225549
92674           0.413625  0.187835  1.079533
92957           0.359768  0.144056  0.661254
93676           0.787876  0.220474  3.676536
99857           1.586552  0.692212  3.598926

In [22]:
# calculate mean, min, and max per posture for IBI, RSA0, vector magnitude, tidal volume, and respiration rate
summary_stats = df_awake_ambulatory.groupby('Majority_postures')[['Average_IBI_msec', 'RSA0_msec', 'Total_Motility_mg', 'Calibrated_Tidal_Volume', 'Respiration_Rate_bpm']].agg(['mean', 'min', 'max'])

# calculate the percentage of rows per posture
posture_counts = df_awake_ambulatory['Majority_postures'].value_counts()
total_rows = len(df_awake_ambulatory)
posture_percentage = (posture_counts / total_rows) * 100

print("Summary Statistics (Mean, Min, Max) by Posture:")
print(summary_stats)

print("\nPercentage of Rows for Each Posture:")
print(posture_percentage)

Summary Statistics (Mean, Min, Max) by Posture:
                  Average_IBI_msec                           RSA0_msec       \
                              mean         min          max       mean  min
Majority_postures
Lying                   799.804252  395.708609  1334.875000  62.300921  0.0
Sitting                 757.520838  346.005814  1306.511111  62.108393  0.0
Standing                649.156875  340.273256  1122.038462  42.212770  0.0

                              Total_Motility_mg                        \
                          max              mean       min         max
Majority_postures
Lying              305.555556         24.806465  3.456337  159.753184
Sitting            415.857143         31.355670  3.405684  159.978562
Standing           322.444444         74.692697  5.411640  159.968723

                  Calibrated_Tidal_Volume                      \
                                     mean       min       max
Majority_postures
Lying                            0.577869  0.100385  5.787612
Sitting                          0.671343  0.100018  3.598926
Standing                         0.795597  0.104934  4.137684

                  Respiration_Rate_bpm
                                  mean       min        max
Majority_postures
Lying                        19.306102  9.278065  31.271192
Sitting                      17.340789  7.739626  32.626221
Standing                     17.423636  7.279412  33.025530

Percentage of Rows for Each Posture:
Majority_postures
Sitting     67.793316
Standing    23.668089
Lying        8.538595
Name: count, dtype: float64

In [ ]:
df_awake_ambulatory #there are 47338 rows of usable data that equates to 789 hours of data in total
#the predominant posture is sitting, as expected, followed by standing and lying

In [23]:
#need to save the excel at this point as the Notebook freezes otherwise (100% CPU)
df_awake_ambulatory.to_excel("df_awake_ambulatory_noRSAmetricsyet.xlsx")

# MAKING THE MULTIPLE REGRESSIONS IN WHICH RSA0 IS PREDICTED BY RESPIRATION RATE AND CALIBRATED TIDAL VOLUME PER POSTURE PER PARTICIPANT

In [24]:
#clean all outputs and reupload the dataframe (to save memory) - also do not print the dataframe as this consumes memory
#if you need to check something, save it as an excel and check on excel
df_awake_ambulatory = pd.read_excel("df_awake_ambulatory_noRSAmetricsyet.xlsx")

In [25]:
#print the number of data points per participant per posture
import pandas as pd

# showing full output, displaying row truncation
pd.set_option('display.max_rows', None) 
pd.set_option('display.max_columns', None)  

# group by participant_id and posture to count the number of epochs
epoch_counts = df_awake_ambulatory.groupby(['participant_id', 'Majority_postures']).size()
print(epoch_counts)

participant_id  Majority_postures
12008           Lying                 194
                Sitting               554
                Standing              374
13304           Lying                  16
                Sitting               122
                Standing               51
15337           Lying                  26
                Sitting               335
                Standing              168
24340           Lying                   1
                Sitting              1045
                Standing              259
25201           Lying                  78
                Sitting               738
                Standing              346
25879           Lying                  57
                Sitting               954
                Standing              237
28327           Lying                  86
                Sitting              1019
                Standing               93
28404           Lying                  36
                Sitting              1035
                Standing              296
30739           Lying                 126
                Sitting               633
                Standing              192
33280           Lying                  41
                Sitting              1005
                Standing              180
34714           Lying                   9
                Sitting              1007
                Standing              264
34763           Lying                  73
                Sitting               868
                Standing              376
37092           Lying                 140
                Sitting               919
                Standing              226
37818           Lying                  59
                Sitting               817
                Standing              367
38029           Lying                  50
                Sitting               685
                Standing              490
38645           Lying                 278
                Sitting               929
                Standing              178
44066           Lying                  65
                Sitting               710
                Standing              540
46773           Lying                 193
                Sitting               311
                Standing              153
50129           Lying                 206
                Sitting               903
                Standing              166
54783           Lying                   7
                Sitting               553
                Standing               52
55110           Lying                 253
                Sitting               617
                Standing              227
56143           Lying                 180
                Sitting               912
                Standing              276
57458           Lying                 114
                Sitting               685
                Standing              122
58996           Lying                  25
                Sitting               857
                Standing              174
61972           Lying                 333
                Sitting               825
                Standing              295
65919           Lying                  42
                Sitting              1026
                Standing              224
66303           Lying                  16
                Sitting               717
                Standing              483
68416           Lying                  38
                Sitting               540
                Standing              412
72950           Lying                 337
                Sitting               743
                Standing              245
74998           Lying                  18
                Sitting               573
                Standing              739
75967           Lying                  20
                Sitting              1182
                Standing              240
78692           Lying                  57
                Sitting               904
                Standing              250
81981           Lying                 163
                Sitting               835
                Standing              291
82556           Lying                  16
                Sitting               592
                Standing              292
84645           Lying                  42
                Sitting               784
                Standing              243
88137           Lying                 258
                Sitting               489
                Standing              242
91169           Lying                  20
                Sitting              1002
                Standing              230
91850           Lying                  98
                Sitting               801
                Standing              278
92674           Lying                 122
                Sitting               977
                Standing              169
92957           Lying                  39
                Sitting               351
                Standing              348
93676           Lying                  24
                Sitting               516
                Standing              289
99857           Lying                  86
                Sitting              1022
                Standing              127
dtype: int64

In [ ]:
# make a dataframe with the Standing data of participant 12008 to double check if the regression is correct when done with the function
#checked, the function that makes the participant and posture specific multiple regression lines for Approach 3 (for getting at residual RSA) is correct
#df_standing_12008 = df_awake_ambulatory[
  #  (df_awake_ambulatory['participant_id'] == 12008) &
  #  (df_awake_ambulatory['Majority_postures'] == 'Standing')
#]

#print(df_standing_12008)
#print(len(df_standing_12008))

In [ ]:
#import statsmodels.api as sm

# Step 1: Define the predictors (X) and outcome (y)
#X = df_standing_12008[['Calibrated_Tidal_Volume', 'Respiration_Rate_bpm']]
#y = df_standing_12008['RSA0_msec']

# Step 2: Add a constant (intercept) to the predictors
#X = sm.add_constant(X)

# Step 3: Fit the regression model
#model = sm.OLS(y, X).fit()

# Step 4: Print the regression summary
#print(model.summary())

In [26]:
import statsmodels.api as sm
import numpy as np

# function to run the multiple regressions for Approach 3 and subsequently calculate the Residual RSAs
# when there are less than 20 data points for a participant's given posture category, it skips that line (not statistically apppropriate to regress then)
def run_regression_and_calculate_residual(group, df_awake_ambulatory):
    # check if a min of 20 points is available
    if len(group) < 20:
        print(f"Skipping regression for Participant {group['participant_id'].iloc[0]} - Posture: {group['Majority_postures'].iloc[0]} (Less than 20 data points)\n")
        # put NaN to RSA0_residual since no regression is available
        df_awake_ambulatory.loc[group.index, 'RSA0_residual'] = np.nan
        return df_awake_ambulatory  
    
    # defining the independent variables
    X = group[['Calibrated_Tidal_Volume', 'Respiration_Rate_bpm']]
    # defining the dependent variable
    y = group['RSA0_msec']
    
    # add a constant for the intercept
    X = sm.add_constant(X)
    
    # fit the regression model
    model = sm.OLS(y, X).fit()
    
    # find the predicted RSA0 values
    group['predicted_RSA0'] = model.predict(X)
    
    # calculating the residual: observed - predicted
    group['RSA0_residual'] = group['RSA0_msec'] - group['predicted_RSA0']
    
    # adding the residual to the dataframe
    df_awake_ambulatory.loc[group.index, 'RSA0_residual'] = group['RSA0_residual']
    
    # print the equation for the regression
    intercept = model.params['const']
    tidal_volume_coef = model.params['Calibrated_Tidal_Volume']
    respiration_rate_coef = model.params['Respiration_Rate_bpm']
    
    intercept_pvalue = model.pvalues['const']
    tidal_volume_pvalue = model.pvalues['Calibrated_Tidal_Volume']
    respiration_rate_pvalue = model.pvalues['Respiration_Rate_bpm']
    
    print(f"Regression Equation for Participant {group['participant_id'].iloc[0]} - Posture: {group['Majority_postures'].iloc[0]}")
    print(f"RSA0_msec = {intercept:.4f} + ({tidal_volume_coef:.4f} * Calibrated_Tidal_Volume) + ({respiration_rate_coef:.4f} * Respiration_Rate_bpm)")
    print(f"P-value for Intercept: {intercept_pvalue:.4f}")
    print(f"P-value for Calibrated_Tidal_Volume: {tidal_volume_pvalue:.4f}")
    print(f"P-value for Respiration_Rate_bpm: {respiration_rate_pvalue:.4f}")
    print("\n")
    
    return df_awake_ambulatory

# implement the function for each participant and posture category
for (participant_id, posture), group in df_awake_ambulatory.groupby(['participant_id', 'Majority_postures']):
    df_awake_ambulatory = run_regression_and_calculate_residual(group, df_awake_ambulatory)

df_awake_ambulatory[['participant_id', 'Majority_postures', 'RSA0_msec', 'RSA0_residual', 'Calibrated_Tidal_Volume', 'Respiration_Rate_bpm']].head()

Regression Equation for Participant 12008 - Posture: Lying
RSA0_msec = 26.8618 + (5.9355 * Calibrated_Tidal_Volume) + (-0.5008 * Respiration_Rate_bpm)
P-value for Intercept: 0.0000
P-value for Calibrated_Tidal_Volume: 0.1340
P-value for Respiration_Rate_bpm: 0.0015


Regression Equation for Participant 12008 - Posture: Sitting
RSA0_msec = 33.7866 + (0.0579 * Calibrated_Tidal_Volume) + (-0.5706 * Respiration_Rate_bpm)
P-value for Intercept: 0.0000
P-value for Calibrated_Tidal_Volume: 0.9828
P-value for Respiration_Rate_bpm: 0.0000


Regression Equation for Participant 12008 - Posture: Standing
RSA0_msec = 43.3121 + (-5.0381 * Calibrated_Tidal_Volume) + (-0.6814 * Respiration_Rate_bpm)
P-value for Intercept: 0.0000
P-value for Calibrated_Tidal_Volume: 0.0063
P-value for Respiration_Rate_bpm: 0.0004


Skipping regression for Participant 13304 - Posture: Lying (Less than 20 data points)

Regression Equation for Participant 13304 - Posture: Sitting
RSA0_msec = 204.8733 + (-40.6168 * Calibrated_Tidal_Volume) + (-6.0630 * Respiration_Rate_bpm)
P-value for Intercept: 0.0000
P-value for Calibrated_Tidal_Volume: 0.0020
P-value for Respiration_Rate_bpm: 0.0000


Regression Equation for Participant 13304 - Posture: Standing
RSA0_msec = 113.4501 + (-3.9939 * Calibrated_Tidal_Volume) + (-3.3363 * Respiration_Rate_bpm)
P-value for Intercept: 0.0048
P-value for Calibrated_Tidal_Volume: 0.8638
P-value for Respiration_Rate_bpm: 0.0132


Regression Equation for Participant 15337 - Posture: Lying
RSA0_msec = 274.1138 + (-281.5295 * Calibrated_Tidal_Volume) + (-3.3743 * Respiration_Rate_bpm)
P-value for Intercept: 0.0165
P-value for Calibrated_Tidal_Volume: 0.0276
P-value for Respiration_Rate_bpm: 0.3039


Regression Equation for Participant 15337 - Posture: Sitting
RSA0_msec = 271.3890 + (-94.6453 * Calibrated_Tidal_Volume) + (-7.5428 * Respiration_Rate_bpm)
P-value for Intercept: 0.0000
P-value for Calibrated_Tidal_Volume: 0.0000
P-value for Respiration_Rate_bpm: 0.0000


Regression Equation for Participant 15337 - Posture: Standing
RSA0_msec = 237.4743 + (-113.1592 * Calibrated_Tidal_Volume) + (-5.6210 * Respiration_Rate_bpm)
P-value for Intercept: 0.0000
P-value for Calibrated_Tidal_Volume: 0.0001
P-value for Respiration_Rate_bpm: 0.0009


Skipping regression for Participant 24340 - Posture: Lying (Less than 20 data points)

Regression Equation for Participant 24340 - Posture: Sitting
RSA0_msec = 171.9806 + (-79.4435 * Calibrated_Tidal_Volume) + (-4.8963 * Respiration_Rate_bpm)
P-value for Intercept: 0.0000
P-value for Calibrated_Tidal_Volume: 0.0000
P-value for Respiration_Rate_bpm: 0.0000


Regression Equation for Participant 24340 - Posture: Standing
RSA0_msec = 78.8928 + (-13.9047 * Calibrated_Tidal_Volume) + (-2.3803 * Respiration_Rate_bpm)
P-value for Intercept: 0.0000
P-value for Calibrated_Tidal_Volume: 0.0337
P-value for Respiration_Rate_bpm: 0.0000


Regression Equation for Participant 25201 - Posture: Lying
RSA0_msec = 138.9547 + (-14.1867 * Calibrated_Tidal_Volume) + (-3.5556 * Respiration_Rate_bpm)
P-value for Intercept: 0.0000
P-value for Calibrated_Tidal_Volume: 0.3009
P-value for Respiration_Rate_bpm: 0.0001


Regression Equation for Participant 25201 - Posture: Sitting
RSA0_msec = 159.3839 + (-4.6438 * Calibrated_Tidal_Volume) + (-4.6877 * Respiration_Rate_bpm)
P-value for Intercept: 0.0000
P-value for Calibrated_Tidal_Volume: 0.4433
P-value for Respiration_Rate_bpm: 0.0000


Regression Equation for Participant 25201 - Posture: Standing
RSA0_msec = 145.3295 + (-28.5241 * Calibrated_Tidal_Volume) + (-3.9362 * Respiration_Rate_bpm)
P-value for Intercept: 0.0000
P-value for Calibrated_Tidal_Volume: 0.1015
P-value for Respiration_Rate_bpm: 0.0000


Regression Equation for Participant 25879 - Posture: Lying
RSA0_msec = 149.3653 + (-49.2869 * Calibrated_Tidal_Volume) + (-4.7518 * Respiration_Rate_bpm)
P-value for Intercept: 0.0000
P-value for Calibrated_Tidal_Volume: 0.0267
P-value for Respiration_Rate_bpm: 0.0017


Regression Equation for Participant 25879 - Posture: Sitting
RSA0_msec = 136.4268 + (-6.5196 * Calibrated_Tidal_Volume) + (-4.8038 * Respiration_Rate_bpm)
P-value for Intercept: 0.0000
P-value for Calibrated_Tidal_Volume: 0.1680
P-value for Respiration_Rate_bpm: 0.0000


Regression Equation for Participant 25879 - Posture: Standing
RSA0_msec = 151.7627 + (-26.3535 * Calibrated_Tidal_Volume) + (-5.1185 * Respiration_Rate_bpm)
P-value for Intercept: 0.0000
P-value for Calibrated_Tidal_Volume: 0.0049
P-value for Respiration_Rate_bpm: 0.0000


Regression Equation for Participant 28327 - Posture: Lying
RSA0_msec = 84.8448 + (5.4550 * Calibrated_Tidal_Volume) + (-2.1547 * Respiration_Rate_bpm)
P-value for Intercept: 0.0001
P-value for Calibrated_Tidal_Volume: 0.4024
P-value for Respiration_Rate_bpm: 0.0329


Regression Equation for Participant 28327 - Posture: Sitting
RSA0_msec = 126.0039 + (-17.4338 * Calibrated_Tidal_Volume) + (-3.8360 * Respiration_Rate_bpm)
P-value for Intercept: 0.0000
P-value for Calibrated_Tidal_Volume: 0.0000
P-value for Respiration_Rate_bpm: 0.0000


Regression Equation for Participant 28327 - Posture: Standing
RSA0_msec = 85.5691 + (-2.4295 * Calibrated_Tidal_Volume) + (-3.0681 * Respiration_Rate_bpm)
P-value for Intercept: 0.0000
P-value for Calibrated_Tidal_Volume: 0.3019
P-value for Respiration_Rate_bpm: 0.0000


Regression Equation for Participant 28404 - Posture: Lying
RSA0_msec = 161.4575 + (-75.7982 * Calibrated_Tidal_Volume) + (-4.9946 * Respiration_Rate_bpm)
P-value for Intercept: 0.0047
P-value for Calibrated_Tidal_Volume: 0.0003
P-value for Respiration_Rate_bpm: 0.0810


Regression Equation for Participant 28404 - Posture: Sitting
RSA0_msec = 189.0333 + (-45.3568 * Calibrated_Tidal_Volume) + (-6.5877 * Respiration_Rate_bpm)
P-value for Intercept: 0.0000
P-value for Calibrated_Tidal_Volume: 0.0000
P-value for Respiration_Rate_bpm: 0.0000


Regression Equation for Participant 28404 - Posture: Standing
RSA0_msec = 168.2955 + (-20.0389 * Calibrated_Tidal_Volume) + (-6.2830 * Respiration_Rate_bpm)
P-value for Intercept: 0.0000
P-value for Calibrated_Tidal_Volume: 0.0283
P-value for Respiration_Rate_bpm: 0.0000


Regression Equation for Participant 30739 - Posture: Lying
RSA0_msec = 168.2639 + (2.6401 * Calibrated_Tidal_Volume) + (-5.5452 * Respiration_Rate_bpm)
P-value for Intercept: 0.0000
P-value for Calibrated_Tidal_Volume: 0.8371
P-value for Respiration_Rate_bpm: 0.0000


Regression Equation for Participant 30739 - Posture: Sitting
RSA0_msec = 139.1010 + (-64.8782 * Calibrated_Tidal_Volume) + (-2.7106 * Respiration_Rate_bpm)
P-value for Intercept: 0.0000
P-value for Calibrated_Tidal_Volume: 0.0000
P-value for Respiration_Rate_bpm: 0.0000


Regression Equation for Participant 30739 - Posture: Standing
RSA0_msec = 81.7407 + (-5.1066 * Calibrated_Tidal_Volume) + (-2.0840 * Respiration_Rate_bpm)
P-value for Intercept: 0.0000
P-value for Calibrated_Tidal_Volume: 0.4203
P-value for Respiration_Rate_bpm: 0.0001


Regression Equation for Participant 33280 - Posture: Lying
RSA0_msec = 61.6614 + (-4.9776 * Calibrated_Tidal_Volume) + (-1.5722 * Respiration_Rate_bpm)
P-value for Intercept: 0.0126
P-value for Calibrated_Tidal_Volume: 0.8672
P-value for Respiration_Rate_bpm: 0.1653


Regression Equation for Participant 33280 - Posture: Sitting
RSA0_msec = 144.2786 + (-10.7927 * Calibrated_Tidal_Volume) + (-5.5675 * Respiration_Rate_bpm)
P-value for Intercept: 0.0000
P-value for Calibrated_Tidal_Volume: 0.0222
P-value for Respiration_Rate_bpm: 0.0000


Regression Equation for Participant 33280 - Posture: Standing
RSA0_msec = 89.2086 + (-0.3457 * Calibrated_Tidal_Volume) + (-3.3974 * Respiration_Rate_bpm)
P-value for Intercept: 0.0000
P-value for Calibrated_Tidal_Volume: 0.9757
P-value for Respiration_Rate_bpm: 0.0000


Skipping regression for Participant 34714 - Posture: Lying (Less than 20 data points)

Regression Equation for Participant 34714 - Posture: Sitting
RSA0_msec = 165.7110 + (-33.6855 * Calibrated_Tidal_Volume) + (-5.5495 * Respiration_Rate_bpm)
P-value for Intercept: 0.0000
P-value for Calibrated_Tidal_Volume: 0.0000
P-value for Respiration_Rate_bpm: 0.0000


Regression Equation for Participant 34714 - Posture: Standing
RSA0_msec = 89.2522 + (-5.0319 * Calibrated_Tidal_Volume) + (-3.1435 * Respiration_Rate_bpm)
P-value for Intercept: 0.0000
P-value for Calibrated_Tidal_Volume: 0.6283
P-value for Respiration_Rate_bpm: 0.0000


Regression Equation for Participant 34763 - Posture: Lying
RSA0_msec = 261.4599 + (-5.1395 * Calibrated_Tidal_Volume) + (-10.2519 * Respiration_Rate_bpm)
P-value for Intercept: 0.0000
P-value for Calibrated_Tidal_Volume: 0.5482
P-value for Respiration_Rate_bpm: 0.0000


Regression Equation for Participant 34763 - Posture: Sitting
RSA0_msec = 200.5573 + (-55.0397 * Calibrated_Tidal_Volume) + (-5.8982 * Respiration_Rate_bpm)
P-value for Intercept: 0.0000
P-value for Calibrated_Tidal_Volume: 0.0000
P-value for Respiration_Rate_bpm: 0.0000


Regression Equation for Participant 34763 - Posture: Standing
RSA0_msec = 179.8308 + (-29.5052 * Calibrated_Tidal_Volume) + (-5.9710 * Respiration_Rate_bpm)
P-value for Intercept: 0.0000
P-value for Calibrated_Tidal_Volume: 0.0000
P-value for Respiration_Rate_bpm: 0.0000


Regression Equation for Participant 37092 - Posture: Lying
RSA0_msec = 122.1778 + (-0.4728 * Calibrated_Tidal_Volume) + (-1.0460 * Respiration_Rate_bpm)
P-value for Intercept: 0.1418
P-value for Calibrated_Tidal_Volume: 0.9942
P-value for Respiration_Rate_bpm: 0.4479


Regression Equation for Participant 37092 - Posture: Sitting
RSA0_msec = 216.3230 + (-39.4775 * Calibrated_Tidal_Volume) + (-5.8300 * Respiration_Rate_bpm)
P-value for Intercept: 0.0000
P-value for Calibrated_Tidal_Volume: 0.0000
P-value for Respiration_Rate_bpm: 0.0000


Regression Equation for Participant 37092 - Posture: Standing
RSA0_msec = 263.8376 + (-62.6787 * Calibrated_Tidal_Volume) + (-9.0721 * Respiration_Rate_bpm)
P-value for Intercept: 0.0000
P-value for Calibrated_Tidal_Volume: 0.0000
P-value for Respiration_Rate_bpm: 0.0000


Regression Equation for Participant 37818 - Posture: Lying
RSA0_msec = 178.0592 + (231.4006 * Calibrated_Tidal_Volume) + (-14.8892 * Respiration_Rate_bpm)
P-value for Intercept: 0.4640
P-value for Calibrated_Tidal_Volume: 0.3198
P-value for Respiration_Rate_bpm: 0.0000


Regression Equation for Participant 37818 - Posture: Sitting
RSA0_msec = 607.0947 + (-301.0255 * Calibrated_Tidal_Volume) + (-12.4085 * Respiration_Rate_bpm)
P-value for Intercept: 0.0000
P-value for Calibrated_Tidal_Volume: 0.0000
P-value for Respiration_Rate_bpm: 0.0000


Regression Equation for Participant 37818 - Posture: Standing
RSA0_msec = 216.0521 + (11.2690 * Calibrated_Tidal_Volume) + (-5.8272 * Respiration_Rate_bpm)
P-value for Intercept: 0.0000
P-value for Calibrated_Tidal_Volume: 0.4063
P-value for Respiration_Rate_bpm: 0.0000


Regression Equation for Participant 38029 - Posture: Lying
RSA0_msec = 139.2586 + (-65.7173 * Calibrated_Tidal_Volume) + (-2.8730 * Respiration_Rate_bpm)
P-value for Intercept: 0.0000
P-value for Calibrated_Tidal_Volume: 0.1060
P-value for Respiration_Rate_bpm: 0.0015


Regression Equation for Participant 38029 - Posture: Sitting
RSA0_msec = 197.1201 + (-97.2229 * Calibrated_Tidal_Volume) + (-4.7608 * Respiration_Rate_bpm)
P-value for Intercept: 0.0000
P-value for Calibrated_Tidal_Volume: 0.0000
P-value for Respiration_Rate_bpm: 0.0000


Regression Equation for Participant 38029 - Posture: Standing
RSA0_msec = 106.8102 + (-13.9694 * Calibrated_Tidal_Volume) + (-3.4137 * Respiration_Rate_bpm)
P-value for Intercept: 0.0000
P-value for Calibrated_Tidal_Volume: 0.0345
P-value for Respiration_Rate_bpm: 0.0000


Regression Equation for Participant 38645 - Posture: Lying
RSA0_msec = 239.0463 + (-155.2051 * Calibrated_Tidal_Volume) + (-5.2298 * Respiration_Rate_bpm)
P-value for Intercept: 0.0000
P-value for Calibrated_Tidal_Volume: 0.0015
P-value for Respiration_Rate_bpm: 0.0000


Regression Equation for Participant 38645 - Posture: Sitting
RSA0_msec = 216.3011 + (-93.4878 * Calibrated_Tidal_Volume) + (-4.0794 * Respiration_Rate_bpm)
P-value for Intercept: 0.0000
P-value for Calibrated_Tidal_Volume: 0.0000
P-value for Respiration_Rate_bpm: 0.0000


Regression Equation for Participant 38645 - Posture: Standing
RSA0_msec = 176.5493 + (-121.1111 * Calibrated_Tidal_Volume) + (-2.3093 * Respiration_Rate_bpm)
P-value for Intercept: 0.0000
P-value for Calibrated_Tidal_Volume: 0.0140
P-value for Respiration_Rate_bpm: 0.0366


Regression Equation for Participant 44066 - Posture: Lying
RSA0_msec = 181.9723 + (-160.2337 * Calibrated_Tidal_Volume) + (-2.1003 * Respiration_Rate_bpm)
P-value for Intercept: 0.0004
P-value for Calibrated_Tidal_Volume: 0.0001
P-value for Respiration_Rate_bpm: 0.3718


Regression Equation for Participant 44066 - Posture: Sitting
RSA0_msec = 125.0552 + (-18.6637 * Calibrated_Tidal_Volume) + (-3.1081 * Respiration_Rate_bpm)
P-value for Intercept: 0.0000
P-value for Calibrated_Tidal_Volume: 0.0073
P-value for Respiration_Rate_bpm: 0.0000


Regression Equation for Participant 44066 - Posture: Standing
RSA0_msec = 158.2630 + (-79.6449 * Calibrated_Tidal_Volume) + (-4.0768 * Respiration_Rate_bpm)
P-value for Intercept: 0.0000
P-value for Calibrated_Tidal_Volume: 0.0000
P-value for Respiration_Rate_bpm: 0.0000


Regression Equation for Participant 46773 - Posture: Lying
RSA0_msec = 168.8093 + (-85.4938 * Calibrated_Tidal_Volume) + (-2.6475 * Respiration_Rate_bpm)
P-value for Intercept: 0.0006
P-value for Calibrated_Tidal_Volume: 0.3342
P-value for Respiration_Rate_bpm: 0.0049


Regression Equation for Participant 46773 - Posture: Sitting
RSA0_msec = 53.9571 + (-80.6839 * Calibrated_Tidal_Volume) + (1.6800 * Respiration_Rate_bpm)
P-value for Intercept: 0.0003
P-value for Calibrated_Tidal_Volume: 0.1049
P-value for Respiration_Rate_bpm: 0.0004


Regression Equation for Participant 46773 - Posture: Standing
RSA0_msec = -27.4703 + (155.1897 * Calibrated_Tidal_Volume) + (-1.1549 * Respiration_Rate_bpm)
P-value for Intercept: 0.4242
P-value for Calibrated_Tidal_Volume: 0.0097
P-value for Respiration_Rate_bpm: 0.1426


Regression Equation for Participant 50129 - Posture: Lying
RSA0_msec = 47.5085 + (-30.1725 * Calibrated_Tidal_Volume) + (-0.6214 * Respiration_Rate_bpm)
P-value for Intercept: 0.3523
P-value for Calibrated_Tidal_Volume: 0.7762
P-value for Respiration_Rate_bpm: 0.2958


Regression Equation for Participant 50129 - Posture: Sitting
RSA0_msec = 74.6857 + (-10.4242 * Calibrated_Tidal_Volume) + (-2.0016 * Respiration_Rate_bpm)
P-value for Intercept: 0.0000
P-value for Calibrated_Tidal_Volume: 0.4735
P-value for Respiration_Rate_bpm: 0.0000


Regression Equation for Participant 50129 - Posture: Standing
RSA0_msec = 85.7046 + (-38.5180 * Calibrated_Tidal_Volume) + (-2.3782 * Respiration_Rate_bpm)
P-value for Intercept: 0.0000
P-value for Calibrated_Tidal_Volume: 0.0019
P-value for Respiration_Rate_bpm: 0.0000


Skipping regression for Participant 54783 - Posture: Lying (Less than 20 data points)

Regression Equation for Participant 54783 - Posture: Sitting
RSA0_msec = 388.3452 + (-211.2524 * Calibrated_Tidal_Volume) + (-5.3341 * Respiration_Rate_bpm)
P-value for Intercept: 0.0000
P-value for Calibrated_Tidal_Volume: 0.0000
P-value for Respiration_Rate_bpm: 0.0000


Regression Equation for Participant 54783 - Posture: Standing
RSA0_msec = 206.9036 + (-186.1327 * Calibrated_Tidal_Volume) + (0.4952 * Respiration_Rate_bpm)
P-value for Intercept: 0.0912
P-value for Calibrated_Tidal_Volume: 0.1048
P-value for Respiration_Rate_bpm: 0.7385


Regression Equation for Participant 55110 - Posture: Lying
RSA0_msec = 105.1291 + (156.3574 * Calibrated_Tidal_Volume) + (-4.8436 * Respiration_Rate_bpm)
P-value for Intercept: 0.0048
P-value for Calibrated_Tidal_Volume: 0.0006
P-value for Respiration_Rate_bpm: 0.0009


Regression Equation for Participant 55110 - Posture: Sitting
RSA0_msec = 156.6794 + (66.4704 * Calibrated_Tidal_Volume) + (-6.5899 * Respiration_Rate_bpm)
P-value for Intercept: 0.0116
P-value for Calibrated_Tidal_Volume: 0.2849
P-value for Respiration_Rate_bpm: 0.0000


Regression Equation for Participant 55110 - Posture: Standing
RSA0_msec = 230.0207 + (-56.5623 * Calibrated_Tidal_Volume) + (-6.1562 * Respiration_Rate_bpm)
P-value for Intercept: 0.0000
P-value for Calibrated_Tidal_Volume: 0.0018
P-value for Respiration_Rate_bpm: 0.0000


Regression Equation for Participant 56143 - Posture: Lying
RSA0_msec = 113.9807 + (6.9525 * Calibrated_Tidal_Volume) + (-3.7251 * Respiration_Rate_bpm)
P-value for Intercept: 0.0000
P-value for Calibrated_Tidal_Volume: 0.6832
P-value for Respiration_Rate_bpm: 0.0000


Regression Equation for Participant 56143 - Posture: Sitting
RSA0_msec = 193.9405 + (-44.4708 * Calibrated_Tidal_Volume) + (-6.3892 * Respiration_Rate_bpm)
P-value for Intercept: 0.0000
P-value for Calibrated_Tidal_Volume: 0.0000
P-value for Respiration_Rate_bpm: 0.0000


Regression Equation for Participant 56143 - Posture: Standing
RSA0_msec = 133.8111 + (3.2830 * Calibrated_Tidal_Volume) + (-5.4839 * Respiration_Rate_bpm)
P-value for Intercept: 0.0000
P-value for Calibrated_Tidal_Volume: 0.6784
P-value for Respiration_Rate_bpm: 0.0000


Regression Equation for Participant 57458 - Posture: Lying
RSA0_msec = 207.6320 + (-130.6878 * Calibrated_Tidal_Volume) + (-4.2012 * Respiration_Rate_bpm)
P-value for Intercept: 0.0000
P-value for Calibrated_Tidal_Volume: 0.0145
P-value for Respiration_Rate_bpm: 0.0000


Regression Equation for Participant 57458 - Posture: Sitting
RSA0_msec = 111.9102 + (-5.4265 * Calibrated_Tidal_Volume) + (-3.5821 * Respiration_Rate_bpm)
P-value for Intercept: 0.0000
P-value for Calibrated_Tidal_Volume: 0.0357
P-value for Respiration_Rate_bpm: 0.0000


Regression Equation for Participant 57458 - Posture: Standing
RSA0_msec = 114.1025 + (-10.5735 * Calibrated_Tidal_Volume) + (-4.1340 * Respiration_Rate_bpm)
P-value for Intercept: 0.0000
P-value for Calibrated_Tidal_Volume: 0.1693
P-value for Respiration_Rate_bpm: 0.0000


Regression Equation for Participant 58996 - Posture: Lying
RSA0_msec = 328.7463 + (-80.4485 * Calibrated_Tidal_Volume) + (-12.3115 * Respiration_Rate_bpm)
P-value for Intercept: 0.0000
P-value for Calibrated_Tidal_Volume: 0.0282
P-value for Respiration_Rate_bpm: 0.0017


Regression Equation for Participant 58996 - Posture: Sitting
RSA0_msec = 77.1617 + (59.8203 * Calibrated_Tidal_Volume) + (-5.8291 * Respiration_Rate_bpm)
P-value for Intercept: 0.0000
P-value for Calibrated_Tidal_Volume: 0.0000
P-value for Respiration_Rate_bpm: 0.0000


Regression Equation for Participant 58996 - Posture: Standing
RSA0_msec = 137.2973 + (-7.6090 * Calibrated_Tidal_Volume) + (-4.6071 * Respiration_Rate_bpm)
P-value for Intercept: 0.0000
P-value for Calibrated_Tidal_Volume: 0.1262
P-value for Respiration_Rate_bpm: 0.0000


Regression Equation for Participant 61972 - Posture: Lying
RSA0_msec = 222.8605 + (-81.3693 * Calibrated_Tidal_Volume) + (-3.7891 * Respiration_Rate_bpm)
P-value for Intercept: 0.0001
P-value for Calibrated_Tidal_Volume: 0.0521
P-value for Respiration_Rate_bpm: 0.0000


Regression Equation for Participant 61972 - Posture: Sitting
RSA0_msec = 131.5893 + (2.8341 * Calibrated_Tidal_Volume) + (-6.0872 * Respiration_Rate_bpm)
P-value for Intercept: 0.0000
P-value for Calibrated_Tidal_Volume: 0.8432
P-value for Respiration_Rate_bpm: 0.0000


Regression Equation for Participant 61972 - Posture: Standing
RSA0_msec = 89.4284 + (-0.4228 * Calibrated_Tidal_Volume) + (-3.2711 * Respiration_Rate_bpm)
P-value for Intercept: 0.0000
P-value for Calibrated_Tidal_Volume: 0.9175
P-value for Respiration_Rate_bpm: 0.0000


Regression Equation for Participant 65919 - Posture: Lying
RSA0_msec = 8.8600 + (30.7186 * Calibrated_Tidal_Volume) + (-2.3060 * Respiration_Rate_bpm)
P-value for Intercept: 0.9769
P-value for Calibrated_Tidal_Volume: 0.8093
P-value for Respiration_Rate_bpm: 0.3148



,participant_id,Majority_postures,RSA0_msec,RSA0_residual,Calibrated_Tidal_Volume,Respiration_Rate_bpm
0,12008,Standing,12.142857,-5.358006,2.933965,16.185775
1,12008,Sitting,11.153846,-13.883491,1.706549,15.507188
2,12008,Standing,14.000000,-3.689623,2.811731,16.812479
3,12008,Standing,22.230769,2.632711,2.683670,14.958695
4,12008,Standing,19.636364,-2.231437,2.478718,13.143172

In [27]:
import statsmodels.api as sm
import numpy as np
# function to run the multiple regressions for Approach 3 and subsequently calculate the Residual RSAs - the version that first eliminates the
   #respiration rate and RSA0 values that deviate 4.5 sds or more than the mean within participant within posture
# when there are less than 20 data points for a participant's given posture category, it skips that line (not statistically apppropriate to regress then)

def run_regression_and_calculate_residual_45(group, df):
   # remove outliers ≥ 4.5 SDs from the mean for RSA0 and Respiration Rate
    rsa0_mean = group['RSA0_msec'].mean()
    rsa0_std = group['RSA0_msec'].std()
    rr_mean = group['Respiration_Rate_bpm'].mean()
    rr_std = group['Respiration_Rate_bpm'].std()

    #we already previously filtered to remove deviant calibrated tidal volume values so no need to do that again
    group_filtered = group[
        (np.abs(group['RSA0_msec'] - rsa0_mean) < 4.5 * rsa0_std) &
        (np.abs(group['Respiration_Rate_bpm'] - rr_mean) < 4.5 * rr_std)
    ]
    # checking if at least a min of 20 data points remained
    if len(group_filtered) < 20:
        print(f"Skipping regression for Participant {group['participant_id'].iloc[0]} - Posture: {group['Majority_postures'].iloc[0]} (Less than 20 data points after filtering)\n")
        df.loc[group.index, 'RSA0_residual_45'] = np.nan
        return df

    # defining the independent variables as tidal volume and respiration rate, and adding a constant
    X_filtered = sm.add_constant(group_filtered[['Calibrated_Tidal_Volume', 'Respiration_Rate_bpm']])
    # defining the dependent variable as RSA0
    y_filtered = group_filtered['RSA0_msec']
    model = sm.OLS(y_filtered, X_filtered).fit()

    # predict for *all* rows including the outliers which were not taken into account while making the regressions
    X_all = sm.add_constant(group[['Calibrated_Tidal_Volume', 'Respiration_Rate_bpm']])
    group['predicted_RSA0_45'] = model.predict(X_all)
    group['RSA0_residual_45'] = group['RSA0_msec'] - group['predicted_RSA0_45']

    # assign residuals back to full dataframe
    df.loc[group.index, 'RSA0_residual_45'] = group['RSA0_residual_45']

    intercept = model.params['const']
    tidal_volume_coef = model.params['Calibrated_Tidal_Volume']
    respiration_rate_coef = model.params['Respiration_Rate_bpm']

    intercept_pvalue = model.pvalues['const']
    tidal_volume_pvalue = model.pvalues['Calibrated_Tidal_Volume']
    respiration_rate_pvalue = model.pvalues['Respiration_Rate_bpm']

    print(f"Regression Equation for Participant {group['participant_id'].iloc[0]} - Posture: {group['Majority_postures'].iloc[0]} (Filtered for fitting only)")
    print(f"RSA0_msec = {intercept:.4f} + ({tidal_volume_coef:.4f} * Calibrated_Tidal_Volume) + ({respiration_rate_coef:.4f} * Respiration_Rate_bpm)")
    print(f"P-value for Intercept: {intercept_pvalue:.4f}")
    print(f"P-value for Calibrated_Tidal_Volume: {tidal_volume_pvalue:.4f}")
    print(f"P-value for Respiration_Rate_bpm: {respiration_rate_pvalue:.4f}\n")

    return df
    
# applying the function to the dataframe in which we group by the participant_id and posture 
for (participant_id, posture), group in df_awake_ambulatory.groupby(['participant_id', 'Majority_postures']):
    df_awake_ambulatory = run_regression_and_calculate_residual_45(group, df_awake_ambulatory)

# previewing the relevant columns
df_awake_ambulatory[['participant_id', 'Majority_postures', 'RSA0_msec', 'RSA0_residual_45', 'Calibrated_Tidal_Volume', 'Respiration_Rate_bpm']].head()

Regression Equation for Participant 12008 - Posture: Lying (Filtered for fitting only)
RSA0_msec = 26.8618 + (5.9355 * Calibrated_Tidal_Volume) + (-0.5008 * Respiration_Rate_bpm)
P-value for Intercept: 0.0000
P-value for Calibrated_Tidal_Volume: 0.1340
P-value for Respiration_Rate_bpm: 0.0015

Regression Equation for Participant 12008 - Posture: Sitting (Filtered for fitting only)
RSA0_msec = 33.0050 + (0.1294 * Calibrated_Tidal_Volume) + (-0.5380 * Respiration_Rate_bpm)
P-value for Intercept: 0.0000
P-value for Calibrated_Tidal_Volume: 0.9601
P-value for Respiration_Rate_bpm: 0.0000

Regression Equation for Participant 12008 - Posture: Standing (Filtered for fitting only)
RSA0_msec = 38.0252 + (-4.2131 * Calibrated_Tidal_Volume) + (-0.5019 * Respiration_Rate_bpm)
P-value for Intercept: 0.0000
P-value for Calibrated_Tidal_Volume: 0.0137
P-value for Respiration_Rate_bpm: 0.0058

Skipping regression for Participant 13304 - Posture: Lying (Less than 20 data points after filtering)

Regression Equation for Participant 13304 - Posture: Sitting (Filtered for fitting only)
RSA0_msec = 202.3690 + (-51.4162 * Calibrated_Tidal_Volume) + (-5.6844 * Respiration_Rate_bpm)
P-value for Intercept: 0.0000
P-value for Calibrated_Tidal_Volume: 0.0000
P-value for Respiration_Rate_bpm: 0.0000

Regression Equation for Participant 13304 - Posture: Standing (Filtered for fitting only)
RSA0_msec = 113.4501 + (-3.9939 * Calibrated_Tidal_Volume) + (-3.3363 * Respiration_Rate_bpm)
P-value for Intercept: 0.0048
P-value for Calibrated_Tidal_Volume: 0.8638
P-value for Respiration_Rate_bpm: 0.0132

Regression Equation for Participant 15337 - Posture: Lying (Filtered for fitting only)
RSA0_msec = 274.1138 + (-281.5295 * Calibrated_Tidal_Volume) + (-3.3743 * Respiration_Rate_bpm)
P-value for Intercept: 0.0165
P-value for Calibrated_Tidal_Volume: 0.0276
P-value for Respiration_Rate_bpm: 0.3039

Regression Equation for Participant 15337 - Posture: Sitting (Filtered for fitting only)
RSA0_msec = 271.3890 + (-94.6453 * Calibrated_Tidal_Volume) + (-7.5428 * Respiration_Rate_bpm)
P-value for Intercept: 0.0000
P-value for Calibrated_Tidal_Volume: 0.0000
P-value for Respiration_Rate_bpm: 0.0000

Regression Equation for Participant 15337 - Posture: Standing (Filtered for fitting only)
RSA0_msec = 198.5909 + (-86.5878 * Calibrated_Tidal_Volume) + (-4.7228 * Respiration_Rate_bpm)
P-value for Intercept: 0.0000
P-value for Calibrated_Tidal_Volume: 0.0003
P-value for Respiration_Rate_bpm: 0.0007

Skipping regression for Participant 24340 - Posture: Lying (Less than 20 data points after filtering)

Regression Equation for Participant 24340 - Posture: Sitting (Filtered for fitting only)
RSA0_msec = 171.9806 + (-79.4435 * Calibrated_Tidal_Volume) + (-4.8963 * Respiration_Rate_bpm)
P-value for Intercept: 0.0000
P-value for Calibrated_Tidal_Volume: 0.0000
P-value for Respiration_Rate_bpm: 0.0000

Regression Equation for Participant 24340 - Posture: Standing (Filtered for fitting only)
RSA0_msec = 78.8928 + (-13.9047 * Calibrated_Tidal_Volume) + (-2.3803 * Respiration_Rate_bpm)
P-value for Intercept: 0.0000
P-value for Calibrated_Tidal_Volume: 0.0337
P-value for Respiration_Rate_bpm: 0.0000

Regression Equation for Participant 25201 - Posture: Lying (Filtered for fitting only)
RSA0_msec = 138.9547 + (-14.1867 * Calibrated_Tidal_Volume) + (-3.5556 * Respiration_Rate_bpm)
P-value for Intercept: 0.0000
P-value for Calibrated_Tidal_Volume: 0.3009
P-value for Respiration_Rate_bpm: 0.0001

Regression Equation for Participant 25201 - Posture: Sitting (Filtered for fitting only)
RSA0_msec = 155.7594 + (-4.9413 * Calibrated_Tidal_Volume) + (-4.4842 * Respiration_Rate_bpm)
P-value for Intercept: 0.0000
P-value for Calibrated_Tidal_Volume: 0.4105
P-value for Respiration_Rate_bpm: 0.0000

Regression Equation for Participant 25201 - Posture: Standing (Filtered for fitting only)
RSA0_msec = 145.3295 + (-28.5241 * Calibrated_Tidal_Volume) + (-3.9362 * Respiration_Rate_bpm)
P-value for Intercept: 0.0000
P-value for Calibrated_Tidal_Volume: 0.1015
P-value for Respiration_Rate_bpm: 0.0000

Regression Equation for Participant 25879 - Posture: Lying (Filtered for fitting only)
RSA0_msec = 149.3653 + (-49.2869 * Calibrated_Tidal_Volume) + (-4.7518 * Respiration_Rate_bpm)
P-value for Intercept: 0.0000
P-value for Calibrated_Tidal_Volume: 0.0267
P-value for Respiration_Rate_bpm: 0.0017

Regression Equation for Participant 25879 - Posture: Sitting (Filtered for fitting only)
RSA0_msec = 136.8619 + (-8.1662 * Calibrated_Tidal_Volume) + (-4.7871 * Respiration_Rate_bpm)
P-value for Intercept: 0.0000
P-value for Calibrated_Tidal_Volume: 0.0811
P-value for Respiration_Rate_bpm: 0.0000

Regression Equation for Participant 25879 - Posture: Standing (Filtered for fitting only)
RSA0_msec = 151.7627 + (-26.3535 * Calibrated_Tidal_Volume) + (-5.1185 * Respiration_Rate_bpm)
P-value for Intercept: 0.0000
P-value for Calibrated_Tidal_Volume: 0.0049
P-value for Respiration_Rate_bpm: 0.0000

Regression Equation for Participant 28327 - Posture: Lying (Filtered for fitting only)
RSA0_msec = 84.8448 + (5.4550 * Calibrated_Tidal_Volume) + (-2.1547 * Respiration_Rate_bpm)
P-value for Intercept: 0.0001
P-value for Calibrated_Tidal_Volume: 0.4024
P-value for Respiration_Rate_bpm: 0.0329

Regression Equation for Participant 28327 - Posture: Sitting (Filtered for fitting only)
RSA0_msec = 125.0380 + (-17.7894 * Calibrated_Tidal_Volume) + (-3.7753 * Respiration_Rate_bpm)
P-value for Intercept: 0.0000
P-value for Calibrated_Tidal_Volume: 0.0000
P-value for Respiration_Rate_bpm: 0.0000

Regression Equation for Participant 28327 - Posture: Standing (Filtered for fitting only)
RSA0_msec = 85.5691 + (-2.4295 * Calibrated_Tidal_Volume) + (-3.0681 * Respiration_Rate_bpm)
P-value for Intercept: 0.0000
P-value for Calibrated_Tidal_Volume: 0.3019
P-value for Respiration_Rate_bpm: 0.0000

Regression Equation for Participant 28404 - Posture: Lying (Filtered for fitting only)
RSA0_msec = 161.4575 + (-75.7982 * Calibrated_Tidal_Volume) + (-4.9946 * Respiration_Rate_bpm)
P-value for Intercept: 0.0047
P-value for Calibrated_Tidal_Volume: 0.0003
P-value for Respiration_Rate_bpm: 0.0810

Regression Equation for Participant 28404 - Posture: Sitting (Filtered for fitting only)
RSA0_msec = 189.0333 + (-45.3568 * Calibrated_Tidal_Volume) + (-6.5877 * Respiration_Rate_bpm)
P-value for Intercept: 0.0000
P-value for Calibrated_Tidal_Volume: 0.0000
P-value for Respiration_Rate_bpm: 0.0000

Regression Equation for Participant 28404 - Posture: Standing (Filtered for fitting only)
RSA0_msec = 157.2519 + (-14.3433 * Calibrated_Tidal_Volume) + (-5.9220 * Respiration_Rate_bpm)
P-value for Intercept: 0.0000
P-value for Calibrated_Tidal_Volume: 0.0986
P-value for Respiration_Rate_bpm: 0.0000

Regression Equation for Participant 30739 - Posture: Lying (Filtered for fitting only)
RSA0_msec = 168.2639 + (2.6401 * Calibrated_Tidal_Volume) + (-5.5452 * Respiration_Rate_bpm)
P-value for Intercept: 0.0000
P-value for Calibrated_Tidal_Volume: 0.8371
P-value for Respiration_Rate_bpm: 0.0000

Regression Equation for Participant 30739 - Posture: Sitting (Filtered for fitting only)
RSA0_msec = 139.1010 + (-64.8782 * Calibrated_Tidal_Volume) + (-2.7106 * Respiration_Rate_bpm)
P-value for Intercept: 0.0000
P-value for Calibrated_Tidal_Volume: 0.0000
P-value for Respiration_Rate_bpm: 0.0000

Regression Equation for Participant 30739 - Posture: Standing (Filtered for fitting only)
RSA0_msec = 81.7407 + (-5.1066 * Calibrated_Tidal_Volume) + (-2.0840 * Respiration_Rate_bpm)
P-value for Intercept: 0.0000
P-value for Calibrated_Tidal_Volume: 0.4203
P-value for Respiration_Rate_bpm: 0.0001

Regression Equation for Participant 33280 - Posture: Lying (Filtered for fitting only)
RSA0_msec = 61.6614 + (-4.9776 * Calibrated_Tidal_Volume) + (-1.5722 * Respiration_Rate_bpm)
P-value for Intercept: 0.0126
P-value for Calibrated_Tidal_Volume: 0.8672
P-value for Respiration_Rate_bpm: 0.1653

Regression Equation for Participant 33280 - Posture: Sitting (Filtered for fitting only)
RSA0_msec = 139.8682 + (-11.3414 * Calibrated_Tidal_Volume) + (-5.3136 * Respiration_Rate_bpm)
P-value for Intercept: 0.0000
P-value for Calibrated_Tidal_Volume: 0.0104
P-value for Respiration_Rate_bpm: 0.0000

Regression Equation for Participant 33280 - Posture: Standing (Filtered for fitting only)
RSA0_msec = 85.5150 + (-0.4884 * Calibrated_Tidal_Volume) + (-3.1982 * Respiration_Rate_bpm)
P-value for Intercept: 0.0000
P-value for Calibrated_Tidal_Volume: 0.9636
P-value for Respiration_Rate_bpm: 0.0000

Skipping regression for Participant 34714 - Posture: Lying (Less than 20 data points after filtering)

Regression Equation for Participant 34714 - Posture: Sitting (Filtered for fitting only)
RSA0_msec = 167.8745 + (-35.2863 * Calibrated_Tidal_Volume) + (-5.6155 * Respiration_Rate_bpm)
P-value for Intercept: 0.0000
P-value for Calibrated_Tidal_Volume: 0.0000
P-value for Respiration_Rate_bpm: 0.0000

Regression Equation for Participant 34714 - Posture: Standing (Filtered for fitting only)
RSA0_msec = 83.5668 + (-1.3813 * Calibrated_Tidal_Volume) + (-3.0434 * Respiration_Rate_bpm)
P-value for Intercept: 0.0000
P-value for Calibrated_Tidal_Volume: 0.8886
P-value for Respiration_Rate_bpm: 0.0000

Regression Equation for Participant 34763 - Posture: Lying (Filtered for fitting only)
RSA0_msec = 261.4599 + (-5.1395 * Calibrated_Tidal_Volume) + (-10.2519 * Respiration_Rate_bpm)
P-value for Intercept: 0.0000
P-value for Calibrated_Tidal_Volume: 0.5482
P-value for Respiration_Rate_bpm: 0.0000

Regression Equation for Participant 34763 - Posture: Sitting (Filtered for fitting only)
RSA0_msec = 200.5573 + (-55.0397 * Calibrated_Tidal_Volume) + (-5.8982 * Respiration_Rate_bpm)
P-value for Intercept: 0.0000
P-value for Calibrated_Tidal_Volume: 0.0000
P-value for Respiration_Rate_bpm: 0.0000

Regression Equation for Participant 34763 - Posture: Standing (Filtered for fitting only)
RSA0_msec = 179.8308 + (-29.5052 * Calibrated_Tidal_Volume) + (-5.9710 * Respiration_Rate_bpm)
P-value for Intercept: 0.0000
P-value for Calibrated_Tidal_Volume: 0.0000
P-value for Respiration_Rate_bpm: 0.0000

Regression Equation for Participant 37092 - Posture: Lying (Filtered for fitting only)
RSA0_msec = 122.1778 + (-0.4728 * Calibrated_Tidal_Volume) + (-1.0460 * Respiration_Rate_bpm)
P-value for Intercept: 0.1418
P-value for Calibrated_Tidal_Volume: 0.9942
P-value for Respiration_Rate_bpm: 0.4479

Regression Equation for Participant 37092 - Posture: Sitting (Filtered for fitting only)
RSA0_msec = 216.3230 + (-39.4775 * Calibrated_Tidal_Volume) + (-5.8300 * Respiration_Rate_bpm)
P-value for Intercept: 0.0000
P-value for Calibrated_Tidal_Volume: 0.0000
P-value for Respiration_Rate_bpm: 0.0000

Regression Equation for Participant 37092 - Posture: Standing (Filtered for fitting only)
RSA0_msec = 263.8376 + (-62.6787 * Calibrated_Tidal_Volume) + (-9.0721 * Respiration_Rate_bpm)
P-value for Intercept: 0.0000
P-value for Calibrated_Tidal_Volume: 0.0000
P-value for Respiration_Rate_bpm: 0.0000

Regression Equation for Participant 37818 - Posture: Lying (Filtered for fitting only)
RSA0_msec = 178.0592 + (231.4006 * Calibrated_Tidal_Volume) + (-14.8892 * Respiration_Rate_bpm)
P-value for Intercept: 0.4640
P-value for Calibrated_Tidal_Volume: 0.3198
P-value for Respiration_Rate_bpm: 0.0000

Regression Equation for Participant 37818 - Posture: Sitting (Filtered for fitting only)
RSA0_msec = 596.6583 + (-301.8227 * Calibrated_Tidal_Volume) + (-11.7236 * Respiration_Rate_bpm)
P-value for Intercept: 0.0000
P-value for Calibrated_Tidal_Volume: 0.0000
P-value for Respiration_Rate_bpm: 0.0000

Regression Equation for Participant 37818 - Posture: Standing (Filtered for fitting only)
RSA0_msec = 202.6994 + (15.7327 * Calibrated_Tidal_Volume) + (-5.2334 * Respiration_Rate_bpm)
P-value for Intercept: 0.0000
P-value for Calibrated_Tidal_Volume: 0.2311
P-value for Respiration_Rate_bpm: 0.0000

Regression Equation for Participant 38029 - Posture: Lying (Filtered for fitting only)
RSA0_msec = 139.2586 + (-65.7173 * Calibrated_Tidal_Volume) + (-2.8730 * Respiration_Rate_bpm)
P-value for Intercept: 0.0000
P-value for Calibrated_Tidal_Volume: 0.1060
P-value for Respiration_Rate_bpm: 0.0015

Regression Equation for Participant 38029 - Posture: Sitting (Filtered for fitting only)
RSA0_msec = 197.1201 + (-97.2229 * Calibrated_Tidal_Volume) + (-4.7608 * Respiration_Rate_bpm)
P-value for Intercept: 0.0000
P-value for Calibrated_Tidal_Volume: 0.0000
P-value for Respiration_Rate_bpm: 0.0000

Regression Equation for Participant 38029 - Posture: Standing (Filtered for fitting only)
RSA0_msec = 106.8102 + (-13.9694 * Calibrated_Tidal_Volume) + (-3.4137 * Respiration_Rate_bpm)
P-value for Intercept: 0.0000
P-value for Calibrated_Tidal_Volume: 0.0345
P-value for Respiration_Rate_bpm: 0.0000

Regression Equation for Participant 38645 - Posture: Lying (Filtered for fitting only)
RSA0_msec = 239.0463 + (-155.2051 * Calibrated_Tidal_Volume) + (-5.2298 * Respiration_Rate_bpm)
P-value for Intercept: 0.0000
P-value for Calibrated_Tidal_Volume: 0.0015
P-value for Respiration_Rate_bpm: 0.0000

Regression Equation for Participant 38645 - Posture: Sitting (Filtered for fitting only)
RSA0_msec = 216.3011 + (-93.4878 * Calibrated_Tidal_Volume) + (-4.0794 * Respiration_Rate_bpm)
P-value for Intercept: 0.0000
P-value for Calibrated_Tidal_Volume: 0.0000
P-value for Respiration_Rate_bpm: 0.0000

Regression Equation for Participant 38645 - Posture: Standing (Filtered for fitting only)
RSA0_msec = 176.5493 + (-121.1111 * Calibrated_Tidal_Volume) + (-2.3093 * Respiration_Rate_bpm)
P-value for Intercept: 0.0000
P-value for Calibrated_Tidal_Volume: 0.0140
P-value for Respiration_Rate_bpm: 0.0366

Regression Equation for Participant 44066 - Posture: Lying (Filtered for fitting only)
RSA0_msec = 181.9723 + (-160.2337 * Calibrated_Tidal_Volume) + (-2.1003 * Respiration_Rate_bpm)
P-value for Intercept: 0.0004
P-value for Calibrated_Tidal_Volume: 0.0001
P-value for Respiration_Rate_bpm: 0.3718

Regression Equation for Participant 44066 - Posture: Sitting (Filtered for fitting only)
RSA0_msec = 125.0552 + (-18.6637 * Calibrated_Tidal_Volume) + (-3.1081 * Respiration_Rate_bpm)
P-value for Intercept: 0.0000
P-value for Calibrated_Tidal_Volume: 0.0073
P-value for Respiration_Rate_bpm: 0.0000

Regression Equation for Participant 44066 - Posture: Standing (Filtered for fitting only)
RSA0_msec = 158.2630 + (-79.6449 * Calibrated_Tidal_Volume) + (-4.0768 * Respiration_Rate_bpm)
P-value for Intercept: 0.0000
P-value for Calibrated_Tidal_Volume: 0.0000
P-value for Respiration_Rate_bpm: 0.0000

Regression Equation for Participant 46773 - Posture: Lying (Filtered for fitting only)
RSA0_msec = 168.8093 + (-85.4938 * Calibrated_Tidal_Volume) + (-2.6475 * Respiration_Rate_bpm)
P-value for Intercept: 0.0006
P-value for Calibrated_Tidal_Volume: 0.3342
P-value for Respiration_Rate_bpm: 0.0049

Regression Equation for Participant 46773 - Posture: Sitting (Filtered for fitting only)
RSA0_msec = 53.9571 + (-80.6839 * Calibrated_Tidal_Volume) + (1.6800 * Respiration_Rate_bpm)
P-value for Intercept: 0.0003
P-value for Calibrated_Tidal_Volume: 0.1049
P-value for Respiration_Rate_bpm: 0.0004

Regression Equation for Participant 46773 - Posture: Standing (Filtered for fitting only)
RSA0_msec = -14.1472 + (105.7422 * Calibrated_Tidal_Volume) + (-0.5680 * Respiration_Rate_bpm)
P-value for Intercept: 0.6433
P-value for Calibrated_Tidal_Volume: 0.0482
P-value for Respiration_Rate_bpm: 0.4192

Regression Equation for Participant 50129 - Posture: Lying (Filtered for fitting only)
RSA0_msec = 52.0316 + (-45.9744 * Calibrated_Tidal_Volume) + (-0.5717 * Respiration_Rate_bpm)
P-value for Intercept: 0.3115
P-value for Calibrated_Tidal_Volume: 0.6700
P-value for Respiration_Rate_bpm: 0.3388

Regression Equation for Participant 50129 - Posture: Sitting (Filtered for fitting only)
RSA0_msec = 74.6857 + (-10.4242 * Calibrated_Tidal_Volume) + (-2.0016 * Respiration_Rate_bpm)
P-value for Intercept: 0.0000
P-value for Calibrated_Tidal_Volume: 0.4735
P-value for Respiration_Rate_bpm: 0.0000

Regression Equation for Participant 50129 - Posture: Standing (Filtered for fitting only)
RSA0_msec = 85.7046 + (-38.5180 * Calibrated_Tidal_Volume) + (-2.3782 * Respiration_Rate_bpm)
P-value for Intercept: 0.0000
P-value for Calibrated_Tidal_Volume: 0.0019
P-value for Respiration_Rate_bpm: 0.0000

Skipping regression for Participant 54783 - Posture: Lying (Less than 20 data points after filtering)

Regression Equation for Participant 54783 - Posture: Sitting (Filtered for fitting only)
RSA0_msec = 388.3452 + (-211.2524 * Calibrated_Tidal_Volume) + (-5.3341 * Respiration_Rate_bpm)
P-value for Intercept: 0.0000
P-value for Calibrated_Tidal_Volume: 0.0000
P-value for Respiration_Rate_bpm: 0.0000

Regression Equation for Participant 54783 - Posture: Standing (Filtered for fitting only)
RSA0_msec = 206.9036 + (-186.1327 * Calibrated_Tidal_Volume) + (0.4952 * Respiration_Rate_bpm)
P-value for Intercept: 0.0912
P-value for Calibrated_Tidal_Volume: 0.1048
P-value for Respiration_Rate_bpm: 0.7385

Regression Equation for Participant 55110 - Posture: Lying (Filtered for fitting only)
RSA0_msec = 105.8892 + (142.9466 * Calibrated_Tidal_Volume) + (-4.6646 * Respiration_Rate_bpm)
P-value for Intercept: 0.0029
P-value for Calibrated_Tidal_Volume: 0.0010
P-value for Respiration_Rate_bpm: 0.0008

Regression Equation for Participant 55110 - Posture: Sitting (Filtered for fitting only)
RSA0_msec = 156.6794 + (66.4704 * Calibrated_Tidal_Volume) + (-6.5899 * Respiration_Rate_bpm)
P-value for Intercept: 0.0116
P-value for Calibrated_Tidal_Volume: 0.2849
P-value for Respiration_Rate_bpm: 0.0000

Regression Equation for Participant 55110 - Posture: Standing (Filtered for fitting only)
RSA0_msec = 230.0207 + (-56.5623 * Calibrated_Tidal_Volume) + (-6.1562 * Respiration_Rate_bpm)
P-value for Intercept: 0.0000
P-value for Calibrated_Tidal_Volume: 0.0018
P-value for Respiration_Rate_bpm: 0.0000

Regression Equation for Participant 56143 - Posture: Lying (Filtered for fitting only)
RSA0_msec = 113.9807 + (6.9525 * Calibrated_Tidal_Volume) + (-3.7251 * Respiration_Rate_bpm)
P-value for Intercept: 0.0000
P-value for Calibrated_Tidal_Volume: 0.6832
P-value for Respiration_Rate_bpm: 0.0000

Regression Equation for Participant 56143 - Posture: Sitting (Filtered for fitting only)
RSA0_msec = 192.4001 + (-45.0651 * Calibrated_Tidal_Volume) + (-6.2807 * Respiration_Rate_bpm)
P-value for Intercept: 0.0000
P-value for Calibrated_Tidal_Volume: 0.0000
P-value for Respiration_Rate_bpm: 0.0000

Regression Equation for Participant 56143 - Posture: Standing (Filtered for fitting only)
RSA0_msec = 133.8111 + (3.2830 * Calibrated_Tidal_Volume) + (-5.4839 * Respiration_Rate_bpm)
P-value for Intercept: 0.0000
P-value for Calibrated_Tidal_Volume: 0.6784
P-value for Respiration_Rate_bpm: 0.0000

Regression Equation for Participant 57458 - Posture: Lying (Filtered for fitting only)
RSA0_msec = 207.6320 + (-130.6878 * Calibrated_Tidal_Volume) + (-4.2012 * Respiration_Rate_bpm)
P-value for Intercept: 0.0000
P-value for Calibrated_Tidal_Volume: 0.0145
P-value for Respiration_Rate_bpm: 0.0000

Regression Equation for Participant 57458 - Posture: Sitting (Filtered for fitting only)
RSA0_msec = 111.9102 + (-5.4265 * Calibrated_Tidal_Volume) + (-3.5821 * Respiration_Rate_bpm)
P-value for Intercept: 0.0000
P-value for Calibrated_Tidal_Volume: 0.0357
P-value for Respiration_Rate_bpm: 0.0000

Regression Equation for Participant 57458 - Posture: Standing (Filtered for fitting only)
RSA0_msec = 114.1025 + (-10.5735 * Calibrated_Tidal_Volume) + (-4.1340 * Respiration_Rate_bpm)
P-value for Intercept: 0.0000
P-value for Calibrated_Tidal_Volume: 0.1693
P-value for Respiration_Rate_bpm: 0.0000

Regression Equation for Participant 58996 - Posture: Lying (Filtered for fitting only)

,participant_id,Majority_postures,RSA0_msec,RSA0_residual_45,Calibrated_Tidal_Volume,Respiration_Rate_bpm
0,12008,Standing,12.142857,-5.397732,2.933965,16.185775
1,12008,Sitting,11.153846,-13.728331,1.706549,15.507188
2,12008,Standing,14.000000,-3.741045,2.811731,16.812479
3,12008,Standing,22.230769,3.019797,2.683670,14.958695
4,12008,Standing,19.636364,-1.349283,2.478718,13.143172

In [28]:
df_awake_ambulatory[['participant_id', 'Majority_postures', 'RSA0_msec', 'RSA0_residual_45', 'Calibrated_Tidal_Volume', 'Respiration_Rate_bpm']].tail()

,participant_id,Majority_postures,RSA0_msec,RSA0_residual_45,Calibrated_Tidal_Volume,Respiration_Rate_bpm
47333,99857,Sitting,23.777778,-14.560730,1.830138,20.531699
47334,99857,Sitting,16.809524,-19.179254,1.581758,21.471635
47335,99857,Sitting,21.523810,-11.714877,1.416549,22.684089
47336,99857,Sitting,24.133333,-16.028958,2.225654,19.983675
47337,99857,Sitting,28.375000,-18.168832,2.829555,17.367665

In [36]:
df_awake_ambulatory.iloc[5000] #checking the different column and values for a random row

Unnamed: 0                                                  6733
Location                                                     NaN
Physical_Exertion                                            NaN
Posture                                                      NaN
Social_Situation                                             NaN
Type_Of_Activity                                             NaN
Location_Code                                                NaN
Physical_Exertion_Code                                       NaN
Posture_Code                                                 NaN
Social_Situation_Code                                        NaN
Type_Of_Activity_Code                                        NaN
Subject_ID                                                 25879
Label_ID                                                     398
Start_Date                                            13-04-2024
Start_Time                                          11:27:08.500
End_Date                                              13-04-2024
End_Time                                            11:28:08.500
Label_Duration_s                                              60
Total_Motility_mg                                       32.32167
Average_IBI_msec                                      832.970588
Average_HR_bpm                                         72.457327
SDNN_msec                                              63.893795
Respiration_Rate_bpm                                   14.528877
Tidal_Volume_mOhm                                     613.484309
RMSSD_msec                                             44.378878
LF_ms                                                      -9999
RSA0_msec                                                  84.75
HF_ms                                                      -9999
PEP_msec                                                   -9999
LVET_msec                                                  -9999
TWave_amplitude_mV                                         -9999
Stroke_Volume_(Nederend_2017)_cc                           -9999
Minute_Volume_(Nederend_2017)_lmin                         -9999
Average_SCL_uS                                             -9999
nsSCRs_per_minute_ppm                                      -9999
Min_IBI_msec                                               704.0
Max_IBI_msec                                               943.0
RSA_msec                                                 127.125
Artefact_Free_ECG_percent                              98.451069
Artefact_Free_Respiration_percent                          100.0
Majority_postures                                        Sitting
participant_id                                             25879
day                                                            2
Experimental_Conditions                                  -9999.0
Experimental_Conditions_Code                             -9999.0
Artefact_Free_ECG_s                                          NaN
Calibrated_Tidal_Volume                                 0.536121
datetime                              2024-04-13 11:27:08.500000
Cleaned_Tidal_Volume                                    0.536121
RSA0_residual                                          21.611748
RSA0_residual_45                                       21.817066
Name: 5000, dtype: object

In [ ]:
#for the supine (lying) condition of the participants below, a regression line could not be calculated due to a lack of at least 20 data points
#the same is the case for both RSA0_residual and RSA0_residual_45
#13304
#24340
#34714
#54783
#66303
#74998
#82556
#only 7 participants do not have a regression for the supine condition - one could argue
#we should also run the supine posture's analyses for the remaining 35 individuals. However, note that although we could statistically calculate a 
#regression line for these 35 individuals, the data points (for x or y) do not have meaningful variation with only a handful
#of data points borderline above 20 data points per individual.

In [ ]:
#continue with adding RSA0/VT, then making the ambulatory baseline regressions (and adjusted RSA), and adding the lab baseline regression based metrics

In [37]:
df_awake_ambulatory["Ttot"] = 60/df_awake_ambulatory["Respiration_Rate_bpm"] #add the breathing period column using the respiration rate data
df_awake_ambulatory["RSA0_over_Vt"] = df_awake_ambulatory['RSA0_msec']/df_awake_ambulatory['Calibrated_Tidal_Volume'] #Approach 4 (tidal volume norm RSA)

In [38]:
df_awake_ambulatory[[
    "Respiration_Rate_bpm", 
    "Calibrated_Tidal_Volume", 
    "RSA0_msec", 
    "Ttot", 
    "RSA0_over_Vt"
]].head()

,Respiration_Rate_bpm,Calibrated_Tidal_Volume,RSA0_msec,Ttot,RSA0_over_Vt
0,16.185775,2.933965,12.142857,3.706959,4.138719
1,15.507188,1.706549,11.153846,3.869173,6.535906
2,16.812479,2.811731,14.000000,3.568778,4.979138
3,14.958695,2.683670,22.230769,4.011045,8.283720
4,13.143172,2.478718,19.636364,4.565108,7.921985

In [ ]:
# make a dataframe with the Standing data of participant 12008 to double check if the br is correct when done with the function
#checked, the following cell's function gives the same result
#df_standing_12008 = df_awake_ambulatory[
 #   (df_awake_ambulatory['participant_id'] == 12008) &
 #   (df_awake_ambulatory['Majority_postures'] == 'Standing')
#]

#print(df_standing_12008)
#print(len(df_standing_12008))

#X = df_standing_12008['Ttot']
#y = df_standing_12008['RSA0_over_Vt']

# add intercept
#X = sm.add_constant(X)

# fitting the model
#model = sm.OLS(y, X).fit()

# print the model summary
#print(model.summary())

In [40]:
import statsmodels.api as sm
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# this is for Approach 2: making baseline regressions (RSA/Vt vs Ttot) using ambulatory data
#here, no outlier removal is conducted (in the next cell, we will re-do this, removing outliers in the y-axis that are 4.5/more sds away from the mean)

# folder to save plots
plot_folder = 'ambulatory_br_plots'
os.makedirs(plot_folder, exist_ok=True)

#defining list to store the regression coefficients
ambulatory_br_list = []

# function to make the ambulatory baseline regression (br)
def run_ambulatory_br_regression(group):
    if len(group) < 20: #check if at least 20 points are available
        print(f"Skipping regression for Participant {group['participant_id'].iloc[0]} - Posture: {group['Majority_postures'].iloc[0]} (Less than 20 points)\n")
        return

    X = sm.add_constant(group[['Ttot']]) #x variable and adding a constant to it
    y = group['RSA0_over_Vt'] #y axis

    model = sm.OLS(y, X).fit() #fitting the model for the participant-posture combination

    intercept = model.params['const']
    slope = model.params['Ttot']
    intercept_pval = model.pvalues['const']
    slope_pval = model.pvalues['Ttot']

    print(f"Regression for Participant {group['participant_id'].iloc[0]} - Posture: {group['Majority_postures'].iloc[0]}")
    print(f"RSA0_over_Vt = {intercept:.4f} + ({slope:.4f} * Ttot)")
    print(f"P-value for Intercept: {intercept_pval:.4f}")
    print(f"P-value for Ttot: {slope_pval:.4f}\n")

    # saving the participant_id, posture, as well as the associated intercept value, slope value, number of points used, and the p values to the
    #pre-defined list
    ambulatory_br_list.append({
        'participant_id': group['participant_id'].iloc[0],
        'posture': group['Majority_postures'].iloc[0],
        'intercept': intercept,
        'slope': slope,
        'intercept_pval': intercept_pval,
        'slope_pval': slope_pval,
        'n_points': len(group)
    })

    # plot
    plt.figure(figsize=(6, 4))
    plt.scatter(group['Ttot'], group['RSA0_over_Vt'], alpha=0.6, label='Data Points')
    x_vals = np.linspace(group['Ttot'].min(), group['Ttot'].max(), 100)
    y_vals = intercept + slope * x_vals
    plt.plot(x_vals, y_vals, color='red', label='Regression Line')
    plt.xlabel('Ttot')
    plt.ylabel('RSA0_over_Vt')
    plt.title(f"Participant {group['participant_id'].iloc[0]} - {group['Majority_postures'].iloc[0]}")
    plt.legend()
    plt.tight_layout()

    # saving the generated plot as a file and save under the folder
    filename = f"{group['participant_id'].iloc[0]}_{group['Majority_postures'].iloc[0].replace(' ', '_')}.png"
    plt.savefig(os.path.join(plot_folder, filename))
    plt.close()

# looping over all participant-posture groups
for (participant_id, posture), group in df_awake_ambulatory.groupby(['participant_id', 'Majority_postures']):
    run_ambulatory_br_regression(group)

# convert the list into a dataframe
ambulatory_br_df = pd.DataFrame(ambulatory_br_list)
ambulatory_br_df.head()

#save the coefficients as an excel
ambulatory_br_df.to_excel("ambulatory_br_df.xlsx")

Regression for Participant 12008 - Posture: Lying
RSA0_over_Vt = 38.7635 + (-2.6556 * Ttot)
P-value for Intercept: 0.0000
P-value for Ttot: 0.1137

Regression for Participant 12008 - Posture: Sitting
RSA0_over_Vt = 14.4582 + (1.0403 * Ttot)
P-value for Intercept: 0.0000
P-value for Ttot: 0.0003

Regression for Participant 12008 - Posture: Standing
RSA0_over_Vt = -0.6066 + (1.7568 * Ttot)
P-value for Intercept: 0.5513
P-value for Ttot: 0.0000

Skipping regression for Participant 13304 - Posture: Lying (Less than 20 points)

Regression for Participant 13304 - Posture: Sitting
RSA0_over_Vt = 398.0578 + (-48.7893 * Ttot)
P-value for Intercept: 0.0000
P-value for Ttot: 0.0048

Regression for Participant 13304 - Posture: Standing
RSA0_over_Vt = 13.0335 + (12.6931 * Ttot)
P-value for Intercept: 0.6252
P-value for Ttot: 0.1260

Regression for Participant 15337 - Posture: Lying
RSA0_over_Vt = 242.1322 + (-30.4039 * Ttot)
P-value for Intercept: 0.0180
P-value for Ttot: 0.2479

Regression for Participant 15337 - Posture: Sitting
RSA0_over_Vt = 148.8907 + (2.1295 * Ttot)
P-value for Intercept: 0.0000
P-value for Ttot: 0.6887

Regression for Participant 15337 - Posture: Standing
RSA0_over_Vt = 47.1935 + (4.0063 * Ttot)
P-value for Intercept: 0.1240
P-value for Ttot: 0.5977

Skipping regression for Participant 24340 - Posture: Lying (Less than 20 points)

Regression for Participant 24340 - Posture: Sitting
RSA0_over_Vt = 4.5585 + (25.3318 * Ttot)
P-value for Intercept: 0.4894
P-value for Ttot: 0.0000

Regression for Participant 24340 - Posture: Standing
RSA0_over_Vt = 101.2131 + (-10.4057 * Ttot)
P-value for Intercept: 0.0000
P-value for Ttot: 0.0705

Regression for Participant 25201 - Posture: Lying
RSA0_over_Vt = -37.2355 + (86.7310 * Ttot)
P-value for Intercept: 0.7464
P-value for Ttot: 0.0143

Regression for Participant 25201 - Posture: Sitting
RSA0_over_Vt = 38.1707 + (35.5606 * Ttot)
P-value for Intercept: 0.0223
P-value for Ttot: 0.0000

Regression for Participant 25201 - Posture: Standing
RSA0_over_Vt = 57.8344 + (19.4760 * Ttot)
P-value for Intercept: 0.0005
P-value for Ttot: 0.0001

Regression for Participant 25879 - Posture: Lying
RSA0_over_Vt = 209.0744 + (-26.4638 * Ttot)
P-value for Intercept: 0.0045
P-value for Ttot: 0.2030

Regression for Participant 25879 - Posture: Sitting
RSA0_over_Vt = 96.2814 + (4.6643 * Ttot)
P-value for Intercept: 0.0000
P-value for Ttot: 0.0655

Regression for Participant 25879 - Posture: Standing
RSA0_over_Vt = 25.9687 + (13.6168 * Ttot)
P-value for Intercept: 0.0826
P-value for Ttot: 0.0009

Regression for Participant 28327 - Posture: Lying
RSA0_over_Vt = 475.8022 + (-98.8626 * Ttot)
P-value for Intercept: 0.0001
P-value for Ttot: 0.0088

Regression for Participant 28327 - Posture: Sitting
RSA0_over_Vt = 43.5501 + (4.1218 * Ttot)
P-value for Intercept: 0.0000
P-value for Ttot: 0.0174

Regression for Participant 28327 - Posture: Standing
RSA0_over_Vt = 12.5817 + (1.3601 * Ttot)
P-value for Intercept: 0.0736
P-value for Ttot: 0.5034

Regression for Participant 28404 - Posture: Lying
RSA0_over_Vt = 320.1793 + (-22.3577 * Ttot)
P-value for Intercept: 0.2456
P-value for Ttot: 0.7750

Regression for Participant 28404 - Posture: Sitting
RSA0_over_Vt = 2.4854 + (25.7536 * Ttot)
P-value for Intercept: 0.8392
P-value for Ttot: 0.0000

Regression for Participant 28404 - Posture: Standing
RSA0_over_Vt = 3.2089 + (15.6564 * Ttot)
P-value for Intercept: 0.8326
P-value for Ttot: 0.0002

Regression for Participant 30739 - Posture: Lying
RSA0_over_Vt = 250.7260 + (27.0824 * Ttot)
P-value for Intercept: 0.0134
P-value for Ttot: 0.3667

Regression for Participant 30739 - Posture: Sitting
RSA0_over_Vt = 116.0046 + (-4.5228 * Ttot)
P-value for Intercept: 0.0000
P-value for Ttot: 0.2181

Regression for Participant 30739 - Posture: Standing
RSA0_over_Vt = 64.4054 + (-0.6780 * Ttot)
P-value for Intercept: 0.0000
P-value for Ttot: 0.8666

Regression for Participant 33280 - Posture: Lying
RSA0_over_Vt = 308.7437 + (-34.2371 * Ttot)
P-value for Intercept: 0.0681
P-value for Ttot: 0.4926

Regression for Participant 33280 - Posture: Sitting
RSA0_over_Vt = 128.3207 + (9.1295 * Ttot)
P-value for Intercept: 0.0000
P-value for Ttot: 0.0727

Regression for Participant 33280 - Posture: Standing
RSA0_over_Vt = -12.7013 + (16.7772 * Ttot)
P-value for Intercept: 0.2364
P-value for Ttot: 0.0000

Skipping regression for Participant 34714 - Posture: Lying (Less than 20 points)

Regression for Participant 34714 - Posture: Sitting
RSA0_over_Vt = -23.3226 + (24.4234 * Ttot)
P-value for Intercept: 0.0000
P-value for Ttot: 0.0000

Regression for Participant 34714 - Posture: Standing
RSA0_over_Vt = -16.5683 + (13.0399 * Ttot)
P-value for Intercept: 0.0046
P-value for Ttot: 0.0000

Regression for Participant 34763 - Posture: Lying
RSA0_over_Vt = -403.6213 + (169.6755 * Ttot)
P-value for Intercept: 0.0000
P-value for Ttot: 0.0000

Regression for Participant 34763 - Posture: Sitting
RSA0_over_Vt = 150.3893 + (6.2645 * Ttot)
P-value for Intercept: 0.0000
P-value for Ttot: 0.4003

Regression for Participant 34763 - Posture: Standing
RSA0_over_Vt = -31.6143 + (34.7338 * Ttot)
P-value for Intercept: 0.0851
P-value for Ttot: 0.0000

Regression for Participant 37092 - Posture: Lying
RSA0_over_Vt = 85.3240 + (1.4070 * Ttot)
P-value for Intercept: 0.0000
P-value for Ttot: 0.7916

Regression for Participant 37092 - Posture: Sitting
RSA0_over_Vt = 115.0952 + (7.1814 * Ttot)
P-value for Intercept: 0.0000
P-value for Ttot: 0.0458

Regression for Participant 37092 - Posture: Standing
RSA0_over_Vt = -50.2792 + (33.0073 * Ttot)
P-value for Intercept: 0.0223
P-value for Ttot: 0.0000

Regression for Participant 37818 - Posture: Lying
RSA0_over_Vt = -67.9251 + (62.6972 * Ttot)
P-value for Intercept: 0.1903
P-value for Ttot: 0.0000

Regression for Participant 37818 - Posture: Sitting
RSA0_over_Vt = -13.1634 + (48.7912 * Ttot)
P-value for Intercept: 0.1884
P-value for Ttot: 0.0000

Regression for Participant 37818 - Posture: Standing
RSA0_over_Vt = 119.6737 + (16.4635 * Ttot)
P-value for Intercept: 0.0000
P-value for Ttot: 0.0011

Regression for Participant 38029 - Posture: Lying
RSA0_over_Vt = 85.1623 + (9.9896 * Ttot)
P-value for Intercept: 0.0113
P-value for Ttot: 0.3240

Regression for Participant 38029 - Posture: Sitting
RSA0_over_Vt = 81.2533 + (9.9960 * Ttot)
P-value for Intercept: 0.0000
P-value for Ttot: 0.0060

Regression for Participant 38029 - Posture: Standing
RSA0_over_Vt = 21.9666 + (11.7748 * Ttot)
P-value for Intercept: 0.0131
P-value for Ttot: 0.0000

Regression for Participant 38645 - Posture: Lying
RSA0_over_Vt = 3.0189 + (40.6681 * Ttot)
P-value for Intercept: 0.8869
P-value for Ttot: 0.0000

Regression for Participant 38645 - Posture: Sitting
RSA0_over_Vt = 164.5726 + (-0.6477 * Ttot)
P-value for Intercept: 0.0000
P-value for Ttot: 0.8681

Regression for Participant 38645 - Posture: Standing
RSA0_over_Vt = 164.1437 + (-10.5858 * Ttot)
P-value for Intercept: 0.0000
P-value for Ttot: 0.2147

Regression for Participant 44066 - Posture: Lying
RSA0_over_Vt = 489.0554 + (-66.2252 * Ttot)
P-value for Intercept: 0.0059
P-value for Ttot: 0.2042

Regression for Participant 44066 - Posture: Sitting
RSA0_over_Vt = 258.9467 + (-10.5314 * Ttot)
P-value for Intercept: 0.0000
P-value for Ttot: 0.3771

Regression for Participant 44066 - Posture: Standing
RSA0_over_Vt = 177.6929 + (-18.6689 * Ttot)
P-value for Intercept: 0.0000
P-value for Ttot: 0.0123

Regression for Participant 46773 - Posture: Lying
RSA0_over_Vt = 197.6891 + (8.2485 * Ttot)
P-value for Intercept: 0.0000
P-value for Ttot: 0.5380

Regression for Participant 46773 - Posture: Sitting
RSA0_over_Vt = 246.9235 + (-12.0617 * Ttot)
P-value for Intercept: 0.0000
P-value for Ttot: 0.1421

Regression for Participant 46773 - Posture: Standing
RSA0_over_Vt = 0.9239 + (14.3488 * Ttot)
P-value for Intercept: 0.9684
P-value for Ttot: 0.0150

Regression for Participant 50129 - Posture: Lying
RSA0_over_Vt = 49.3354 + (3.2594 * Ttot)
P-value for Intercept: 0.0217
P-value for Ttot: 0.7062

Regression for Participant 50129 - Posture: Sitting
RSA0_over_Vt = 18.0397 + (18.0618 * Ttot)
P-value for Intercept: 0.0000
P-value for Ttot: 0.0000

Regression for Participant 50129 - Posture: Standing
RSA0_over_Vt = 9.4783 + (13.2701 * Ttot)
P-value for Intercept: 0.3822
P-value for Ttot: 0.0000

Skipping regression for Participant 54783 - Posture: Lying (Less than 20 points)

Regression for Participant 54783 - Posture: Sitting
RSA0_over_Vt = 127.2927 + (-2.3863 * Ttot)
P-value for Intercept: 0.0000
P-value for Ttot: 0.4601

Regression for Participant 54783 - Posture: Standing
RSA0_over_Vt = 84.7232 + (-9.3309 * Ttot)
P-value for Intercept: 0.0002
P-value for Ttot: 0.0930

Regression for Participant 55110 - Posture: Lying
RSA0_over_Vt = -6.9789 + (62.3577 * Ttot)
P-value for Intercept: 0.9052
P-value for Ttot: 0.0005

Regression for Participant 55110 - Posture: Sitting
RSA0_over_Vt = -5.5040 + (35.2831 * Ttot)
P-value for Intercept: 0.7622
P-value for Ttot: 0.0000

Regression for Participant 55110 - Posture: Standing
RSA0_over_Vt = 53.2759 + (6.7769 * Ttot)
P-value for Intercept: 0.0010
P-value for Ttot: 0.1294

Regression for Participant 56143 - Posture: Lying
RSA0_over_Vt = 60.8272 + (24.8015 * Ttot)
P-value for Intercept: 0.1321
P-value for Ttot: 0.0173

Regression for Participant 56143 - Posture: Sitting
RSA0_over_Vt = 125.8840 + (8.2791 * Ttot)
P-value for Intercept: 0.0000
P-value for Ttot: 0.0174

Regression for Participant 56143 - Posture: Standing
RSA0_over_Vt = 5.3026 + (17.1249 * Ttot)
P-value for Intercept: 0.6812
P-value for Ttot: 0.0000

Regression for Participant 57458 - Posture: Lying
RSA0_over_Vt = 7.2298 + (41.6894 * Ttot)
P-value for Intercept: 0.8408
P-value for Ttot: 0.0001

Regression for Participant 57458 - Posture: Sitting
RSA0_over_Vt = 82.8684 + (0.4231 * Ttot)
P-value for Intercept: 0.0000
P-value for Ttot: 0.8509

Regression for Participant 57458 - Posture: Standing
RSA0_over_Vt = -12.9618 + (13.6541 * Ttot)
P-value for Intercept: 0.2308
P-value for Ttot: 0.0000

Regression for Participant 58996 - Posture: Lying
RSA0_over_Vt = 524.2485 + (-61.9251 * Ttot)
P-value for Intercept: 0.0795
P-value for Ttot: 0.4219

Regression for Participant 58996 - Posture: Sitting
RSA0_over_Vt = -3.1744 + (14.1822 * Ttot)
P-value for Intercept: 0.3011
P-value for Ttot: 0.0000

Regression for Participant 58996 - Posture: Standing
RSA0_over_Vt = -0.1943 + (13.4318 * Ttot)
P-value for Intercept: 0.9899
P-value for Ttot: 0.0017

Regression for Participant 61972 - Posture: Lying
RSA0_over_Vt = -12.8223 + (12.1879 * Ttot)
P-value for Intercept: 0.1557
P-value for Ttot: 0.0000

Regression for Participant 61972 - Posture: Sitting
RSA0_over_Vt = -38.8410 + (17.1029 * Ttot)
P-value for Intercept: 0.0000
P-value for Ttot: 0.0000

Regression for Participant 61972 - Posture: Standing
RSA0_over_Vt = -6.9963 + (6.2286 * Ttot)
P-value for Intercept: 0.0736
P-value for Ttot: 0.0000

Regression for Participant 65919 - Posture: Lying
RSA0_over_Vt = 4.3612 + (3.6823 * Ttot)
P-value for Intercept: 0.7466
P-value for Ttot: 0.3039

Regression for Participant 65919 - Posture: Sitting
RSA0_over_Vt = -15.1642 + (20.0211 * Ttot)
P-value for Intercept: 0.0895
P-value for Ttot: 0.0000

Regression for Participant 65919 - Posture: Standing
RSA0_over_Vt = -32.4378 + (17.2758 * Ttot)
P-value for Intercept: 0.0001
P-value for Ttot: 0.0000

Skipping regression for Participant 66303 - Posture: Lying (Less than 20 points)

Regression for Participant 66303 - Posture: Sitting
RSA0_over_Vt = 221.1692 + (-34.3421 * Ttot)
P-value for Intercept: 0.0000
P-value for Ttot: 0.0000

Regression for Participant 66303 - Posture: Standing
RSA0_over_Vt = 65.8189 + (-6.7213 * Ttot)
P-value for Intercept: 0.0000
P-value for Ttot: 0.0004

Regression for Participant 68416 - Posture: Lying
RSA0_over_Vt = 406.0940 + (-88.6407 * Ttot)
P-value for Intercept: 0.0000
P-value for Ttot: 0.0000

Regression for Participant 68416 - Posture: Sitting
RSA0_over_Vt = 349.6756 + (-55.1584 * Ttot)
P-value for Intercept: 0.0000
P-value for Ttot: 0.0000

Regression for Participant 68416 - Posture: Standing
RSA0_over_Vt = 10.9636 + (12.2650 * Ttot)
P-value for Intercept: 0.1346
P-value for Ttot: 0.0000

Regression for Participant 72950 - Posture: Lying
RSA0_over_Vt = -149.5222 + (104.4453 * Ttot)
P-value for Intercept: 0.0003
P-value for Ttot: 0.0000

Regression for Participant 72950 - Posture: Sitting
RSA0_over_Vt = -45.8531 + (51.6818 * Ttot)
P-value for Intercept: 0.0151
P-value for Ttot: 0.0000

Regression for Participant 72950 - Posture: Standing
RSA0_over_Vt = -137.8284 + (74.5565 * Ttot)
P-value for Intercept: 0.0001
P-value for Ttot: 0.0000

Skipping regression for Participant 74998 - Posture: Lying (Less than 20 points)

Regression for Participant 74998 - Posture: Sitting
RSA0_over_Vt = -55.2310 + (33.1865 * Ttot)
P-value for Intercept: 0.0000
P-value for Ttot: 0.0000

Regression for Participant 74998 - Posture: Standing
RSA0_over_Vt = 11.2198 + (7.9661 * Ttot)
P-value for Intercept: 0.0678
P-value for Ttot: 0.0000

Regression for Participant 75967 - Posture: Lying
RSA0_over_Vt = -162.6703 + (82.9326 * Ttot)
P-value for Intercept: 0.1837
P-value for Ttot: 0.0168

Regression for Participant 75967 - Posture: Sitting
RSA0_over_Vt = 26.1466 + (45.2150 * Ttot)
P-value for Intercept: 0.1729
P-value for Ttot: 0.0000

Regression for Participant 75967 - Posture: Standing
RSA0_over_Vt = 16.7921 + (19.5026 * Ttot)
P-value for Intercept: 0.3897
P-value for Ttot: 0.0005

Regression for Participant 78692 - Posture: Lying
RSA0_over_Vt = 194.5991 + (-13.2593 * Ttot)
P-value for Intercept: 0.0548
P-value for Ttot: 0.5776

Regression for Participant 78692 - Posture: Sitting
RSA0_over_Vt = 105.4110 + (1.7746 * Ttot)
P-value for Intercept: 0.0000
P-value for Ttot: 0.6291

Regression for Participant 78692 - Posture: Standing
RSA0_over_Vt = 0.0750 + (21.6149 * Ttot)
P-value for Intercept: 0.9976
P-value for Ttot: 0.0013

Regression for Participant 81981 - Posture: Lying
RSA0_over_Vt = 183.0005 + (26.9592 * Ttot)
P-value for Intercept: 0.0009
P-value for Ttot: 0.1857

Regression for Participant 81981 - Posture: Sitting
RSA0_over_Vt = 244.3595 + (-23.6065 * Ttot)
P-value for Intercept: 0.0000
P-value for Ttot: 0.0001

Regression for Participant 81981 - Posture: Standing
RSA0_over_Vt = 152.8121 + (-19.1003 * Ttot)
P-value for Intercept: 0.0000
P-value for Ttot: 0.0068

Skipping regression for Participant 82556 - Posture: Lying (Less than 20 points)

Regression for Participant 82556 - Posture: Sitting
RSA0_over_Vt = -1.8523 + (7.4693 * Ttot)
P-value for Intercept: 0.6074
P-value for Ttot: 0.0000

Regression for Participant 82556 - Posture: Standing
RSA0_over_Vt = 2.3028 + (8.5860 * Ttot)
P-value for Intercept: 0.6765
P-value for Ttot: 0.0000

Regression for Participant 84645 - Posture: Lying
RSA0_over_Vt = 609.7052 + (-66.1258 * Ttot)
P-value for Intercept: 0.0000
P-value for Ttot: 0.0660

Regression for Participant 84645 - Posture: Sitting
RSA0_over_Vt = 897.5380 + (-155.7046 * Ttot)
P-value for Intercept: 0.0000
P-value for Ttot: 0.0000

Regression for Participant 84645 - Posture: Standing
RSA0_over_Vt = 143.2377 + (-3.4449 * Ttot)
P-value for Intercept: 0.0000
P-value for Ttot: 0.7272

Regression for Participant 88137 - Posture: Lying
RSA0_over_Vt = -182.2894 + (136.7006 * Ttot)
P-value for Intercept: 0.0099
P-value for Ttot: 0.0000

Regression for Participant 88137 - Posture: Sitting
RSA0_over_Vt = 105.8845 + (-6.1583 * Ttot)
P-value for Intercept: 0.0000
P-value for Ttot: 0.0404

Regression for Participant 88137 - Posture: Standing
RSA0_over_Vt = 3.4898 + (10.9475 * Ttot)
P-value for Intercept: 0.6478
P-value for Ttot: 0.0000

Regression for Participant 91169 - Posture: Lying
RSA0_over_Vt = 4.2892 + (1.8830 * Ttot)
P-value for Intercept: 0.7680
P-value for Ttot: 0.6117

Regression for Participant 91169 - Posture: Sitting
RSA0_over_Vt = 2.9770 + (12.1717 * Ttot)
P-value for Intercept: 0.6318
P-value for Ttot: 0.0000

Regression for Participant 91169 - Posture: Standing
RSA0_over_Vt = 84.5497 + (-11.8061 * Ttot)
P-value for Intercept: 0.0000
P-value for Ttot: 0.0118

Regression for Participant 91850 - Posture: Lying
RSA0_over_Vt = 134.7536 + (0.3375 * Ttot)
P-value for Intercept: 0.0148
P-value for Ttot: 0.9832

Regression for Participant 91850 - Posture: Sitting
RSA0_over_Vt = 52.2562 + (3.7007 * Ttot)
P-value for Intercept: 0.0000
P-value for Ttot: 0.1206

Regression for Participant 91850 - Posture: Standing
RSA0_over_Vt = 57.6409 + (-1.6207 * Ttot)
P-value for Intercept: 0.0008
P-value for Ttot: 0.7502

Regression for Participant 92674 - Posture: Lying
RSA0_over_Vt = -68.4737 + (106.8301 * Ttot)
P-value for Intercept: 0.2011
P-value for Ttot: 0.0000

Regression for Participant 92674 - Posture: Sitting
RSA0_over_Vt = 254.7821 + (-21.1665 * Ttot)
P-value for Intercept: 0.0000
P-value for Ttot: 0.0000

Regression for Participant 92674 - Posture: Standing
RSA0_over_Vt = 144.2580 + (-3.1337 * Ttot)
P-value for Intercept: 0.0000
P-value for Ttot: 0.6964

Regression for Participant 92957 - Posture: Lying
RSA0_over_Vt = -2.6178 + (27.9315 * Ttot)
P-value for Intercept: 0.9533
P-value for Ttot: 0.0512

Regression for Participant 92957 - Posture: Sitting
RSA0_over_Vt = -113.6806 + (85.3393 * Ttot)
P-value for Intercept: 0.0000
P-value for Ttot: 0.0000

Regression for Participant 92957 - Posture: Standing
RSA0_over_Vt = -57.4346 + (45.2010 * Ttot)
P-value for Intercept: 0.0000
P-value for Ttot: 0.0000

Regression for Participant 93676 - Posture: Lying
RSA0_over_Vt = -67.8738 + (40.1079 * Ttot)
P-value for Intercept: 0.5212
P-value for Ttot: 0.1771

Regression for Participant 93676 - Posture: Sitting
RSA0_over_Vt = 144.8206 + (-4.0778 * Ttot)
P-value for Intercept: 0.0000
P-value for Ttot: 0.4440

Regression for Participant 93676 - Posture: Standing
RSA0_over_Vt = 62.0146 + (0.3937 * Ttot)
P-value for Intercept: 0.0039
P-value for Ttot: 0.9439

Regression for Participant 99857 - Posture: Lying
RSA0_over_Vt = -6.0648 + (12.2613 * Ttot)
P-value for Intercept: 0.5842
P-value for Ttot: 0.0013

Regression for Participant 99857 - Posture: Sitting
RSA0_over_Vt = 24.9386 + (0.9459 * Ttot)
P-value for Intercept: 0.0000
P-value for Ttot: 0.3030

Regression for Participant 99857 - Posture: Standing
RSA0_over_Vt = 3.9075 + (4.4231 * Ttot)
P-value for Intercept: 0.4735
P-value for Ttot: 0.0070

In [41]:
# this is for Approach 2: making baseline regressions (RSA/Vt vs Ttot) using ambulatory data
#here, outlier removal is conducted, we are removing outliers in the y-axis that are 4.5/more sds away from the mean, after this check if there are
#at least 20 points remaining

import statsmodels.api as sm
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import os

# folder to save the RSA0/Vt vs Ttot plots that will be generated following outlier removal over the y axis
plot_folder_45 = 'ambulatory_br_plots_4_5sd'
os.makedirs(plot_folder_45, exist_ok=True)

# to store the regression coefficients
ambulatory_br_45_list = []

# function to get the ambulatory baseline regressions following outlier removal
def run_ambulatory_br_45(group):
    # for each "group" (i.e., the group of data for a given posture for a given participant)
    mean_val = group['RSA0_over_Vt'].mean()
    std_val = group['RSA0_over_Vt'].std()
    group_filtered = group[np.abs(group['RSA0_over_Vt'] - mean_val) < 4.5 * std_val]

    if len(group_filtered) < 20:  #after the filtering, check whether a minimum of 20 points are still remaining for the "group"
        print(f"Skipping regression for Participant {group['participant_id'].iloc[0]} - Posture: {group['Majority_postures'].iloc[0]} (Less than 20 points after 4.5 SD filtering)\n")
        return

    X = sm.add_constant(group_filtered[['Ttot']])
    y = group_filtered['RSA0_over_Vt']
    model = sm.OLS(y, X).fit() #fitting the model

    intercept = model.params['const']
    slope = model.params['Ttot']
    intercept_pval = model.pvalues['const']
    slope_pval = model.pvalues['Ttot']

    print(f"Filtered (4.5 SD) Regression for Participant {group['participant_id'].iloc[0]} - Posture: {group['Majority_postures'].iloc[0]}")
    print(f"RSA0_over_Vt = {intercept:.4f} + ({slope:.4f} * Ttot)")
    print(f"P-value for Intercept: {intercept_pval:.4f}")
    print(f"P-value for Ttot: {slope_pval:.4f}\n")

    ambulatory_br_45_list.append({
        'participant_id': group['participant_id'].iloc[0],
        'posture': group['Majority_postures'].iloc[0],
        'intercept': intercept,
        'slope': slope,
        'intercept_pval': intercept_pval,
        'slope_pval': slope_pval,
        'n_points': len(group_filtered)
    })

    # plot
    plt.figure(figsize=(6, 4))
    plt.scatter(group_filtered['Ttot'], group_filtered['RSA0_over_Vt'], alpha=0.6, label='Filtered Data')
    x_vals = np.linspace(group_filtered['Ttot'].min(), group_filtered['Ttot'].max(), 100)
    y_vals = intercept + slope * x_vals
    plt.plot(x_vals, y_vals, color='red', label='Regression Line')
    plt.xlabel('Ttot')
    plt.ylabel('RSA0_over_Vt')
    plt.title(f"Participant {group['participant_id'].iloc[0]} - {group['Majority_postures'].iloc[0]} (Filtered 4.5 SD)")
    plt.legend()
    plt.tight_layout()

    filename = f"{group['participant_id'].iloc[0]}_{group['Majority_postures'].iloc[0].replace(' ', '_')}_filtered.png"
    plt.savefig(os.path.join(plot_folder_45, filename))
    plt.close()

# looping over each "group" (i.e., participant-posture combination) and implementing the function to do outlier removall, calculating br, plotting
for (participant_id, posture), group in df_awake_ambulatory.groupby(['participant_id', 'Majority_postures']):
    run_ambulatory_br_45(group)

# convert the list with the participant id, posture, regression coefficients into a dataframe
ambulatory_br_45 = pd.DataFrame(ambulatory_br_45_list)

ambulatory_br_45.head()

#save the coefficients as an excel
ambulatory_br_45.to_excel("ambulatory_br_45.xlsx")

Filtered (4.5 SD) Regression for Participant 12008 - Posture: Lying
RSA0_over_Vt = 38.7635 + (-2.6556 * Ttot)
P-value for Intercept: 0.0000
P-value for Ttot: 0.1137

Filtered (4.5 SD) Regression for Participant 12008 - Posture: Sitting
RSA0_over_Vt = 14.6187 + (0.9817 * Ttot)
P-value for Intercept: 0.0000
P-value for Ttot: 0.0004

Filtered (4.5 SD) Regression for Participant 12008 - Posture: Standing
RSA0_over_Vt = 0.7422 + (1.4003 * Ttot)
P-value for Intercept: 0.4296
P-value for Ttot: 0.0000

Skipping regression for Participant 13304 - Posture: Lying (Less than 20 points after 4.5 SD filtering)

Filtered (4.5 SD) Regression for Participant 13304 - Posture: Sitting
RSA0_over_Vt = 398.0578 + (-48.7893 * Ttot)
P-value for Intercept: 0.0000
P-value for Ttot: 0.0048

Filtered (4.5 SD) Regression for Participant 13304 - Posture: Standing
RSA0_over_Vt = 13.0335 + (12.6931 * Ttot)
P-value for Intercept: 0.6252
P-value for Ttot: 0.1260

Filtered (4.5 SD) Regression for Participant 15337 - Posture: Lying
RSA0_over_Vt = 242.1322 + (-30.4039 * Ttot)
P-value for Intercept: 0.0180
P-value for Ttot: 0.2479

Filtered (4.5 SD) Regression for Participant 15337 - Posture: Sitting
RSA0_over_Vt = 148.8907 + (2.1295 * Ttot)
P-value for Intercept: 0.0000
P-value for Ttot: 0.6887

Filtered (4.5 SD) Regression for Participant 15337 - Posture: Standing
RSA0_over_Vt = 45.8074 + (3.6221 * Ttot)
P-value for Intercept: 0.0615
P-value for Ttot: 0.5496

Skipping regression for Participant 24340 - Posture: Lying (Less than 20 points after 4.5 SD filtering)

Filtered (4.5 SD) Regression for Participant 24340 - Posture: Sitting
RSA0_over_Vt = 7.7077 + (24.1485 * Ttot)
P-value for Intercept: 0.2294
P-value for Ttot: 0.0000

Filtered (4.5 SD) Regression for Participant 24340 - Posture: Standing
RSA0_over_Vt = 95.8828 + (-9.1131 * Ttot)
P-value for Intercept: 0.0000
P-value for Ttot: 0.0877

Filtered (4.5 SD) Regression for Participant 25201 - Posture: Lying
RSA0_over_Vt = -37.2355 + (86.7310 * Ttot)
P-value for Intercept: 0.7464
P-value for Ttot: 0.0143

Filtered (4.5 SD) Regression for Participant 25201 - Posture: Sitting
RSA0_over_Vt = 38.1707 + (35.5606 * Ttot)
P-value for Intercept: 0.0223
P-value for Ttot: 0.0000

Filtered (4.5 SD) Regression for Participant 25201 - Posture: Standing
RSA0_over_Vt = 57.8344 + (19.4760 * Ttot)
P-value for Intercept: 0.0005
P-value for Ttot: 0.0001

Filtered (4.5 SD) Regression for Participant 25879 - Posture: Lying
RSA0_over_Vt = 209.0744 + (-26.4638 * Ttot)
P-value for Intercept: 0.0045
P-value for Ttot: 0.2030

Filtered (4.5 SD) Regression for Participant 25879 - Posture: Sitting
RSA0_over_Vt = 95.6741 + (4.7763 * Ttot)
P-value for Intercept: 0.0000
P-value for Ttot: 0.0563

Filtered (4.5 SD) Regression for Participant 25879 - Posture: Standing
RSA0_over_Vt = 25.9687 + (13.6168 * Ttot)
P-value for Intercept: 0.0826
P-value for Ttot: 0.0009

Filtered (4.5 SD) Regression for Participant 28327 - Posture: Lying
RSA0_over_Vt = 475.8022 + (-98.8626 * Ttot)
P-value for Intercept: 0.0001
P-value for Ttot: 0.0088

Filtered (4.5 SD) Regression for Participant 28327 - Posture: Sitting
RSA0_over_Vt = 42.8365 + (4.2993 * Ttot)
P-value for Intercept: 0.0000
P-value for Ttot: 0.0122

Filtered (4.5 SD) Regression for Participant 28327 - Posture: Standing
RSA0_over_Vt = 12.5817 + (1.3601 * Ttot)
P-value for Intercept: 0.0736
P-value for Ttot: 0.5034

Filtered (4.5 SD) Regression for Participant 28404 - Posture: Lying
RSA0_over_Vt = 320.1793 + (-22.3577 * Ttot)
P-value for Intercept: 0.2456
P-value for Ttot: 0.7750

Filtered (4.5 SD) Regression for Participant 28404 - Posture: Sitting
RSA0_over_Vt = 1.0768 + (26.0625 * Ttot)
P-value for Intercept: 0.9291
P-value for Ttot: 0.0000

Filtered (4.5 SD) Regression for Participant 28404 - Posture: Standing
RSA0_over_Vt = 4.3787 + (15.0877 * Ttot)
P-value for Intercept: 0.7466
P-value for Ttot: 0.0001

Filtered (4.5 SD) Regression for Participant 30739 - Posture: Lying
RSA0_over_Vt = 250.7260 + (27.0824 * Ttot)
P-value for Intercept: 0.0134
P-value for Ttot: 0.3667

Filtered (4.5 SD) Regression for Participant 30739 - Posture: Sitting
RSA0_over_Vt = 116.0046 + (-4.5228 * Ttot)
P-value for Intercept: 0.0000
P-value for Ttot: 0.2181

Filtered (4.5 SD) Regression for Participant 30739 - Posture: Standing
RSA0_over_Vt = 59.7436 + (0.4531 * Ttot)
P-value for Intercept: 0.0000
P-value for Ttot: 0.9036

Filtered (4.5 SD) Regression for Participant 33280 - Posture: Lying
RSA0_over_Vt = 308.7437 + (-34.2371 * Ttot)
P-value for Intercept: 0.0681
P-value for Ttot: 0.4926

Filtered (4.5 SD) Regression for Participant 33280 - Posture: Sitting
RSA0_over_Vt = 125.3733 + (9.7267 * Ttot)
P-value for Intercept: 0.0000
P-value for Ttot: 0.0501

Filtered (4.5 SD) Regression for Participant 33280 - Posture: Standing
RSA0_over_Vt = -12.7013 + (16.7772 * Ttot)
P-value for Intercept: 0.2364
P-value for Ttot: 0.0000

Skipping regression for Participant 34714 - Posture: Lying (Less than 20 points after 4.5 SD filtering)

Filtered (4.5 SD) Regression for Participant 34714 - Posture: Sitting
RSA0_over_Vt = -23.3226 + (24.4234 * Ttot)
P-value for Intercept: 0.0000
P-value for Ttot: 0.0000

Filtered (4.5 SD) Regression for Participant 34714 - Posture: Standing
RSA0_over_Vt = -16.6684 + (12.9864 * Ttot)
P-value for Intercept: 0.0023
P-value for Ttot: 0.0000

Filtered (4.5 SD) Regression for Participant 34763 - Posture: Lying
RSA0_over_Vt = -403.6213 + (169.6755 * Ttot)
P-value for Intercept: 0.0000
P-value for Ttot: 0.0000

Filtered (4.5 SD) Regression for Participant 34763 - Posture: Sitting
RSA0_over_Vt = 150.3893 + (6.2645 * Ttot)
P-value for Intercept: 0.0000
P-value for Ttot: 0.4003

Filtered (4.5 SD) Regression for Participant 34763 - Posture: Standing
RSA0_over_Vt = -31.6143 + (34.7338 * Ttot)
P-value for Intercept: 0.0851
P-value for Ttot: 0.0000

Filtered (4.5 SD) Regression for Participant 37092 - Posture: Lying
RSA0_over_Vt = 85.3240 + (1.4070 * Ttot)
P-value for Intercept: 0.0000
P-value for Ttot: 0.7916

Filtered (4.5 SD) Regression for Participant 37092 - Posture: Sitting
RSA0_over_Vt = 113.4722 + (7.5371 * Ttot)
P-value for Intercept: 0.0000
P-value for Ttot: 0.0337

Filtered (4.5 SD) Regression for Participant 37092 - Posture: Standing
RSA0_over_Vt = -50.2792 + (33.0073 * Ttot)
P-value for Intercept: 0.0223
P-value for Ttot: 0.0000

Filtered (4.5 SD) Regression for Participant 37818 - Posture: Lying
RSA0_over_Vt = -67.9251 + (62.6972 * Ttot)
P-value for Intercept: 0.1903
P-value for Ttot: 0.0000

Filtered (4.5 SD) Regression for Participant 37818 - Posture: Sitting
RSA0_over_Vt = -0.1672 + (45.3805 * Ttot)
P-value for Intercept: 0.9873
P-value for Ttot: 0.0000

Filtered (4.5 SD) Regression for Participant 37818 - Posture: Standing
RSA0_over_Vt = 135.8827 + (11.9672 * Ttot)
P-value for Intercept: 0.0000
P-value for Ttot: 0.0157

Filtered (4.5 SD) Regression for Participant 38029 - Posture: Lying
RSA0_over_Vt = 85.1623 + (9.9896 * Ttot)
P-value for Intercept: 0.0113
P-value for Ttot: 0.3240

Filtered (4.5 SD) Regression for Participant 38029 - Posture: Sitting
RSA0_over_Vt = 81.2533 + (9.9960 * Ttot)
P-value for Intercept: 0.0000
P-value for Ttot: 0.0060

Filtered (4.5 SD) Regression for Participant 38029 - Posture: Standing
RSA0_over_Vt = 21.9666 + (11.7748 * Ttot)
P-value for Intercept: 0.0131
P-value for Ttot: 0.0000

Filtered (4.5 SD) Regression for Participant 38645 - Posture: Lying
RSA0_over_Vt = 0.8870 + (41.0378 * Ttot)
P-value for Intercept: 0.9651
P-value for Ttot: 0.0000

Filtered (4.5 SD) Regression for Participant 38645 - Posture: Sitting
RSA0_over_Vt = 164.5726 + (-0.6477 * Ttot)
P-value for Intercept: 0.0000
P-value for Ttot: 0.8681

Filtered (4.5 SD) Regression for Participant 38645 - Posture: Standing
RSA0_over_Vt = 164.1437 + (-10.5858 * Ttot)
P-value for Intercept: 0.0000
P-value for Ttot: 0.2147

Filtered (4.5 SD) Regression for Participant 44066 - Posture: Lying
RSA0_over_Vt = 489.0554 + (-66.2252 * Ttot)
P-value for Intercept: 0.0059
P-value for Ttot: 0.2042

Filtered (4.5 SD) Regression for Participant 44066 - Posture: Sitting
RSA0_over_Vt = 258.9467 + (-10.5314 * Ttot)
P-value for Intercept: 0.0000
P-value for Ttot: 0.3771

Filtered (4.5 SD) Regression for Participant 44066 - Posture: Standing
RSA0_over_Vt = 179.7996 + (-19.4897 * Ttot)
P-value for Intercept: 0.0000
P-value for Ttot: 0.0074

Filtered (4.5 SD) Regression for Participant 46773 - Posture: Lying
RSA0_over_Vt = 197.6891 + (8.2485 * Ttot)
P-value for Intercept: 0.0000
P-value for Ttot: 0.5380

Filtered (4.5 SD) Regression for Participant 46773 - Posture: Sitting
RSA0_over_Vt = 246.9235 + (-12.0617 * Ttot)
P-value for Intercept: 0.0000
P-value for Ttot: 0.1421

Filtered (4.5 SD) Regression for Participant 46773 - Posture: Standing
RSA0_over_Vt = 33.5159 + (5.7848 * Ttot)
P-value for Intercept: 0.1301
P-value for Ttot: 0.2977

Filtered (4.5 SD) Regression for Participant 50129 - Posture: Lying
RSA0_over_Vt = 49.3354 + (3.2594 * Ttot)
P-value for Intercept: 0.0217
P-value for Ttot: 0.7062

Filtered (4.5 SD) Regression for Participant 50129 - Posture: Sitting
RSA0_over_Vt = 18.0397 + (18.0618 * Ttot)
P-value for Intercept: 0.0000
P-value for Ttot: 0.0000

Filtered (4.5 SD) Regression for Participant 50129 - Posture: Standing
RSA0_over_Vt = 9.4783 + (13.2701 * Ttot)
P-value for Intercept: 0.3822
P-value for Ttot: 0.0000

Skipping regression for Participant 54783 - Posture: Lying (Less than 20 points after 4.5 SD filtering)

Filtered (4.5 SD) Regression for Participant 54783 - Posture: Sitting
RSA0_over_Vt = 127.2927 + (-2.3863 * Ttot)
P-value for Intercept: 0.0000
P-value for Ttot: 0.4601

Filtered (4.5 SD) Regression for Participant 54783 - Posture: Standing
RSA0_over_Vt = 84.7232 + (-9.3309 * Ttot)
P-value for Intercept: 0.0002
P-value for Ttot: 0.0930

Filtered (4.5 SD) Regression for Participant 55110 - Posture: Lying
RSA0_over_Vt = -6.9789 + (62.3577 * Ttot)
P-value for Intercept: 0.9052
P-value for Ttot: 0.0005

Filtered (4.5 SD) Regression for Participant 55110 - Posture: Sitting
RSA0_over_Vt = -5.5040 + (35.2831 * Ttot)
P-value for Intercept: 0.7622
P-value for Ttot: 0.0000

Filtered (4.5 SD) Regression for Participant 55110 - Posture: Standing
RSA0_over_Vt = 53.2759 + (6.7769 * Ttot)
P-value for Intercept: 0.0010
P-value for Ttot: 0.1294

Filtered (4.5 SD) Regression for Participant 56143 - Posture: Lying
RSA0_over_Vt = 60.8272 + (24.8015 * Ttot)
P-value for Intercept: 0.1321
P-value for Ttot: 0.0173

Filtered (4.5 SD) Regression for Participant 56143 - Posture: Sitting
RSA0_over_Vt = 125.8840 + (8.2791 * Ttot)
P-value for Intercept: 0.0000
P-value for Ttot: 0.0174

Filtered (4.5 SD) Regression for Participant 56143 - Posture: Standing
RSA0_over_Vt = 1.0869 + (18.0684 * Ttot)
P-value for Intercept: 0.9293
P-value for Ttot: 0.0000

Filtered (4.5 SD) Regression for Participant 57458 - Posture: Lying
RSA0_over_Vt = 7.2298 + (41.6894 * Ttot)
P-value for Intercept: 0.8408
P-value for Ttot: 0.0001

Filtered (4.5 SD) Regression for Participant 57458 - Posture: Sitting
RSA0_over_Vt = 82.8684 + (0.4231 * Ttot)
P-value for Intercept: 0.0000
P-value for Ttot: 0.8509

Filtered (4.5 SD) Regression for Participant 57458 - Posture: Standing
RSA0_over_Vt = -12.9618 + (13.6541 * Ttot)
P-value for Intercept: 0.2308
P-value for Ttot: 0.0000

Filtered (4.5 SD) Regression for Participant 58996 - Posture: Lying
RSA0_over_Vt = 524.2485 + (-61.9251 * Ttot)
P-value for Intercept: 0.0795
P-value for Ttot: 0.4219

Filtered (4.5 SD) Regression for Participant 58996 - Posture: Sitting
RSA0_over_Vt = -3.1744 + (14.1822 * Ttot)
P-value for Intercept: 0.3011
P-value for Ttot: 0.0000

Filtered (4.5 SD) Regression for Participant 58996 - Posture: Standing
RSA0_over_Vt = -0.1943 + (13.4318 * Ttot)
P-value for Intercept: 0.9899
P-value for Ttot: 0.0017

Filtered (4.5 SD) Regression for Participant 61972 - Posture: Lying
RSA0_over_Vt = -10.3730 + (11.3556 * Ttot)
P-value for Intercept: 0.1684
P-value for Ttot: 0.0000

Filtered (4.5 SD) Regression for Participant 61972 - Posture: Sitting
RSA0_over_Vt = -38.8410 + (17.1029 * Ttot)
P-value for Intercept: 0.0000
P-value for Ttot: 0.0000

Filtered (4.5 SD) Regression for Participant 61972 - Posture: Standing
RSA0_over_Vt = -6.9963 + (6.2286 * Ttot)
P-value for Intercept: 0.0736
P-value for Ttot: 0.0000

Filtered (4.5 SD) Regression for Participant 65919 - Posture: Lying
RSA0_over_Vt = 4.3612 + (3.6823 * Ttot)
P-value for Intercept: 0.7466
P-value for Ttot: 0.3039

Filtered (4.5 SD) Regression for Participant 65919 - Posture: Sitting
RSA0_over_Vt = -8.8184 + (18.3350 * Ttot)
P-value for Intercept: 0.3084
P-value for Ttot: 0.0000

Filtered (4.5 SD) Regression for Participant 65919 - Posture: Standing
RSA0_over_Vt = -32.4378 + (17.2758 * Ttot)
P-value for Intercept: 0.0001
P-value for Ttot: 0.0000

Skipping regression for Participant 66303 - Posture: Lying (Less than 20 points after 4.5 SD filtering)

Filtered (4.5 SD) Regression for Participant 66303 - Posture: Sitting
RSA0_over_Vt = 219.6006 + (-34.0201 * Ttot)
P-value for Intercept: 0.0000
P-value for Ttot: 0.0000

Filtered (4.5 SD) Regression for Participant 66303 - Posture: Standing
RSA0_over_Vt = 65.8189 + (-6.7213 * Ttot)
P-value for Intercept: 0.0000
P-value for Ttot: 0.0004

Filtered (4.5 SD) Regression for Participant 68416 - Posture: Lying
RSA0_over_Vt = 406.0940 + (-88.6407 * Ttot)
P-value for Intercept: 0.0000
P-value for Ttot: 0.0000

Filtered (4.5 SD) Regression for Participant 68416 - Posture: Sitting
RSA0_over_Vt = 346.2282 + (-54.3559 * Ttot)
P-value for Intercept: 0.0000
P-value for Ttot: 0.0000

Filtered (4.5 SD) Regression for Participant 68416 - Posture: Standing
RSA0_over_Vt = 10.9636 + (12.2650 * Ttot)
P-value for Intercept: 0.1346
P-value for Ttot: 0.0000

Filtered (4.5 SD) Regression for Participant 72950 - Posture: Lying
RSA0_over_Vt = -149.5222 + (104.4453 * Ttot)
P-value for Intercept: 0.0003
P-value for Ttot: 0.0000

Filtered (4.5 SD) Regression for Participant 72950 - Posture: Sitting
RSA0_over_Vt = -33.5078 + (47.7774 * Ttot)
P-value for Intercept: 0.0638
P-value for Ttot: 0.0000

Filtered (4.5 SD) Regression for Participant 72950 - Posture: Standing
RSA0_over_Vt = -137.8284 + (74.5565 * Ttot)
P-value for Intercept: 0.0001
P-value for Ttot: 0.0000

Skipping regression for Participant 74998 - Posture: Lying (Less than 20 points after 4.5 SD filtering)

Filtered (4.5 SD) Regression for Participant 74998 - Posture: Sitting
RSA0_over_Vt = -46.2558 + (30.6976 * Ttot)
P-value for Intercept: 0.0000
P-value for Ttot: 0.0000

Filtered (4.5 SD) Regression for Participant 74998 - Posture: Standing
RSA0_over_Vt = 13.7759 + (7.0726 * Ttot)
P-value for Intercept: 0.0165
P-value for Ttot: 0.0000

Filtered (4.5 SD) Regression for Participant 75967 - Posture: Lying
RSA0_over_Vt = -162.6703 + (82.9326 * Ttot)
P-value for Intercept: 0.1837
P-value for Ttot: 0.0168

Filtered (4.5 SD) Regression for Participant 75967 - Posture: Sitting
RSA0_over_Vt = 26.1466 + (45.2150 * Ttot)
P-value for Intercept: 0.1729
P-value for Ttot: 0.0000

Filtered (4.5 SD) Regression for Participant 75967 - Posture: Standing
RSA0_over_Vt = 16.7921 + (19.5026 * Ttot)
P-value for Intercept: 0.3897
P-value for Ttot: 0.0005

Filtered (4.5 SD) Regression for Participant 78692 - Posture: Lying
RSA0_over_Vt = 194.5991 + (-13.2593 * Ttot)
P-value for Intercept: 0.0548
P-value for Ttot: 0.5776

Filtered (4.5 SD) Regression for Participant 78692 - Posture: Sitting
RSA0_over_Vt = 100.0901 + (2.8264 * Ttot)
P-value for Intercept: 0.0000
P-value for Ttot: 0.4136

Filtered (4.5 SD) Regression for Participant 78692 - Posture: Standing
RSA0_over_Vt = 0.0750 + (21.6149 * Ttot)
P-value for Intercept: 0.9976
P-value for Ttot: 0.0013

Filtered (4.5 SD) Regression for Participant 81981 - Posture: Lying
RSA0_over_Vt = 183.0005 + (26.9592 * Ttot)
P-value for Intercept: 0.0009
P-value for Ttot: 0.1857

Filtered (4.5 SD) Regression for Participant 81981 - Posture: Sitting
RSA0_over_Vt = 244.3595 + (-23.6065 * Ttot)
P-value for Intercept: 0.0000
P-value for Ttot: 0.0001

Filtered (4.5 SD) Regression for Participant 81981 - Posture: Standing
RSA0_over_Vt = 134.4604 + (-14.4705 * Ttot)
P-value for Intercept: 0.0000
P-value for Ttot: 0.0157

Skipping regression for Participant 82556 - Posture: Lying (Less than 20 points after 4.5 SD filtering)

Filtered (4.5 SD) Regression for Participant 82556 - Posture: Sitting
RSA0_over_Vt = -0.6502 + (7.1549 * Ttot)
P-value for Intercept: 0.8550
P-value for Ttot: 0.0000

Filtered (4.5 SD) Regression for Participant 82556 - Posture: Standing
RSA0_over_Vt = 6.3399 + (7.4668 * Ttot)
P-value for Intercept: 0.2324
P-value for Ttot: 0.0000

Filtered (4.5 SD) Regression for Participant 84645 - Posture: Lying
RSA0_over_Vt = 609.7052 + (-66.1258 * Ttot)
P-value for Intercept: 0.0000
P-value for Ttot: 0.0660

Filtered (4.5 SD) Regression for Participant 84645 - Posture: Sitting
RSA0_over_Vt = 897.5380 + (-155.7046 * Ttot)
P-value for Intercept: 0.0000
P-value for Ttot: 0.0000

Filtered (4.5 SD) Regression for Participant 84645 - Posture: Standing
RSA0_over_Vt = 118.9981 + (3.7731 * Ttot)
P-value for Intercept: 0.0000
P-value for Ttot: 0.6677

Filtered (4.5 SD) Regression for Participant 88137 - Posture: Lying
RSA0_over_Vt = -180.8054 + (135.3228 * Ttot)
P-value for Intercept: 0.0075
P-value for Ttot: 0.0000

Filtered (4.5 SD) Regression for Participant 88137 - Posture: Sitting
RSA0_over_Vt = 106.0923 + (-6.3022 * Ttot)
P-value for Intercept: 0.0000
P-value for Ttot: 0.0321

Filtered (4.5 SD) Regression for Participant 88137 - Posture: Standing
RSA0_over_Vt = 4.3788 + (10.6219 * Ttot)
P-value for Intercept: 0.5462
P-value for Ttot: 0.0000

Filtered (4.5 SD) Regression for Participant 91169 - Posture: Lying
RSA0_over_Vt = 4.2892 + (1.8830 * Ttot)
P-value for Intercept: 0.7680
P-value for Ttot: 0.6117

Filtered (4.5 SD) Regression for Participant 91169 - Posture: Sitting
RSA0_over_Vt = 1.7952 + (12.3950 * Ttot)
P-value for Intercept: 0.7667
P-value for Ttot: 0.0000

Filtered (4.5 SD) Regression for Participant 91169 - Posture: Standing
RSA0_over_Vt = 84.9306 + (-12.4122 * Ttot)
P-value for Intercept: 0.0000
P-value for Ttot: 0.0025

Filtered (4.5 SD) Regression for Participant 91850 - Posture: Lying
RSA0_over_Vt = 134.7536 + (0.3375 * Ttot)
P-value for Intercept: 0.0148
P-value for Ttot: 0.9832

Filtered (4.5 SD) Regression for Participant 91850 - Posture: Sitting
RSA0_over_Vt = 52.2562 + (3.7007 * Ttot)
P-value for Intercept: 0.0000
P-value for Ttot: 0.1206

Filtered (4.5 SD) Regression for Participant 91850 - Posture: Standing
RSA0_over_Vt = 49.9751 + (0.3364 * Ttot)
P-value for Intercept: 0.0014
P-value for Ttot: 0.9425

Filtered (4.5 SD) Regression for Participant 92674 - Posture: Lying
RSA0_over_Vt = -68.4737 + (106.8301 * Ttot)
P-value for Intercept: 0.2011
P-value for Ttot: 0.0000

Filtered (4.5 SD) Regression for Participant 92674 - Posture: Sitting
RSA0_over_Vt = 254.7821 + (-21.1665 * Ttot)
P-value for Intercept: 0.0000
P-value for Ttot: 0.0000

Filtered (4.5 SD) Regression for Participant 92674 - Posture: Standing
RSA0_over_Vt = 144.2580 + (-3.1337 * Ttot)
P-value for Intercept: 0.0000
P-value for Ttot: 0.6964

Filtered (4.5 SD) Regression for Participant 92957 - Posture: Lying
RSA0_over_Vt = -2.6178 + (27.9315 * Ttot)
P-value for Intercept: 0.9533
P-value for Ttot: 0.0512

Filtered (4.5 SD) Regression for Participant 92957 - Posture: Sitting
RSA0_over_Vt = -113.6806 + (85.3393 * Ttot)
P-value for Intercept: 0.0000
P-value for Ttot: 0.0000

Filtered (4.5 SD) Regression for Participant 92957 - Posture: Standing
RSA0_over_Vt = -50.9785 + (43.2093 * Ttot)
P-value for Intercept: 0.0000
P-value for Ttot: 0.0000

Filtered (4.5 SD) Regression for Participant 93676 - Posture: Lying
RSA0_over_Vt = -67.8738 + (40.1079 * Ttot)
P-value for Intercept: 0.5212
P-value for Ttot: 0.1771

Filtered (4.5 SD) Regression for Participant 93676 - Posture: Sitting

In [42]:
#defining the function to calculate the delta RSA0/VT values using the ambulatory baseline regressions - Approach 2
#VERY IMPORTANT VARIABLE NAME CLARIFICATION: You will see that we named the ambulatory baseline regression cardiac vagal activity as
#delta_RSA0_over_Ttot_ambulatory or delta_RSA0_over_Ttot_ambulatory_45. This variable, as also explained and calculated below is
#delta RSA0/Vt. We simply named it as delta_RSA0_over_Ttot to avoid making mistakes in code as the different RSA variables have similar names and terms

def apply_residuals(df, regression_df, column_name):#df would be the actual physiological data, regression_df is the dataframe with ambulatory df values
    residuals = []                                   #column name is the new column that would be added to df for the newly calculated deltaRSA0/Vt

    for idx, row in df.iterrows():
        match = regression_df[ #match is selecting the row that is the same as the current df row's participant id and posture
            (regression_df['participant_id'] == row['participant_id']) &  # for the current row in the df, searching for the 
                                                                            # regression of that participant and posture
            (regression_df['posture'] == row['Majority_postures'])
        ]
        if not match.empty:
            intercept = match.iloc[0]['intercept']
            slope = match.iloc[0]['slope']
            predicted = intercept + slope * row['Ttot']   #calculate the predicted RSA0/Vt given the row's Ttot
            residual = row['RSA0_over_Vt'] - predicted   #subtract the observed from the predicted to get at the delta
        else:
            residual = np.nan
            
        residuals.append(residual)

    df[column_name] = residuals
    return df

# using the ambulatory baseline regressions, calculating deltaRSA0/Vt
df_awake_ambulatory = apply_residuals(df_awake_ambulatory, ambulatory_br_df, 'delta_RSA0_over_Ttot_ambulatory') #again, this is deltaRSA0/Vt

# using the ambulatory baseline regressions (while making the br points at or away 4.5sds from the mean were removed), calculating deltaRSA0/Vt
df_awake_ambulatory = apply_residuals(df_awake_ambulatory, ambulatory_br_45, 'delta_RSA0_over_Ttot_ambulatory_45') #again, this is deltaRSA0/Vt

In [33]:
#save to also manually check if the calculations worked
#df_awake_ambulatory.to_excel("df_after_ambulatory_approach2.xlsx")   
#manual check verified that it does work

In [43]:
#and now, calculating the deltaRSA0/Vt for Approach 1, using the laboratory baseline regressions calculated with the paced breathing data
import os
import pandas as pd
import numpy as np

# the directory where the laboratory calibration data is stored
base_path = r"C:\Users\msa583\OneDrive - Vrije Universiteit Amsterdam\Desktop\RSA Analyses Post-Processing\RQ2"

# mapping the postures in the dataframe to the names used in the lab calibration excels
posture_mapping = {
    'lying': 'supine',
    'sitting': 'sitting',
    'standing': 'standing'
}

# function for reading in the lab calibration files of participants and turning into pandas dataframe
def get_lab_coefficients(participant_id):
    file_path = os.path.join(base_path, f"lab_calibration_{participant_id}.xlsx") #this is how the individual files are titled
    if os.path.exists(file_path):
        return pd.read_excel(file_path) #making it a pandas dataframe
    else:
        print(f"File not found for Participant {participant_id}")
        return None

# function to calculate the deltaRSA0/Vt
def calculate_lab_delta_cached(df, suffix, column_name):
    deltas = []
    lab_cache = {}  # dictionary to store each participant's lab calibration dataframe (so we don't need to re-read the excel file for every row)

    for idx, row in df.iterrows():
        ppid = row['participant_id'] #extracting the participant id of the current row
        posture_raw = row['Majority_postures'].strip().lower() #extracting the posture of the current row
        posture = posture_mapping.get(posture_raw) #translate the posture name (relevant if converting from lying to supine)

        if posture is None:
            print(f"Unknown posture '{posture_raw}' for participant {ppid}")
            deltas.append(np.nan)
            continue

        # using the dictionary to avoid re-reading excel files for every row
        if ppid not in lab_cache:
            lab_cache[ppid] = get_lab_coefficients(ppid)

        lab_df = lab_cache[ppid]

        if lab_df is None:
            deltas.append(np.nan)
            continue

        try:   #the regressions are already calculated previously in the separate participant specific notebooks which is why we do not fit a model here
            slope_col = f'br_slope_{posture}{suffix}'
            intercept_col = f'br_intercept_{posture}{suffix}'

            slope = lab_df.at[0, slope_col]
            intercept = lab_df.at[0, intercept_col]

            predicted = intercept + slope * row['Ttot']
            delta = row['RSA0_over_Vt'] - predicted
            deltas.append(delta)
        except KeyError:
            print(f"Missing regression columns for posture '{posture}' (original: '{posture_raw}') in Participant {ppid}'s file")
            deltas.append(np.nan)

    df[column_name] = deltas
    return df

# apply the function to get the deltaRSA0/Vt
df_awake_ambulatory = calculate_lab_delta_cached(df_awake_ambulatory, '', 'delta_RSA0_over_Ttot_laboratory') #deltaRSA0/Vt calculated using lab br
df_awake_ambulatory = calculate_lab_delta_cached(df_awake_ambulatory, '_45', 'delta_RSA0_over_Ttot_laboratory_45') #calculated using lab br except for 4.5 SD deviant points
df_awake_ambulatory = calculate_lab_delta_cached(df_awake_ambulatory, '_3', 'delta_RSA0_over_Ttot_laboratory_3') #calculated using lab br except for 3 SD deviant points

In [44]:
# loading the descriptives (age, sex, BMI, smoking status, IPAQ will be used later in multilevel modeling)
descriptives_path = os.path.join(base_path, "Descriptives.xlsx")
df_descriptives = pd.read_excel(descriptives_path)

# merging the descriptives column onto df_awake_ambulatory based on the participant_id column
df_awake_ambulatory = df_awake_ambulatory.merge(df_descriptives, on='participant_id', how='left')

In [45]:
df_awake_ambulatory.to_excel("df_RSAmetrics_descriptives.xlsx") #the final dataframe with all the RSA metrics and descriptives, has all postures

In [46]:
df_awake_ambulatory = pd.read_excel("df_RSAmetrics_descriptives.xlsx")

In [47]:
# separating the main dataframe into three based on posture
final_df_lying = df_awake_ambulatory[df_awake_ambulatory['Majority_postures'].str.lower() == 'lying'].copy()
final_df_sitting = df_awake_ambulatory[df_awake_ambulatory['Majority_postures'].str.lower() == 'sitting'].copy()
final_df_standing = df_awake_ambulatory[df_awake_ambulatory['Majority_postures'].str.lower() == 'standing'].copy()

In [50]:
final_df_lying.columns.tolist()

['Unnamed: 0.1',
 'Unnamed: 0',
 'Location',
 'Physical_Exertion',
 'Posture',
 'Social_Situation',
 'Type_Of_Activity',
 'Location_Code',
 'Physical_Exertion_Code',
 'Posture_Code',
 'Social_Situation_Code',
 'Type_Of_Activity_Code',
 'Subject_ID',
 'Label_ID',
 'Start_Date',
 'Start_Time',
 'End_Date',
 'End_Time',
 'Label_Duration_s',
 'Total_Motility_mg',
 'Average_IBI_msec',
 'Average_HR_bpm',
 'SDNN_msec',
 'Respiration_Rate_bpm',
 'Tidal_Volume_mOhm',
 'RMSSD_msec',
 'LF_ms',
 'RSA0_msec',
 'HF_ms',
 'PEP_msec',
 'LVET_msec',
 'TWave_amplitude_mV',
 'Stroke_Volume_(Nederend_2017)_cc',
 'Minute_Volume_(Nederend_2017)_lmin',
 'Average_SCL_uS',
 'nsSCRs_per_minute_ppm',
 'Min_IBI_msec',
 'Max_IBI_msec',
 'RSA_msec',
 'Artefact_Free_ECG_percent',
 'Artefact_Free_Respiration_percent',
 'Majority_postures',
 'participant_id',
 'day',
 'Experimental_Conditions',
 'Experimental_Conditions_Code',
 'Artefact_Free_ECG_s',
 'Calibrated_Tidal_Volume',
 'datetime',
 'Cleaned_Tidal_Volume',
 'RSA0_residual',
 'RSA0_residual_45',
 'Ttot',
 'RSA0_over_Vt',
 'delta_RSA0_over_Ttot_ambulatory',
 'delta_RSA0_over_Ttot_ambulatory_45',
 'delta_RSA0_over_Ttot_laboratory',
 'delta_RSA0_over_Ttot_laboratory_45',
 'delta_RSA0_over_Ttot_laboratory_3',
 'Height',
 'Weight',
 'Sex',
 'Ethnicity',
 'Age',
 'BMI',
 'BMI_Category',
 'Education',
 'IPAQ_SF',
 'Current_Smoking']

# SEPARATING THE FINAL DATAFRAME FOR RQ2 INTO LYING, SITTING, AND STANDING DATAFRAMES FOR USE IN R

In [51]:
#save as excel files, from there on move to R
final_df_lying.to_excel("final_df_lying.xlsx", index=False)
final_df_sitting.to_excel("final_df_sitting.xlsx", index=False)
final_df_standing.to_excel("final_df_standing.xlsx", index=False)

# READING IN AND MERGING THE M-PATH (EMA) FILES, CALCULATING THE TOTAL MOMENTARY PERCEIVED STRESS, POSITIVE AFFECT, NEGATIVE AFFECT SCORES

In [58]:
import pandas as pd
import glob
import os

# defining the path where the ema excels are
base_path = r"C:\Users\msa583\OneDrive - Vrije Universiteit Amsterdam\Desktop\RSA Analyses Post-Processing\RQ2"

# finding the excel files that start with m-Path_
file_list = glob.glob(os.path.join(base_path, "m-Path_*.xlsx"))

# list to append the m_Path data
df_list = []

# loop through the files
for file_path in file_list:
    filename = os.path.basename(file_path)
    participant_id = filename.split("_")[1].split(".")[0]  # extract the participant id from the file name
    
    df = pd.read_excel(file_path)
    df['participant_id'] = participant_id  # add participant ID
    
    df_list.append(df)

# converting from a list to a concetenated dataframe
df_ema = pd.concat(df_list, ignore_index=True)

#commented the printout of the dataframe to conceal the sensitive daily life emotion data
#df_ema

In [59]:
df_ema["Tot_Stress"] = df_ema["PSS_1 (sliderNegPos)"] + df_ema["PSS_2 (sliderNegPos)"] + df_ema["PSS_3 (sliderNegPos)"] + df_ema["PSS_4 (sliderNegPos)"]
df_ema["Safety"] = df_ema["safety (sliderNegPos)"]
#df_ema

In [60]:
# "affect_1 (sliderNegPos)" is happy
# "affect_2 (sliderNegPos)" is energetic
# "affect_3 (sliderNegPos)" is satisfied
# "affect_4 (sliderNegPos)" is relaxed
# "affect_5 (sliderNegPos)" is stressed
# "affect_6 (sliderNegPos)" is anxious
# "affect_7 (sliderNegPos)" is irritated
# "affect_8 (sliderNegPos)" is down

In [61]:
df_ema["Pos_Aff"] = df_ema["affect_1 (sliderNegPos)"] + df_ema["affect_2 (sliderNegPos)"] + df_ema["affect_3 (sliderNegPos)"] + df_ema["affect_4 (sliderNegPos)"]
df_ema["Neg_Aff"] = df_ema["affect_5 (sliderNegPos)"] + df_ema["affect_6 (sliderNegPos)"] + df_ema["affect_7 (sliderNegPos)"] + df_ema["affect_8 (sliderNegPos)"] 
#df_ema

In [62]:
# convert the 'Date and time' column to datetime with the to_datetime function of pandas
df_ema['Date and time'] = pd.to_datetime(df_ema['Date and time'], errors='coerce')
#print(df_ema.head())

# set it as the index
df_ema.set_index('Date and time', inplace=True)

#df_ema

In [64]:
#some participants had their start times for some VU-DAMS files have one hour or one day before/after the recording actually started
#these instances were clearly outlined as the procedures always started around 10:15 am, and the day1 and day2 recording days were always back to back
#we also had additional pieces of information such as the manually written down end time of the procedure, and the m-Path datetimes
#here we shortly go back to the df_awake_ambulatory dataset (will continue working on the df_ema and merging these in the later cells)
from pandas.tseries.frequencies import to_offset

# shifting the day1 epochs for participant 91169 1 hour backwards (earlier)
df_awake_ambulatory.loc[
    (df_awake_ambulatory['participant_id'] == 91169) & 
    (df_awake_ambulatory['day'] == 1), 
    'datetime'
] -= pd.Timedelta(hours=1)

# shifting the day2 epochs for participant 37092 1 day backwards (earlier)
df_awake_ambulatory.loc[
    (df_awake_ambulatory['participant_id'] == 37092) & 
    (df_awake_ambulatory['day'] == 2), 
    'datetime'
] -= pd.Timedelta(days=1)

# shifting epochs 1 hour forwards (later) for both day1 and day2 for the required participants
forward_shift_ids = [46773, 30739, 93676, 37818, 12008, 25201, 88137]

df_awake_ambulatory.loc[
    df_awake_ambulatory['participant_id'].isin(forward_shift_ids) & 
    df_awake_ambulatory['day'].isin([1, 2]), 
    'datetime'
] += pd.Timedelta(hours=1)

In [65]:
df_awake_ambulatory[df_awake_ambulatory['participant_id'] == 91169][['day', 'datetime']].head()
#checking a participant to see if it adjusted correctly, note that we are viewing the part of the dataframe that already excluded the lab portion
#so we see the epochs starting from the end of the procedure, which should indeed start around 11:55:00 --> this is correctly adjusted

       day                datetime
40839    1 2024-04-30 11:55:53.500
40840    1 2024-04-30 11:56:53.500
40841    1 2024-04-30 11:57:53.500
40842    1 2024-04-30 11:58:53.500
40843    1 2024-04-30 11:59:53.500

In [66]:
df_awake_ambulatory[
    (df_awake_ambulatory['participant_id'] == 37092) & 
    (df_awake_ambulatory['day'] == 2)
][['day', 'datetime']].head()
#--> correctly adjusted

       day                datetime
13465    2 2024-05-31 07:52:49.500
13466    2 2024-05-31 07:53:49.500
13467    2 2024-05-31 07:54:49.500
13468    2 2024-05-31 07:55:49.500
13469    2 2024-05-31 07:56:49.500

In [ ]:
#save to also manually check if the calculations worked
df_awake_ambulatory.to_excel("df_withRSA_withDescriptives_shifted.xlsx")   #shifted refers to the fact that we adjusted for some participants
   #their initially off-time (e.g., those who needed to get their day1/day2 files shifted by an hour/day forward/backward)
   #this does not yet have the EMA

In [80]:
df_awake_ambulatory.columns.tolist()

['Unnamed: 0.1',
 'Unnamed: 0',
 'Location',
 'Physical_Exertion',
 'Posture',
 'Social_Situation',
 'Type_Of_Activity',
 'Location_Code',
 'Physical_Exertion_Code',
 'Posture_Code',
 'Social_Situation_Code',
 'Type_Of_Activity_Code',
 'Subject_ID',
 'Label_ID',
 'Start_Date',
 'Start_Time',
 'End_Date',
 'End_Time',
 'Label_Duration_s',
 'Total_Motility_mg',
 'Average_IBI_msec',
 'Average_HR_bpm',
 'SDNN_msec',
 'Respiration_Rate_bpm',
 'Tidal_Volume_mOhm',
 'RMSSD_msec',
 'LF_ms',
 'RSA0_msec',
 'HF_ms',
 'PEP_msec',
 'LVET_msec',
 'TWave_amplitude_mV',
 'Stroke_Volume_(Nederend_2017)_cc',
 'Minute_Volume_(Nederend_2017)_lmin',
 'Average_SCL_uS',
 'nsSCRs_per_minute_ppm',
 'Min_IBI_msec',
 'Max_IBI_msec',
 'RSA_msec',
 'Artefact_Free_ECG_percent',
 'Artefact_Free_Respiration_percent',
 'Majority_postures',
 'participant_id',
 'day',
 'Experimental_Conditions',
 'Experimental_Conditions_Code',
 'Artefact_Free_ECG_s',
 'Calibrated_Tidal_Volume',
 'datetime',
 'Cleaned_Tidal_Volume',
 'RSA0_residual',
 'RSA0_residual_45',
 'Ttot',
 'RSA0_over_Vt',
 'delta_RSA0_over_Ttot_ambulatory',
 'delta_RSA0_over_Ttot_ambulatory_45',
 'delta_RSA0_over_Ttot_laboratory',
 'delta_RSA0_over_Ttot_laboratory_45',
 'delta_RSA0_over_Ttot_laboratory_3',
 'Height',
 'Weight',
 'Sex',
 'Ethnicity',
 'Age',
 'BMI',
 'BMI_Category',
 'Education',
 'IPAQ_SF',
 'Current_Smoking']

In [67]:
import pandas as pd
import numpy as np
# identifying which columns are numerical via np.number and selecting them, while excluding participant id and day 
numeric_cols = df_awake_ambulatory.select_dtypes(include=[np.number]).columns.difference(['participant_id', 'day'])

averaged_physio_data = [] # empty list to store the physiological data
num_epochs_list = []  #empty list to store the number of epochs averaged to reach the 5min averages (it won't always be 5 epochs)
majority_posture_list = [] #empty list to store the majority posture for the 5 min epoch

# iterrows iterates through each row in the dataframe df_ema
for idx, row in df_ema.iterrows():
    pid = int(row['participant_id']) #extract the participant id of the current row
    #we previously set a datetime index to the dataframe df_ema so the time is now in the index (time is no longer in the column)
    ema_time = row.name  # 'Date and time' is the index, so the row.name gets the time when the prompt is answered
    
    # filter the physiological data (from df_awake_ambulatory) between 5 minutes before the EMA prompt and the EMA prompt, for the current participant
    physio_window = df_awake_ambulatory[
        (df_awake_ambulatory['participant_id'] == pid) &
        (df_awake_ambulatory['datetime'] >= ema_time - pd.Timedelta(minutes=5)) &
        (df_awake_ambulatory['datetime'] < ema_time)   #backward-looking 5 minute window
    ]
    
    if not physio_window.empty:  #if this window is not empty (if there is any data)
        averaged_vals = physio_window[numeric_cols].mean()   #calculate the mean for all numerical columns (e.g., RSA0_msec and so on) for this df subset
                                                   #the function .mean on a dataframes operates columnwise by default
        epoch_count = len(physio_window) #the number of epochs in the window
        majority_posture = physio_window['Majority_postures'].mode() #the majority posture is the most frequently occuring posture across epochs
        majority_posture = majority_posture.iloc[0] if not majority_posture.empty else np.nan #if there is a tie, iloc[0] returns the first in the list
    else: #if there is no data in the window
        averaged_vals = pd.Series([np.nan] * len(numeric_cols), index=numeric_cols) #put in NaNs for the numeric columns
        epoch_count = 0  #put in 0 for the number of epochs
        majority_posture = np.nan  #put in NaN for the posture

    averaged_physio_data.append(averaged_vals)
    num_epochs_list.append(epoch_count)
    majority_posture_list.append(majority_posture)

# combine into a dataframe
averaged_df = pd.DataFrame(averaged_physio_data)
averaged_df['num_epochs_averaged'] = num_epochs_list
averaged_df['Majority_posture_5min'] = majority_posture_list

# concatenate the averaged_df with df_ema
df_ema_merged = pd.concat([df_ema.reset_index(), averaged_df], axis=1)
df_ema_merged.set_index('Date and time', inplace=True)

In [1]:
#averaged_df

In [68]:
#the viewing of these ema dataframes are purposefully commented out so the sensitive emotional state data is not be visible on GitHub
#df_ema_merged

In [69]:
len(df_ema_merged)

874

In [71]:
#df_ema_merged["RSA0_msec"]

In [72]:
#drop the rows where no physiological epoch could be found - this would be due to EMA data being answered when the wearable is not worn (e.g., charging)
df_ema_merged = df_ema_merged.dropna(subset=['RSA0_msec'])
#df_ema_merged

In [73]:
len(df_ema_merged)

735

In [75]:
df_ema_merged["Calibrated_Tidal_Volume"]

Date and time
2024-09-02 12:33:26    2.942938
2024-09-02 13:41:26    2.951459
2024-09-02 13:43:25    3.071775
2024-09-02 14:51:48    1.841011
2024-09-02 15:31:20    1.260392
2024-09-02 16:27:28    2.962626
2024-09-02 17:38:32    1.642151
2024-09-02 19:08:06    2.728619
2024-09-03 09:49:05    1.417763
2024-09-03 10:43:35    2.783556
2024-09-03 11:01:59    1.211268
2024-09-03 12:21:23    1.363699
2024-09-03 13:41:40    2.687845
2024-09-03 14:15:02    2.669923
2024-09-03 15:31:37    0.563748
2024-09-03 16:06:52    1.238459
2024-09-03 17:01:49    1.212279
2024-09-03 18:49:39    1.711617
2024-09-03 20:08:05    0.524553
2024-09-03 21:27:19    2.318793
2024-08-09 13:29:16    0.674715
2024-08-09 14:15:31    0.268139
2024-08-09 15:44:03    0.898143
2024-06-25 12:37:02    0.831461
2024-06-25 14:00:27    0.797135
2024-06-25 14:16:44    0.777925
2024-06-25 16:04:13    0.706917
2024-06-25 17:47:32    0.903963
2024-06-25 18:25:38    0.682636
2024-06-25 19:14:39    0.495974
2024-06-25 21:12:15    0.859911
2024-06-25 22:31:37    0.903798
2024-09-17 12:42:12    0.741503
2024-09-17 13:59:02    0.448970
2024-09-17 14:50:05    0.409116
2024-09-17 15:52:28    0.391814
2024-09-17 16:29:14    0.444450
2024-09-17 17:33:38    0.462772
2024-09-17 18:47:00    0.475592
2024-09-17 19:49:38    0.398106
2024-09-17 20:52:59    0.859408
2024-09-17 21:10:02    0.580452
2024-09-17 22:32:42    0.399097
2024-09-18 09:26:17    0.414596
2024-09-18 11:07:51    0.406041
2024-09-18 12:54:39    0.667156
2024-09-18 13:14:48    0.517902
2024-09-18 14:18:05    0.414751
2024-09-18 15:55:44    0.513945
2024-09-18 16:15:51    0.478592
2024-09-18 17:37:41    0.604604
2024-09-18 18:44:36    0.571312
2024-09-18 19:07:36    0.522841
2024-09-18 20:04:23    0.482968
2024-09-18 21:48:08    0.408994
2024-09-18 22:19:46    0.548482
2024-09-10 12:19:04    0.513160
2024-09-10 13:29:54    0.449572
2024-09-10 14:43:02    0.409888
2024-09-10 15:51:38    0.220065
2024-09-10 16:05:35    0.306342
2024-09-10 17:21:01    0.494170
2024-09-10 18:33:55    0.405555
2024-09-10 19:23:57    0.597227
2024-09-10 20:21:53    0.520077
2024-09-10 21:33:47    0.500538
2024-09-11 10:15:34    0.513045
2024-09-11 11:36:06    0.514965
2024-09-11 12:11:51    0.408895
2024-09-11 13:35:51    0.541004
2024-09-11 14:19:48    0.433041
2024-09-11 15:09:34    0.480895
2024-09-11 16:38:50    0.514781
2024-09-11 17:37:35    0.412073
2024-09-11 18:30:32    0.445707
2024-09-11 19:59:30    0.432173
2024-09-11 20:31:10    0.456592
2024-09-11 21:26:10    0.437042
2024-04-12 12:37:12    0.712984
2024-04-12 13:25:00    0.337728
2024-04-12 14:11:18    0.419885
2024-04-12 15:25:53    0.469108
2024-04-12 16:54:06    0.342406
2024-04-12 18:37:34    0.480423
2024-04-12 20:11:08    0.606541
2024-04-12 20:30:36    0.452161
2024-04-13 09:19:24    0.434163
2024-04-13 10:44:10    0.823265
2024-04-13 11:15:39    0.469596
2024-04-13 12:54:33    0.691098
2024-04-13 13:25:50    0.581605
2024-04-13 14:10:00    0.372513
2024-04-13 16:38:50    0.416926
2024-04-13 19:04:27    0.499747
2024-04-13 19:15:30    0.419183
2024-04-13 20:28:11    0.959160
2024-07-04 13:37:17    0.616327
2024-07-04 14:38:58    0.648949
2024-07-04 15:14:16    0.613016
2024-07-04 16:34:20    0.660343
2024-07-04 18:36:42    0.602004
2024-07-04 19:33:46    1.138307
2024-07-04 20:47:31    0.696627
2024-07-04 21:07:07    0.597856
2024-07-04 21:35:14    0.642563
2024-07-05 11:01:54    0.882334
2024-07-05 11:41:45    1.158864
2024-07-05 12:48:56    2.145695
2024-07-05 13:38:38    1.303294
2024-07-05 14:29:06    0.791253
2024-07-05 15:33:01    1.300983
2024-07-05 16:47:31    0.717182
2024-07-05 17:01:05    2.189772
2024-07-05 18:22:20    0.831955
2024-07-05 20:50:40    0.280542
2024-10-03 12:35:42    0.770147
2024-10-03 13:44:17    0.483725
2024-10-03 14:17:20    0.511875
2024-10-03 16:12:40    0.492541
2024-10-03 16:29:39    0.672851
2024-10-03 18:02:15    0.940167
2024-10-03 18:51:53    0.709182
2024-10-03 19:15:33    0.805892
2024-10-03 20:06:29    0.495712
2024-10-04 09:57:11    0.552509
2024-10-04 10:23:54    0.502671
2024-10-04 11:55:34    0.490705
2024-10-04 12:37:12    0.206481
2024-10-04 13:08:40    0.163964
2024-10-04 14:06:43    0.561247
2024-10-04 15:24:50    0.777587
2024-10-04 16:31:05    0.835487
2024-10-04 17:10:06    0.725159
2024-10-04 18:50:05    0.801714
2024-10-04 19:28:15    0.555081
2024-10-04 20:36:30    0.579300
2024-10-04 22:00:39    0.950910
2024-10-04 22:46:06    0.853061
2024-07-11 12:24:50    0.584870
2024-07-11 13:53:39    0.592674
2024-07-11 14:20:57    0.537907
2024-07-11 15:46:47    0.639693
2024-07-11 17:15:04    0.535636
2024-07-11 18:43:26    0.472223
2024-07-11 19:48:03    0.428247
2024-07-11 20:09:59    0.702355
2024-07-11 21:20:58    0.553914
2024-07-11 22:26:02    0.535442
2024-07-12 11:38:05    0.573640
2024-07-12 12:04:18    0.656207
2024-07-12 13:23:35    0.175121
2024-07-12 14:57:08    0.592295
2024-07-12 15:59:16    0.580694
2024-07-12 17:33:38    0.453791
2024-07-12 18:36:10    0.632115
2024-05-15 12:44:10    0.256132
2024-05-15 13:10:45    0.586624
2024-05-15 14:49:55    0.238273
2024-05-15 15:08:09    0.459357
2024-05-15 16:19:00    0.277841
2024-05-15 17:42:12    0.452674
2024-05-15 18:09:25    0.591725
2024-05-15 19:10:47    0.244476
2024-05-15 20:14:46    0.305306
2024-05-16 09:22:40    0.215730
2024-05-16 10:48:19    0.279523
2024-05-16 12:28:53    0.416229
2024-05-16 14:42:50    0.238748
2024-05-16 15:12:49    0.270805
2024-05-16 16:38:40    0.209787
2024-05-16 17:52:43    0.262778
2024-05-16 18:27:06    0.402147
2024-11-07 12:53:22    0.725027
2024-11-07 13:35:01    0.808324
2024-11-07 14:12:08    0.866384
2024-11-07 15:11:22    0.697187
2024-11-07 16:43:20    0.701042
2024-11-07 18:55:11    0.741496
2024-11-07 19:25:25    0.774830
2024-11-07 20:40:44    0.761919
2024-11-07 21:59:57    0.654911
2024-11-08 10:00:49    0.724057
2024-11-08 10:54:01    0.921196
2024-11-08 11:15:46    0.674243
2024-11-08 12:57:57    0.924793
2024-11-08 15:11:57    1.074231
2024-11-08 16:53:40    0.811978
2024-11-08 17:56:41    0.639855
2024-11-08 18:16:03    0.972565
2024-11-08 19:28:02    0.773501
2024-11-08 21:03:01    0.754365
2024-11-08 21:26:41    0.717427
2024-11-08 22:27:37    0.798364
2025-01-28 14:55:50    0.703839
2025-01-28 15:32:57    1.310559
2025-01-28 17:31:04    2.275938
2025-01-29 11:25:25    0.493854
2025-01-29 12:42:44    0.534734
2025-01-29 13:31:26    0.516469
2025-01-29 14:16:52    0.596364
2025-01-29 15:15:23    0.365200
2025-01-29 16:41:21    0.520747
2025-01-29 18:50:33    0.607162
2025-01-29 19:29:20    0.580985
2025-01-29 20:07:23    0.389241
2025-01-29 21:58:01    0.398927
2025-01-29 22:49:05    0.673548
2024-05-30 12:33:07    0.853791
2024-05-30 13:03:32    0.671828
2024-05-30 14:05:20    0.535005
2024-05-30 15:03:43    0.819782
2024-05-30 16:10:14    0.682769
2024-05-30 18:17:20    0.910340
2024-05-30 19:14:33    1.142797
2024-05-30 20:08:31    0.858577
2024-05-30 21:31:02    0.986628
2024-05-30 22:33:18    1.135599
2024-05-31 09:56:44    0.766859
2024-05-31 10:19:26    0.734300
2024-05-31 11:51:40    0.608708
2024-05-31 12:21:56    0.730273
2024-05-31 13:20:22    1.026625
2024-05-31 15:14:05    0.787266
2024-05-31 16:54:17    0.891777
2024-05-31 17:03:41    0.737905
2024-05-31 18:34:23    0.696908
2024-08-20 12:27:23    0.855766
2024-08-20 13:48:10    0.813199
2024-08-20 14:35:20    0.784121
2024-08-20 15:33:30    0.793448
2024-08-20 16:49:44    0.836341
2024-08-20 17:31:58    0.832500
2024-08-20 18:31:34    0.827845
2024-08-20 19:11:19    0.844190
2024-08-20 20:04:12    0.803849
2024-08-21 09:00:39    0.888951
2024-08-21 12:05:49    0.868656
2024-08-21 13:13:13    0.824082
2024-08-21 14:15:44    0.877922
2024-08-21 15:36:36    0.856907
2024-08-21 16:39:25    0.790438
2024-08-21 17:55:49    0.835014
2024-08-21 18:26:14    0.880599
2024-08-21 19:01:34    0.889195
2024-08-21 20:37:47    0.877623
2024-09-11 12:56:03    0.592277
2024-09-11 14:04:37    0.536425
2024-09-11 15:49:06    0.492978
2024-09-11 16:43:55    0.499267
2024-09-11 17:04:32    0.463953
2024-09-11 18:38:36    0.510327
2024-09-11 19:55:19    0.469982
2024-09-11 20:53:38    0.570601
2024-09-12 09:02:58    0.558065
2024-09-12 10:52:29    0.467259
2024-09-12 11:00:40    0.525425
2024-09-12 12:53:55    0.508484
2024-09-12 14:13:09    0.501108
2024-09-12 15:21:24    0.542282
2024-09-12 19:23:34    0.674244
2024-09-12 20:35:03    0.701847
2024-09-12 21:22:50    0.414085
2024-05-23 12:17:17    0.514243
2024-05-23 13:08:13    0.508672
2024-05-23 14:20:39    0.634341
2024-05-23 15:43:29    0.428043
2024-05-23 16:09:10    0.493092
2024-05-23 17:49:31    0.564281
2024-05-23 18:49:14    0.487246
2024-05-23 19:31:44    0.468894
2024-05-23 20:28:01    0.577059
2024-05-23 21:25:45    0.556726
2024-05-24 13:34:08    0.467457
2024-05-24 14:41:22    0.521483
2024-05-24 16:16:48    0.575444
2024-05-24 17:11:49    0.415254
2024-05-24 18:32:10    0.656042
2024-05-24 19:30:18    0.733252
2024-05-24 21:01:20    0.584951
2024-05-24 22:41:02    0.556132
2024-11-01 12:32:09    0.315232
2024-11-01 13:25:14    0.284241
2024-11-01 14:57:07    0.299310
2024-11-01 17:36:55    0.349141
2024-11-01 18:52:31    0.282066
2024-11-01 19:24:04    0.326732
2024-11-01 20:11:48    0.272455
2024-11-01 21:54:16    0.245470
2024-11-02 09:30:33    0.545443
2024-11-02 10:27:55    0.601369
2024-11-02 11:08:30    0.548135
2024-11-02 12:57:40    0.404314
2024-11-02 13:27:07    0.649146
2024-11-02 14:03:19    0.293168
2024-11-02 15:02:27    0.353057
2024-11-02 16:23:08    0.368083
2024-11-02 17:22:43    0.422631
2024-11-02 19:52:39    0.324826
2024-11-02 21:17:15    0.549461
2024-11-02 21:36:20    0.558873
2024-11-02 22:23:11    0.572512
2024-07-09 12:35:26    0.353259
2024-07-09 13:51:22    0.352010
2024-07-09 14:07:52    0.371965
2024-07-09 15:24:15    0.300750
2024-07-10 09:11:59    0.315689
2024-07-10 10:49:31    0.363235
2024-07-10 11:10:57    0.335733
2024-07-10 12:10:44    0.318582
2024-07-10 15:13:55    0.440966
2024-06-26 14:39:55    0.447107
2024-06-26 15:31:15    0.417605
2024-06-26 16:56:31    0.338357
2024-06-26 17:59:57    0.367797
2024-06-26 18:42:17    0.423432
2024-06-26 19:42:41    0.446291
2024-06-26 21:05:43    0.375734
2024-06-26 22:06:26    0.378288
2024-06-27 10:39:49    0.379456
2024-06-27 11:35:03    0.373661
2024-06-27 12:03:17    0.367537
2024-06-27 13:58:57    0.421908
2024-06-27 14:10:10    0.473127
2024-06-27 15:58:03    0.375008
2024-06-27 16:04:37    0.369000
2024-06-27 17:49:01    0.415665
2024-06-27 18:50:12    0.424938
2024-06-27 19:34:24    0.422861
2024-11-13 13:44:23    0.922708
2024-11-13 14:36:57    0.904847
2024-11-13 15:37:44    0.965912
2024-11-13 16:21:20    0.826011
2024-11-13 17:19:38    0.915676
2024-11-13 18:30:38    0.965349
2024-11-13 19:29:03    0.939261
2024-11-13 20:44:20    0.842207
2024-11-13 21:35:44    0.963557
2024-11-13 22:56:42    0.863113
2025-01-16 12:52:25    0.808530
2025-01-16 14:06:04    0.872983
2025-01-16 14:37:44    0.770498
2025-01-16 16:26:05    0.319414
2025-01-16 17:46:07    0.300822
2025-01-16 18:33:43    0.703181
2025-01-16 19:37:28    0.774639
2025-01-16 20:26:29    1.015732
2025-01-16 21:10:18    1.057661
2025-01-17 11:06:09    0.907255
2025-01-17 11:45:15    0.783519
2025-01-17 12:11:02    0.885937
2025-01-17 14:37:25    0.944530
2025-01-17 16:10:26    0.653009
2025-01-17 18:48:27    0.812296
2024-09-26 12:48:54    0.534151
2024-09-26 13:43:20    0.404600
2024-09-26 14:25:15    0.596204
2024-09-26 15:45:24    0.363519
2024-09-26 16:50:42    0.556403
2024-09-26 17:26:58    0.537588
2024-09-26 18:22:16    0.381727
2024-09-26 19:25:18    0.401325
2024-09-26 20:48:49    0.569556
2024-09-26 21:50:40    0.434940
2024-09-26 22:59:30    0.393948
2024-09-27 09:59:26    0.497137
2024-09-27 10:30:21    0.573932
2024-09-27 11:14:13    0.686636
2024-09-27 12:31:20    0.597249
2024-09-27 13:30:28    0.765027
2024-09-27 14:51:10    0.444697
2024-09-27 15:15:07    1.134826
2024-09-27 17:58:33    0.682817
2024-09-27 18:51:34    0.669406
2024-09-27 19:26:32    0.541493
2024-06-11 13:00:22    0.892622
2024-06-11 14:05:57    0.530387
2024-06-11 15:00:13    0.460359
2024-06-11 17:01:09    0.471734
2024-06-11 18:57:42    0.468120
2024-06-11 19:22:25    0.460345
2024-06-11 20:47:19    1.000668
2024-06-12 10:29:10    1.775680
2024-06-12 11:24:10    0.549465
2024-06-12 12:04:20    0.689165
2024-06-12 13:17:29    0.523075
2024-06-12 15:52:05    0.794633
2024-06-12 16:05:51    0.620778
2024-06-12 17:05:07    0.917319
2024-09-19 12:15:20    0.974026
2024-09-19 13:19:04    1.928664
2024-09-19 14:15:21    1.782695
2024-09-19 15:08:10    1.250617
2024-09-19 16:56:51    1.806368
2024-09-19 17:23:37    1.209650
2024-09-19 18:06:11    1.973133
2024-09-19 19:07:14    1.736547
2024-09-19 20:19:43    1.864051
2024-09-19 21:57:32    1.753269
2024-09-19 22:08:26    1.981479
2024-09-20 09:43:31    1.957657
2024-09-20 10:21:43    1.980350
2024-09-20 11:21:33    1.442526
2024-09-20 13:04:51    1.767410
2024-09-20 13:29:52    1.177472
2024-09-20 15:15:30    1.810948
2024-09-20 18:03:08    1.681021
2024-09-20 19:51:12    1.715738
2024-09-20 20:36:10    1.776427
2024-06-24 12:27:36    1.535349
2024-06-24 13:36:17    1.669835
2024-06-24 14:56:54    1.392215
2024-06-24 15:32:01    1.410267
2024-06-24 16:44:00    1.451456
2024-06-24 17:26:11    1.376522
2024-06-24 18:17:43    1.426263
2024-06-24 19:15:25    1.426507
2024-06-24 20:37:26    1.450095
2024-06-24 21:25:51    1.596461
2024-06-24 23:03:30    1.714711
2024-06-25 10:16:04    1.492090
2024-06-25 10:18:40    1.495323
2024-06-25 12:54:28    1.381834
2024-06-25 13:37:51    1.403649
2024-06-25 14:46:02    1.654164
2024-06-25 15:51:56    1.576458
2024-06-25 16:09:03    1.461070
2024-06-25 17:34:50    1.812326
2024-06-25 18:22:28    1.455255
2024-06-25 19:54:04    2.248499
2024-06-25 20:28:36    1.771112
2024-06-25 21:57:36    3.643909
2024-06-25 22:14:49    2.581273
2024-05-14 12:03:11    1.064098
2024-05-14 14:26:15    0.846878
2024-05-14 15:18:05    1.306276
2024-05-14 16:57:22    0.963172
2024-05-14 17:39:04    0.969328
2024-05-14 18:49:57    0.776462
2024-05-14 19:10:45    0.789542
2024-05-14 20:20:52    1.248774
2024-05-14 21:02:28    1.274507
2024-05-14 22:14:55    0.670513
2024-05-15 09:22:02    1.220773
2024-05-15 10:50:49    0.725021
2024-05-15 11:19:17    0.848054
2024-05-15 12:42:20    0.803242
2024-05-15 13:10:52    1.102185
2024-05-15 14:23:09    0.728147
2024-05-15 15:09:47    1.305657
2024-05-15 16:03:21    0.679029
2024-05-15 17:07:38    1.006759
2024-05-15 19:31:52    1.112077
2024-05-15 21:56:36    1.319210
2025-02-03 13:09:04    0.525237
2025-02-03 14:34:11    0.612574
2025-02-03 16:20:33    0.572763
2025-02-03 17:47:14    0.531710
2025-02-03 18:25:28    0.680283
2025-02-03 20:01:16    0.538593
2025-02-03 20:57:57    0.468469
2025-02-03 22:45:59    0.598398
2025-02-04 10:00:55    0.643984
2025-02-04 10:21:02    0.403748
2025-02-04 11:57:21    0.556766
2025-02-04 12:24:24    0.425273
2025-02-04 14:06:04    0.805516
2025-02-04 15:56:06    0.858245
2025-02-04 16:11:00    0.638816
2025-02-04 18:33:20    0.430772
2025-02-04 20:11:13    0.567631
2024-10-31 13:43:09    0.334691
2024-10-31 14:17:56    0.417475
2024-10-31 15:24:18    0.685373
2024-10-31 16:29:50    0.689662
2024-10-31 17:58:00    0.453638
2024-10-31 18:21:09    0.651372
2024-10-31 19:12:52    0.766583
2024-10-31 20:22:00    0.750034
2024-11-01 10:55:39    0.709100
2024-11-01 11:37:05    0.525617
2024-11-01 12:21:43    0.242296
2024-11-01 13:38:12    0.518303
2024-11-01 14:40:38    0.372451
2024-11-01 16:37:44    0.764481
2024-11-01 18:32:35    0.807130
2024-11-01 19:20:10    0.728205
2024-05-01 14:41:48    0.504873
2024-05-01 15:06:44    0.562901
2024-05-01 16:27:59    0.629833
2024-05-01 17:22:44    0.561485
2024-05-01 18:06:35    0.584016
2024-05-01 19:27:22    0.516686
2024-05-01 20:55:02    0.583371
2024-05-01 21:54:01    0.573307
2024-05-01 22:37:59    0.541499
2024-05-02 09:23:37    0.323897
2024-05-02 10:40:37    0.484250
2024-05-02 11:18:02    0.458396
2024-05-02 12:25:34    0.509095
2024-05-02 14:09:03    0.697683
2024-05-02 15:48:33    0.527026
2024-05-02 16:35:47    0.559079
2024-05-02 17:46:32    0.425858
2024-05-02 18:38:47    0.537783
2024-05-02 19:03:18    0.511460
2024-05-02 20:21:39    0.561454
2024-05-02 22:28:32    0.699693
2024-11-14 14:08:43    0.391535
2024-11-14 14:35:22    0.414789
2024-11-14 16:00:56    0.559004
2024-11-14 16:17:27    0.485229
2024-11-14 17:43:32    0.429004
2024-11-14 19:07:58    0.419693
2024-11-14 19:50:18    0.484871
2024-11-14 20:25:24    0.461965
2024-11-14 21:15:25    0.472131
2024-11-14 22:52:22    0.541921
2024-11-15 09:45:04    0.454573
2024-11-15 11:22:49    0.418666
2024-11-15 12:07:11    0.420880
2024-11-15 13:33:01    0.494534
2024-11-15 14:11:54    1.274582
2024-11-15 15:34:41    0.399327
2024-11-15 16:18:29    0.467742
2024-11-15 18:33:30    0.482668
2024-11-15 19:46:11    0.427242
2024-11-15 21:40:41    0.387035
2024-11-15 22:25:37    0.460586
2024-05-16 13:43:26    0.542060
2024-05-16 14:36:29    0.580012
2024-05-16 15:52:16    0.639631
2024-05-16 16:31:28    0.492510
2024-05-16 18:59:37    0.779158
2024-05-16 19:19:48    0.574984
2024-05-16 20:23:19    0.738889
2024-05-16 21:31:05    0.689495
2024-05-16 22:36:11    0.528621
2024-05-17 10:59:16    0.542520
2024-05-17 12:28:30    0.496312
2024-05-17 13:18:41    0.527544
2024-05-17 14:24:58    0.511278
2024-05-17 15:42:51    0.517088
2024-05-17 17:05:46    0.495818
2024-05-17 18:56:20    0.585167
2024-05-17 21:21:34    0.585893
2024-12-05 12:57:08    0.359446
2024-12-05 13:13:48    0.304320
2024-12-05 14:43:23    0.453817
2024-12-05 15:40:19    0.543849
2024-12-05 16:41:33    0.475846
2024-12-05 17:03:27    0.430555
2024-12-05 18:55:32    0.412009
2024-12-05 20:41:45    0.462285
2024-12-06 10:50:19    0.324714
2024-12-06 11:10:12    0.343957
2024-12-06 12:51:17    0.389158
2024-12-06 13:22:53    0.311992
2024-12-06 14:33:33    0.337237
2024-12-06 15:55:05    0.364776
2024-12-06 16:58:31    0.354047
2024-12-06 17:14:29    0.388769
2024-12-06 18:10:26    0.352272
2024-12-06 19:40:46    0.378547
2024-12-06 21:09:15    0.473435
2024-12-06 22:44:25    0.330042
2024-06-19 12:10:06    0.540726
2024-06-19 13:45:46    0.366451
2024-06-19 14:48:19    0.431013
2024-06-19 15:29:52    0.495298
2024-06-19 17:02:34    0.490425
2024-06-19 17:14:59    0.473576
2024-06-19 20:36:50    0.486843
2024-06-19 21:22:45    0.507481
2024-06-20 09:28:10    0.552699
2024-06-20 12:53:51    0.505988
2024-06-20 14:23:01    0.462094
2024-06-20 15:43:35    0.397162
2024-06-20 16:18:18    0.457560
2024-06-20 17:59:01    0.531911
2024-06-20 18:48:30    0.324248
2024-06-20 19:19:01    0.256392
2024-06-20 20:36:06    0.542924
2024-06-20 21:26:16    0.184979
2024-11-15 14:17:05    1.078512
2024-11-15 15:46:49    1.327387
2024-11-15 16:06:37    1.207711
2024-11-15 17:30:56    1.240300
2024-11-15 18:07:54    0.970329
2024-11-15 19:11:01    1.111989
2024-11-15 20:25:46    1.330711
2024-11-16 09:13:47    1.334280
2024-11-16 10:15:04    1.334245
2024-11-16 11:42:39    1.334272
2024-11-16 12:42:55    0.930463
2024-11-16 13:56:55    2.854895
2024-11-16 14:43:33    0.932963
2024-11-16 15:07:15    0.944908
2024-11-16 16:34:03    0.929599
2024-11-16 17:20:11    1.333046
2024-11-16 18:28:38    0.965799
2024-11-16 19:39:20    1.147621
2025-01-24 12:10:46    0.338937
2025-01-24 14:03:17    0.224018
2025-01-24 15:01:56    0.195808
2025-01-24 15:57:18    0.166900
2025-01-24 16:28:08    0.203649
2025-01-24 17:21:45    0.251814
2025-01-24 19:26:32    0.158386
2025-01-25 09:58:20    0.366499
2025-01-25 10:50:41    0.350865
2025-01-25 11:46:17    0.152691
2025-01-25 12:51:50    0.236688
2025-01-25 14:23:13    0.118231
2025-01-25 15:57:25    0.256131
2025-01-25 16:31:06    0.137820
2025-01-25 17:13:18    0.184212
2025-01-25 18:55:01    0.193128
2025-01-25 20:25:22    0.166985
2025-01-25 21:21:38    0.212220
2025-01-25 22:07:18    0.376608
2024-09-20 12:24:27    0.928071
2024-09-20 13:44:41    1.173543
2024-09-20 14:15:28    0.587554
2024-09-20 15:43:35    0.709556

In [76]:
df_ema_merged['Majority_posture_5min'].value_counts(normalize=True) * 100

Majority_posture_5min
Sitting     66.530612
Standing    25.034014
Lying        8.435374
Name: proportion, dtype: float64

In [81]:
df_ema_merged.columns.tolist()

['PSS_1 (sliderNegPos)',
 'PSS_2 (sliderNegPos)',
 'PSS_3 (sliderNegPos)',
 'PSS_4 (sliderNegPos)',
 'safety (sliderNegPos)',
 'location (multipleChoice)',
 'with_who (multipleChoice)',
 'activity_type (multipleChoice)',
 'panas_0 (multipleChoice)',
 'affect_1 (sliderNegPos)',
 'affect_2 (sliderNegPos)',
 'affect_3 (sliderNegPos)',
 'affect_4 (sliderNegPos)',
 'affect_5 (sliderNegPos)',
 'affect_6 (sliderNegPos)',
 'affect_7 (sliderNegPos)',
 'affect_8 (sliderNegPos)',
 'language (multipleChoice)',
 'Self_Speech (sliderNegPos)',
 'consumption (multipleChoice)',
 'system_devspecs (devicespecs)',
 'participant_id',
 'Tot_Stress',
 'Safety',
 'Pos_Aff',
 'Neg_Aff',
 'Age',
 'Artefact_Free_ECG_percent',
 'Artefact_Free_ECG_s',
 'Artefact_Free_Respiration_percent',
 'Average_HR_bpm',
 'Average_IBI_msec',
 'Average_SCL_uS',
 'BMI',
 'Calibrated_Tidal_Volume',
 'Cleaned_Tidal_Volume',
 'Current_Smoking',
 'Experimental_Conditions',
 'Experimental_Conditions_Code',
 'HF_ms',
 'Height',
 'IPAQ_SF',
 'LF_ms',
 'LVET_msec',
 'Label_Duration_s',
 'Label_ID',
 'Location',
 'Location_Code',
 'Max_IBI_msec',
 'Min_IBI_msec',
 'Minute_Volume_(Nederend_2017)_lmin',
 'PEP_msec',
 'Physical_Exertion',
 'Physical_Exertion_Code',
 'Posture',
 'Posture_Code',
 'RMSSD_msec',
 'RSA0_msec',
 'RSA0_over_Vt',
 'RSA0_residual',
 'RSA0_residual_45',
 'RSA_msec',
 'Respiration_Rate_bpm',
 'SDNN_msec',
 'Social_Situation',
 'Social_Situation_Code',
 'Stroke_Volume_(Nederend_2017)_cc',
 'Subject_ID',
 'TWave_amplitude_mV',
 'Tidal_Volume_mOhm',
 'Total_Motility_mg',
 'Ttot',
 'Type_Of_Activity',
 'Type_Of_Activity_Code',
 'Unnamed: 0',
 'Unnamed: 0.1',
 'Weight',
 'delta_RSA0_over_Ttot_ambulatory',
 'delta_RSA0_over_Ttot_ambulatory_45',
 'delta_RSA0_over_Ttot_laboratory',
 'delta_RSA0_over_Ttot_laboratory_3',
 'delta_RSA0_over_Ttot_laboratory_45',
 'nsSCRs_per_minute_ppm',
 'num_epochs_averaged',
 'Majority_posture_5min']

In [82]:
import pandas as pd
#Sex is missing in the df_ema_merged so add that
descriptives_df = pd.read_excel("Descriptives.xlsx")

df_ema_merged['participant_id'] = df_ema_merged['participant_id'].astype(str)
descriptives_df['participant_id'] = descriptives_df['participant_id'].astype(str)

df_ema_merged = pd.merge(df_ema_merged, descriptives_df[['participant_id', 'Sex']], on='participant_id', how='left')  #only keeping the id/sex columns from descriptived
#print(df_ema_merged.head())

In [83]:
df_ema_merged.columns

Index(['PSS_1 (sliderNegPos)', 'PSS_2 (sliderNegPos)', 'PSS_3 (sliderNegPos)',
       'PSS_4 (sliderNegPos)', 'safety (sliderNegPos)',
       'location (multipleChoice)', 'with_who (multipleChoice)',
       'activity_type (multipleChoice)', 'panas_0 (multipleChoice)',
       'affect_1 (sliderNegPos)', 'affect_2 (sliderNegPos)',
       'affect_3 (sliderNegPos)', 'affect_4 (sliderNegPos)',
       'affect_5 (sliderNegPos)', 'affect_6 (sliderNegPos)',
       'affect_7 (sliderNegPos)', 'affect_8 (sliderNegPos)',
       'language (multipleChoice)', 'Self_Speech (sliderNegPos)',
       'consumption (multipleChoice)', 'system_devspecs (devicespecs)',
       'participant_id', 'Tot_Stress', 'Safety', 'Pos_Aff', 'Neg_Aff', 'Age',
       'Artefact_Free_ECG_percent', 'Artefact_Free_ECG_s',
       'Artefact_Free_Respiration_percent', 'Average_HR_bpm',
       'Average_IBI_msec', 'Average_SCL_uS', 'BMI', 'Calibrated_Tidal_Volume',
       'Cleaned_Tidal_Volume', 'Current_Smoking', 'Experimental_Conditions',
       'Experimental_Conditions_Code', 'HF_ms', 'Height', 'IPAQ_SF', 'LF_ms',
       'LVET_msec', 'Label_Duration_s', 'Label_ID', 'Location',
       'Location_Code', 'Max_IBI_msec', 'Min_IBI_msec',
       'Minute_Volume_(Nederend_2017)_lmin', 'PEP_msec', 'Physical_Exertion',
       'Physical_Exertion_Code', 'Posture', 'Posture_Code', 'RMSSD_msec',
       'RSA0_msec', 'RSA0_over_Vt', 'RSA0_residual', 'RSA0_residual_45',
       'RSA_msec', 'Respiration_Rate_bpm', 'SDNN_msec', 'Social_Situation',
       'Social_Situation_Code', 'Stroke_Volume_(Nederend_2017)_cc',
       'Subject_ID', 'TWave_amplitude_mV', 'Tidal_Volume_mOhm',
       'Total_Motility_mg', 'Ttot', 'Type_Of_Activity',
       'Type_Of_Activity_Code', 'Unnamed: 0', 'Unnamed: 0.1', 'Weight',
       'delta_RSA0_over_Ttot_ambulatory', 'delta_RSA0_over_Ttot_ambulatory_45',
       'delta_RSA0_over_Ttot_laboratory', 'delta_RSA0_over_Ttot_laboratory_3',
       'delta_RSA0_over_Ttot_laboratory_45', 'nsSCRs_per_minute_ppm',
       'num_epochs_averaged', 'Majority_posture_5min', 'Sex'],
      dtype='object')

In [84]:
df_ema_merged.to_excel("df_ema_merged.xlsx")    #refers to the EMA prompts of all participants along with the averaged physiological and posture data

# Calculating Descriptive Summary

In [86]:
# loading the descriptives (age, sex, BMI, smoking status, IPAQ will be used later in multilevel modeling)
import pandas as pd
df_descriptives = pd.read_excel("Descriptives.xlsx")

In [87]:
#df_descriptives

In [88]:
# defining special mappings for numeric-coded categorical variables
special_categoricals = {
    'Current_Smoking': {0: 'Non-smoking', 1: 'Smoking'},
    'IPAQ_SF': {1: 'Minimally active', 2: 'Moderately active', 3: 'HEPA active'}
}

# apply the mappings
for col, mapping in special_categoricals.items():
    if col in df_descriptives.columns:
        df_descriptives[col] = df_descriptives[col].map(mapping).astype("category")

# get list of categorical columns (including object types and our recoded ones)
categorical_cols = df_descriptives.select_dtypes(include=["object", "category"]).columns

# loop through and print summaries
for col in df_descriptives.columns:
    print(f"\n--- {col} ---")
    
    if col in categorical_cols:
        value_counts = df_descriptives[col].value_counts(dropna=False, normalize=True) * 100
        for category, percent in value_counts.items():
            print(f"{category}: {percent:.2f}%")
    elif pd.api.types.is_numeric_dtype(df_descriptives[col]):
        col_data = df_descriptives[col].dropna()
        print(f"Mean: {col_data.mean():.2f}")
        print(f"SD: {col_data.std():.2f}")
        print(f"Min: {col_data.min():.2f}")
        print(f"Max: {col_data.max():.2f}")

--- participant_id ---
Mean: 55858.50
SD: 25760.66
Min: 12008.00
Max: 99857.00

--- Height ---
Mean: 167.25
SD: 6.96
Min: 154.00
Max: 187.80

--- Weight ---
Mean: 66.51
SD: 12.45
Min: 49.30
Max: 103.40

--- Sex ---
Female: 85.71%
Male: 14.29%

--- Ethnicity ---
White/Caucasian: 66.67%
West-Asian/ Middle East / North Africa: 16.67%
Mixed race/ethnicity, namely:: 4.76%
South-east asia: 4.76%
Hispanic/Latino: 2.38%
Black (African black, Afro-American,  Afro-Caribbean, African American): 2.38%
East-asian (China, Japan, Taiwan, North- and South Korea): 2.38%

--- Age ---
Mean: 23.81
SD: 6.99
Min: 18.00
Max: 47.00

--- BMI ---
Mean: 23.73
SD: 3.83
Min: 19.30
Max: 36.70

--- BMI_Category ---
Healthy Weight: 78.57%
Overweight: 9.52%
Obesity: 9.52%
Severe Obesity: 2.38%

--- Education ---
Some University coursework completed but no degree (HBO, WO): 38.10%
Completed Secondary School: 33.33%
Master's level degree (MA, MS, MBA): 11.90%
University Bachelors Degree (HBO, WO Bachelor): 11.90%
Doctoral level degree (PhD, JD, MD, DDS): 4.76%

--- IPAQ_SF ---
HEPA active: 76.19%
Moderately active: 21.43%
Minimally active: 2.38%

--- Current_Smoking ---
Non-smoking: 76.19%
Smoking: 23.81%